### ISSUE TITLE
MSVC Error on opening .sln file

### ISSUE THREAD

**Issue by Erotix8210** [mangosR2/scriptdev2#100]
error:

C:\Users\Erotix8210\Downloads\mangosR2-mangos-v0.15-8506-g84ac5df\mangosR2-mangos-84ac5df\src\bindings\scriptdev2\VC100\100ScriptDev2.vcxproj : error  : Die Projektdatei "100ScriptDev2.vcxproj" konnte nicht gelesen werden.
C:\Users\Erotix8210\Downloads\mangosR2-mangos-v0.15-8506-g84ac5df\mangosR2-mangos-84ac5df\src\bindings\scriptdev2\VC100\100ScriptDev2.vcxproj(404,2): Die Projektdatei konnte nicht geladen werden. Ein Name darf nicht mit dem Zeichen '<', hexadezimaler Wert 0x3C, beginnen. Zeile 404, Position 2.

**Comment by rsa** [comment]
https://github.com/mangosR2/mangos/wiki/FAQ

**Comment by KiriX** [comment]
https://gist.github.com/2204625

**Comment by Erotix8210** [comment]
trolol im not dump.. i read stuff before using it... ive used cmake omg.. dont close the issue before asking anything..

**Comment by KiriX** [comment]
MaNGOSR2 Cmake for win is still bugged, dont use it for win.
Another bug - you dont use cmake for mr_SD2 - I see solution files that you run, this is not from cmake...
