### ISSUE TITLE
[ICC] Door to Putricide | Doesn't disappear

### ISSUE THREAD

**Issue by Angarius** [mangosR2/scriptdev2#101]
Good morning.
We have got a little problem in ICC.

I hope it belongs in the "ScriptDev2" area.

When you have killed Festergut and Rotface the door to Professor Putricide should change his visibility.

The door is still displayed, even though it was supposed to disappear.

However, it is possible to go through that door. Although it is still there.
See the screenshots:
1. http://www10.pic-upload.de/29.03.12/hixb5sfhxvyk.jpg
2. http://www10.pic-upload.de/29.03.12/jtmpwmmeejjz.jpg
3. http://www10.pic-upload.de/29.03.12/nfsc237ncufw.jpg

Our Serverinfos:

MaNGOS/0.17.0 (Revision 11928)
mangosR2 branch (2012-03-20 23:51:12 R2 Revision 1811 commit d0249a6b5fca7f7b97a13b769171e40ee78b01c1) for Linux_x64 (little-endian)
Using script library: ScriptDev2 (for MaNGOS 11812+) Revision [2478] Revision R2 [0377](d0249a6b5fca7f7b97a13b769171e40ee78b01c1) 2012-03-20 23:51:12 (Unix)
Using World DB: YTDB_0.14.4_R615_MaNGOS_R11921_SD2_R2448_ACID_R309b_RuDB_R45
Using creature EventAI: ACID 3.0.9b 'Streamlined Perfection' - Full Release for MaNGOS (3.3.5a Client)

Thank you very much.

nice greetings
Angarius

**Comment by carlos93** [comment]
Yes, I confirm it.
