### ISSUE TITLE
[ICC] Professor Putricide

### ISSUE THREAD

**Issue by Angarius** [mangosR2/scriptdev2#102]
Good morning.

We have found some bugs @ Professor Putricide.

-> It is not possible to absorb the puddles on the floor with the creature. It has no function.

See the screenshot:

http://www10.pic-upload.de/30.03.12/apfkdjwxgr8h.jpg

-> The green and orange slime cause no damage. During the phase change, it is true that distribute them no damage.

-> It is possible to attack the bottles. Normally this should not be possible.
Unfortunately it has not been possible to get the sword on the screenshot. For a screenshot, the mouse will disappear.

See the screenshot:

http://www10.pic-upload.de/30.03.12/tixycjfm3a2c.jpg

Our Serverinfos:

MaNGOS/0.17.0 (Revision 11928)
mangosR2 branch (2012-03-20 23:51:12 R2 Revision 1811 commit d0249a6) for Linux_x64 (little-endian)
Using script library: ScriptDev2 (for MaNGOS 11812+) Revision [2478] Revision R2 0377 2012-03-20 23:51:12 (Unix)
Using World DB: YTDB_0.14.4_R615_MaNGOS_R11921_SD2_R2448_ACID_R309b_RuDB_R45
Using creature EventAI: ACID 3.0.9b 'Streamlined Perfection' - Full Release for MaNGOS (3.3.5a Client)

Thank you very much.

nice greetings
Angarius

**Comment by ROKB** [comment]
link broken.

**Comment by Angarius** [comment]
sry. the link works fine

**Comment by michalpolko** [comment]
1. Puddles already fixed.
2. Slimes do deal damage, during phase transition all dmg taken by players is greatly reduced.
3. Attacking bottles fixed in sd2_mr0446
