### ISSUE TITLE
[ICC] Dreamwalker

### ISSUE THREAD

**Issue by Angarius** [mangosR2/scriptdev2#103]
Good morning.

We have found a bug @ Dreamwalker
1. During the fight with Dreamwalker here you can attack the "Lich King"

See the screenshot:
1. http://www10.pic-upload.de/30.03.12/r9o54susunwn.jpg

Our Serverinfos:

MaNGOS/0.17.0 (Revision 11928)
mangosR2 branch (2012-03-20 23:51:12 R2 Revision 1811 commit d0249a6) for Linux_x64 (little-endian)
Using script library: ScriptDev2 (for MaNGOS 11812+) Revision [2478] Revision R2 0377 2012-03-20 23:51:12 (Unix)
Using World DB: YTDB_0.14.4_R615_MaNGOS_R11921_SD2_R2448_ACID_R309b_RuDB_R45
Using creature EventAI: ACID 3.0.9b 'Streamlined Perfection' - Full Release for MaNGOS (3.3.5a Client)

Thank you very much.

nice greetings
Angarius

**Comment by michalpolko** [comment]
AFAIK: DB issue and lack of implementation. This is probably the dummy NPC of Lich King who should yell after defeating the Valithria encounter.
