### ISSUE TITLE
[ICC] Bloodqueen

### ISSUE THREAD

**Issue by Angarius** [mangosR2/scriptdev2#104]
Good morning.

We have found some problems @ Bloodqueen.
1. Once the blood queen was defeated, would normally open the door by the chandelier. This does not. Must step up the run down again.

See the screenshot:
1. http://www10.pic-upload.de/30.03.12/8wp84s4zaeje.jpg
2. When the fight was stopped, were supposed to disappear all debuffs. It does not exist. On the screenshot you can see the vampire bite very well.

See the screenshot:
1. http://www10.pic-upload.de/30.03.12/8wp84s4zaeje.jpg

Maybe contains to: https://github.com/mangosR2/scriptdev2/issues/92
1. During combat, players with the magic of "Swarming Shadows" is highlighted. Here, the player must run to the edge so that it causes no damage to other players.
   The players get this buff, but the veil is not displayed and therefore adds no damage to other players if they get in the way.

Spell:
1. http://www.wowhead.com/spell=71265

See the screenshot:
1. http://static.hordeguides.de/images/wotlk/instance_ic25_203.jpg (lilac mist)

Our Serverinfos:

MaNGOS/0.17.0 (Revision 11928)
mangosR2 branch (2012-03-20 23:51:12 R2 Revision 1811 commit d0249a6) for Linux_x64 (little-endian)
Using script library: ScriptDev2 (for MaNGOS 11812+) Revision [2478] Revision R2 0377 2012-03-20 23:51:12 (Unix)
Using World DB: YTDB_0.14.4_R615_MaNGOS_R11921_SD2_R2448_ACID_R309b_RuDB_R45
Using creature EventAI: ACID 3.0.9b 'Streamlined Perfection' - Full Release for MaNGOS (3.3.5a Client)

Thank you very much.

nice greetings
Angarius

**Comment by michalpolko** [comment]
1. floor is opened after defeating her
2. debuffs are removed thx to somebody's fix
3. Swarming Shadows are working properly
