### ISSUE TITLE
[ICC] Lichking

### ISSUE THREAD

**Issue by Angarius** [mangosR2/scriptdev2#105]
Good morning.

We have found a bug @ Lichking
1. If you use the portal to the Frozen Throne, the "Arthas Platform" does not exist. Thus you put firmly in the ground and can not do anything.

See the screenshot:
1. http://www10.pic-upload.de/30.03.12/7fgns8f37iwf.jpg

Our Serverinfos:

MaNGOS/0.17.0 (Revision 11928)
mangosR2 branch (2012-03-20 23:51:12 R2 Revision 1811 commit d0249a6) for Linux_x64 (little-endian)
Using script library: ScriptDev2 (for MaNGOS 11812+) Revision [2478] Revision R2 0377 2012-03-20 23:51:12 (Unix)
Using World DB: YTDB_0.14.4_R615_MaNGOS_R11921_SD2_R2448_ACID_R309b_RuDB_R45
Using creature EventAI: ACID 3.0.9b 'Streamlined Perfection' - Full Release for MaNGOS (3.3.5a Client)

Thank you very much.

nice greetings
Angarius

**Comment by michalpolko** [comment]
This appears randomly, don't know why, hard to tell.
I saw this only on my localhost.

**Comment by rsa** [comment]
don't forget set
Visibility.Distance.Instances     = 400
(someone need 500)
for true work Frostmourne event. need add to FAQ.

**Comment by Angarius** [comment]
Hello Rsa,

we have set Visibility.Distance.Instances to 400 (original?).
Maybe you have another idea how we can solve this problem.

**Comment by raynar** [comment]
try 500, but on my server still bug with 500 T_T

**Comment by Angarius** [comment]
I will test it and give you feedback.

**Comment by rsa** [comment]
if dropdown _first_ teleported player only, then hardware on server require upgrade...

**Comment by Angarius** [comment]
Sry, but I don't understand your comment. Can you please explain in an other way? Thank you

**Comment by Sar777** [comment]
После вайпа идёт восстановление платформы, но если она не была разрушена, то в
uiPlatformOriginalFlag кривое значение.

After a wipe in the reduction of the platform, but if it was not destroyed, the
uiPlatformOriginalFlag distorting meaning.

https://github.com/Sar777/scriptdev2/commit/67cdd81fcda120df3857d0e7e137559f9c63dbcd ?

**Comment by Angarius** [comment]
I have tested it with 500. It causes the same Problem.

**Comment by Angarius** [comment]
@rsa : Our Hardware

Intel® Core™ i7-2600 Quad-Core
32 GB DDR3 RAM
2 x 3 TB SATA 6 Gb/s HDD 7200 rpm Software-RAID 1
Debian 6 64 Bit
Mysql server ver: 5.1.61-0+squeeze1 
MySQL client library: 5.1.49

**Comment by Sar777** [comment]
Nothing to do with distance, fixes above.

**Comment by Angarius** [comment]
Thank you Sar.
Maybe RSA can apply this fix.

**Comment by michalpolko** [comment]
How can respawning pillars solve problem with spawning _platform_ on client's side? (this appears to a client, other client can see the platform while other cannot)
Or maybe what you reported is not what I encountered.

**Comment by Sar777** [comment]
No need to look at the poles:

```
void DoRespawnPlatform()
{
    if (!m_pInstance)
        return;

    if (!m_bPlatformDestroyed)
        return;

    if (GameObject* pGoFloor = m_pInstance->GetSingleGameObjectFromStorage(GO_ARTHAS_PLATFORM))
    {
        pGoFloor->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_DAMAGED | GO_FLAG_NODESPAWN);
        pGoFloor->SetUInt32Value(GAMEOBJECT_BYTES_1, m_uiPlatformOriginalFlag);
    }

    if (GameObject* pGo = m_pInstance->GetSingleGameObjectFromStorage(GO_FROSTY_WIND))
        pGo->SetGoState(GO_STATE_ACTIVE);

    m_bPlatformDestroyed = false;
}
```

pGoFloor->SetUInt32Value(GAMEOBJECT_BYTES_1, m_uiPlatformOriginalFlag);
m_uiPlatformOriginalFlag - If the platform is not destroyed, then the value of the curve.

Bug is visible only when zanogo portal to Lich

**Comment by rsa** [comment]
may be more simple get original flag state in Reset()?
anywhay, Sar, push changes if sure.
