### ISSUE TITLE
[ICC]blood_prince_council

### ISSUE THREAD

**Issue by ROKB** [mangosR2/scriptdev2#106]
72053 Kinetic Bomb
propelling the bomb higher in the air with each hit.
not work, i hit bomb and still going ground. 8(
and many bugs

**Comment by softbest** [comment]
hi

I rewirte the spell support but it need test : http://pastebin.com/6dJzuSrF

**Comment by ROKB** [comment]
@softbest Hm.. Thx i will test 8P

**Comment by ROKB** [comment]
@softbest 
work fine.
but first time object visual.
and i hit Bomb and I cant see Bomb(invisible but can targeting).
10N Check

**Comment by softbest** [comment]
npc 38454 or 38458??

**Comment by ROKB** [comment]
38454

**Comment by softbest** [comment]
posible fixes, you use the fix 1 but if the fix 1 isn't work you use the fix 2 :

 in blood_prince_council.cpp :
1 : http://pastebin.com/KS28RyXs
or
2 : http://pastebin.com/ifKq6VqH

 when you test these fixes you say if they are work

**Comment by ROKB** [comment]
1,2 something wrong.
cuz http://pastebin.com/6dJzuSrF is remove 

if (!m_creature->HasAura(SPELL_KINETIC_BOMB_VISUAL))
DoCastSpellIfCan(m_creature, SPELL_KINETIC_BOMB_VISUAL, CAST_TRIGGERED);

**Comment by softbest** [comment]
Sorry, I create the patch 1 and 2 without the main patch. I will wirte good

**Comment by ROKB** [comment]
@softbest 
ok 8) waiting you

**Comment by softbest** [comment]
@ROKB 
FULL : http://pastebin.com/aLjLp0h9
Sql : UPDATE creature_template SET modelid_1 = 31095 ,modelid_2 = 19725 WHERE entry= 38454;

need test

**Comment by michalpolko** [comment]
kinetic bombs work properly, closing
