### ISSUE TITLE
Frostthron (202161) - Map-Problem?

### ISSUE THREAD

**Issue by ZuSe** [mangosR2/scriptdev2#109]
All creatueres falling under the map.
mmaps and vmaps are extracted without errors and enabled.
If i remember right michal mentioned that he had to use waypoints in lichking-script, coz mmaps doesnt work with the gameobject (plattform).

So the question is: why doensn't it work anymore?

http://youtu.be/RdqakxACt_g

GreeZ
ZuSe

**Comment by rsa** [comment]
> Frostthrone

what is it?

**Comment by softbest** [comment]
hi

The problem is the mmaps. I think that it need support for mmap 

You can use the option mmap.ignoreMapIds in mangosd.conf for deactivate mmap on icecrown citadel (map : 631)

**Comment by ZuSe** [comment]
@rsa its well written name is Frostthron...
It is the plattform where you fight against the lichking (a gameobject).

@soft:  Michalpolko mentioned that his icc stuff works quite fine with mmaps. There must be an option to disable mmaps on the plattform as it does not work with gameobjects. If i remember right there was a flag in the script or sth similiar.. but i dunno why it does not work anymore.. any ideas?

**Comment by softbest** [comment]
@ZuSe I know the option 'mmap.ignoreMapIds' in mangosd.conf which desactivate all mmap on this map but i don't know the option for desactivate mmap on map zone. I think that the best option is mmap.ignoreMapIds although I don't like desactivate mmap

**Comment by ZuSe** [comment]
yes.. with deactivated mmaps it works fine.. i have already tested it... but that should only be a temporarly option.
I really hope rsa knows a way how to deactivate the mmaps on the gameobject... :)

**Comment by softbest** [comment]
Yes, it is a temporal solution.

@michalpolko say in https://github.com/mangosR2/scriptdev2/issues/92 :

I use mmaps in ICC with no problems, only in Lich King encounter I will have to set special flag for mobs to make them not use pathfinding, because platform is a gameobject.

**Comment by rsa** [comment]
currently usage mmaps on GO type 33 impossible. need implement feature from #770
