### ISSUE TITLE
Crash in boss_dredAI::UpdateAI

### ISSUE THREAD

**Issue by Undergarun** [mangosR2/scriptdev2#11]
http://pastebin.com/WXpCzfFf

**Comment by ghost** [comment]
Is ScriptDev2 isn't any boss_dred.cpp.....

EDIT: Sorry, I didn't notice that I'm at R2 :P

**Comment by ghost** [comment]
https://github.com/mangosR2/scriptdev2/blob/master/scripts/northrend/draktharon_keep/boss_dred.cpp

**Comment by ghost** [comment]
Ill look at this tonight when I get home

**Comment by ghost** [comment]
https://github.com/mangosR2/scriptdev2/commit/9faa336193199714c6ccce9042938e23f4dc14f4
