### ISSUE TITLE
[ICC]Sindragosa

### ISSUE THREAD

**Issue by ROKB** [mangosR2/scriptdev2#110]
69762
10 max 2man
25 max 5man
but now all man debuff

**Comment by carlos93** [comment]
https://github.com/Radicalmangos/devmangos/commit/ef7316ed7a5bf1417aae319c513a96c2c83e4e3c

Test it ;)

**Comment by ROKB** [comment]
@carlos93 
thx i will check right now 8)

**Comment by Sar777** [comment]
Work it?

**Comment by ROKB** [comment]
@Sar777 Work Fine :P

**Comment by michalpolko** [comment]
fixed in mr2077
