### ISSUE TITLE
[ICC]PUTRICIDE

### ISSUE THREAD

**Issue by ROKB** [mangosR2/scriptdev2#111]
Abomination eat poison work on only 10N
the other level not work.

10n only small and remove poison.

**Comment by Inquisitor** [comment]
Confirmed.

**Comment by Angarius** [comment]
Together with #102

---

-> It is not possible to absorb the puddles on the floor with the creature. It has no function.

See the screenshot:

http://www10.pic-upload.de/30.03.12/apfkdjwxgr8h.jpg

---

**Comment by Romman** [comment]
@rsa What do you think about this hack:
<a href="https://github.com/Sar777/mangos/commit/f586aebbd2ec726c660927fdb2dfff29ec782b23">Hacky fix "Eat Ooze" spell enabling</a>
Is it legal way to activate Abomination's spells?

**Comment by rsa** [comment]
as i think, this - bad way. your may 1) reconstruct 3-4 difficulty in spell_dbc or 2) true correct aurasearch system to fit in this check metodic (as i think, search must return not only 70346, but also all difficultyes)
need yse much more common methods...

**Comment by Romman** [comment]
Difficulties for 70360 (Eat Ooze):
70360 / 72527 / 0 / 0.

Difficulties for 70346 (Slime Puddle):
70346 / 72456 / 72868 / 72869

По spell.dbc чтобы есть лужи, нужно иметь на себе ауры (для 70360 это аура 70346, для 72527 это 72456)
Однако это для 10N и 25N

Для 10H и 25H, ауры луж другие, но спел пожирания луж ищет ауры с нормы

Проблема в том чтобы на героическом режиме спелы пожирания луж неактивны, так как не удовлетворяют условиям каста.
И в данном случае, активным быть спелу или нет решает <b>клиентская сторона</b>, но не сервер.

P.S Я сам понимаю что хак плохой и очень глупый, но с ним всё работает как нужно :(

**Comment by rsa** [comment]
все равно так опасно хакать не стоит. если проблема точно в клиенте, и он ищет именно спелл по иду (похоже на то...) то надо просто положить думми-ауру от 72456 "в параллель" к 72869, в методе HandleSpellSpecificBoost. Или даже еще лучше, немного доделать метод linked_spell для этого (наложение только одной ауры из спелла) и прописать в базе.

**Comment by Romman** [comment]
Я и Sar не один час потратили чтобы понять, что как базу сервера не меняй, а клиент сам по своим dbc проверит условия: можно ли в данный момент использовать заклинание(активно) или нельзя(неактивно).
[Даже менял в клиенте в MPQ значения полей в dbc, чтобы удостовериться]

Я пытался именно при касте Effect1 (Apply aura: Dummy) спела 72868 заменить ауру от спела сложности нормы(70346), чтобы урон от Effect0 (School damage) оставался свой для каждой из 4х сложностей. Но опыта маловато, чтобы сделать правильным способом.

Хотя на трини сделали <a href="https://github.com/TrinityCore/TrinityCore/commit/0ab5cdef2e1b700c60fbe3c807206c3369b7fc1a#diff-8"><code>вот так</code></a>

**Comment by rsa** [comment]
ну вот на трине как раз и добавили думмиауру в параллель 

GetCaster()->AddAura((GetCaster()->GetMap()->GetSpawnMode() & 1) ? 72456 : 70346, target);

, у них видимо работает. а мы зачем велосипед изобретаем?
а, сорри, они заменяют. ну не думаю что есть принципиальная разница.

**Comment by Romman** [comment]
Они заменяют спел целиком, то есть с эффектом нанесения урона

**Comment by rsa** [comment]
надо положить только 2ю ауру от нужного спелла в параллель вручную. это и явно проще чем у трини и должно работать как минимум не хуже. а хак примерно одного уровня гадостности...

**Comment by Inquisitor** [comment]
I have only one question: if there are wrong spells, how this is handled on official server? I mean, how official server tells client to land right aura?

---

У меня только один вопрос - если тут неправильные ауры и они делают неправильный код, то как это пашет на официалке? Т. е., если клиент такой "неправильный", то почему на оффе спеллы включаются?

**Comment by rsa** [comment]
сниффов нет - глянуть негде. но я думаю есть 2 варианта - 1) сложности 3 и 4 в ЦЛК вообще не используются 2) действительно сложность 1 идет в параллель к 3 а 2 к 4.

**Comment by Inquisitor** [comment]
Кстати, может ли это быть связано с "горячим" переключением сложностей?

**Comment by rsa** [comment]
именно. я подозреваю, что кроме боссов и части спеллов, больше ничего в цлк не переключается. в тех сниффах что я видел, спеллы обычно шли 1 и 2 сложности, 3 и 4 ни разу не видел.

**Comment by Inquisitor** [comment]
А в других инстах?

**Comment by Romman** [comment]
Все 4 сложности имеет только Испытание Крестоностца
А ЦЛК и Рубиновое Святилище только 1 и 2

**Comment by ZuSe** [comment]
english pls... google translator gets a lot of rubbish

**Comment by rsa** [comment]
:) this writtem mostly not in russian, but in s-lang. main idea - difficultyes 3 && 4 not must be used in some ICC/RS spells.

**Comment by michalpolko** [comment]
fixed in mr2076
