### ISSUE TITLE
[Karazhan] Boss Midnight

### ISSUE THREAD

**Issue by Angarius** [mangosR2/scriptdev2#112]
Hello scriptdev2-Team,

I have found a little Bug @Boss_midnight.

/\* ScriptData
SDName: Boss_Midnight
SD%Complete: 90
SDComment: Use SPELL_SUMMON_ATTUMEN and SPELL_SUMMON_ATTUMEN_MOUNTED instead of SummonCreature.
SDCategory: Karazhan
EndScriptData */

The hunter Attumen should sit on the horse Midnight direktly at the beginning of the fight and descend a little time later. But the rider doesn't appear once during the fight

I've found a little Movie @Youtube: 

http://www.youtube.com/watch?v=wgm8ah6BSuw&feature=related

Our Server Infos:

MaNGOS/0.17.0 (Revision 11928)
mangosR2 branch (\* \* R2 Revision 1823 commit 68c61e1f788e9a31149990a2c9c291e544162aa9) for Linux_x64 (little-endian)
Verwende Script-Bibliothek: ScriptDev2 (for MaNGOS 11812+)_2319_RuDB_43Revision [2484] Revision R2 [0379](68c61e1f788e9a31149990a2c9c291e544162aa9) \* \* (Unix)
Verwende World-DB: YTDB_0.14.4_R614_MaNGOS_R11878_SD2_R2403_ACID_R309b_RuDB_R45

Thanks in advance.

Angarius

**Comment by softbest** [comment]
is The hunter Attumen a player??

**Comment by Angarius** [comment]
No. This is a Boss which sits on the Horse.

-> SDComment: Use SPELL_SUMMON_ATTUMEN and SPELL_SUMMON_ATTUMEN_MOUNTED instead of SummonCreature.

**Comment by Angarius** [comment]
http://wowdata.getbuffed.com/npc/Attumen-the-Huntsman-15550
http://wowdata.getbuffed.com/npc/Attumen-the-Huntsman-16152

**Comment by softbest** [comment]
Ok, I will see the code I try add code for repair this

**Comment by Angarius** [comment]
best thing would be if you could watch the bossfight on youtube
http://www.youtube.com/watch?v=wgm8ah6BSuw&feature=related

**Comment by Angarius** [comment]
The same problem exists on TC:
https://github.com/TrinityCore/TrinityCore/commit/b1c4e8202e0c3f3a18811bda13e6f32bb0644864

**Comment by Sar777** [comment]
Attumen from a text is not climbs :(

**Comment by Angarius** [comment]
Sry, but I don't understand what you mean. Can you please explain this in a better way?
Maybe you can speak german :-)

**Comment by Sar777** [comment]
Attumen не вылазит из под текстур, почему то, но бывает и всё ок

**Comment by Schmoozerd** [comment]
Just 4y info
Wenn Du hier einen BugReport postest, dann wird er das scriptdev2 team höchstens über Umwege erreichen.
Besser geeignete Orte für Bugreports bezüglich echten SD2 skripten sind das sd2 forum, github.com/scriptdev2/scriptdev2 oder irc - wo es sogar einen deutschsprachigen channel git (irc.rizon.net #sd2-german)

**Comment by rsa** [comment]
@Schmoozerd, Beitrag Bug-Reports in bestimmten Orten wird Sinn machen, wenn jemand auf ihrer regulären Arbeit. Leider zeigt die Praxis des vergangenen Jahres, dass der Einsatz es irgendwelche Fragen oder Probleme macht einfach keinen Sinn.

**Comment by Angarius** [comment]
Wenn hier schon so schön in Deutsch gesprochen wird, schließe ich mich einfach mal an.
Was ist euch den lieber?
Hier über Github Probleme zu melden, oder nur noch im IRC oder soll das ganze über das Forum passieren?

**Comment by Schmoozerd** [comment]
Ich wollte lediglich darauf hinweisen, dass das _hier_ kein offizieller Ort für ScriptDev2 probleme ist. Während Du in Deinem Post so geklungen hast, als ob Du das SD2 Team erreichen wolltest, hattest Du nunmal keinen Ort für Deinen Report gewählt, den das SD2 Team im Allgemeinen finden würde.

Offizielle Orte von SD2 sind:
www.scriptdev2.com
https://github.com/scriptdev2/scriptdev2
sowie auf irc.rizon.net die channels #scriptdev2 (bzw. deutschsprachiger channel #sd2-german
