### ISSUE TITLE
New crash in boss thermaplugg (Possible related to #917)

### ISSUE THREAD

**Issue by Undergarun** [mangosR2/scriptdev2#114]
http://pastebin.com/VuNLeJVw

https://github.com/mangosR2/mangos/issues/917

**Comment by rsa** [comment]
news?

**Comment by Undergarun** [comment]
Not happens anymore. Can be closed ;-)

**Comment by Undergarun** [comment]
http://pastebin.com/7fz1Y6qj

**Comment by Undergarun** [comment]
Completely fixed, thank you!
