### ISSUE TITLE
[ICC] Professor Putricide #3

### ISSUE THREAD

**Issue by Angarius** [mangosR2/scriptdev2#116]
Hello together -

I have found another Bug @Professor Putricide.

Bug:

In the 3. Phase you are able to convert in the monstrosity.

-> When changing from phase 2 to phase 3 you should be independently turned back.
-> In the 3rd Phase you should not be able to transform.

Our Server Infos:

MaNGOS/0.17.0 (Revision 11943)
mangosR2 branch (\* \* R2 Revision 1868 commit *) for Linux_x64 (little-endian)
Verwende Script-Bibliothek: ScriptDev2 (for MaNGOS 11942+) Revision [2506] Revision R2 [0386](*) \* \* (Unix)
Verwende World-DB: YTDB_0.14.4_R618_MaNGOS_R11930_SD2_R2486_ACID_R309c_RuDB_R47
Verwende creature EventAI: ACID 3.0.9c 'Streamlined Perfection' - Full Release for MaNGOS (3.3.5a Client)

Thanks in advance 

greetz Angarius

**Comment by ZuSe** [comment]
confirmed
Tested on todays rev with YTDB 619 on Windows_x64
