### ISSUE TITLE
[ICC] Event before Boss Dreamwalker

### ISSUE THREAD

**Issue by Angarius** [mangosR2/scriptdev2#117]
Hello together -

I have found another Bug @Event before Boss Dreamwalker

Screenshots:

http://www10.pic-upload.de/11.04.12/rjhb7vdpcy5.jpg
http://www7.pic-upload.de/11.04.12/8netpfautu6q.jpg
http://www10.pic-upload.de/11.04.12/mat76if9k6rg.jpg

Bug:

1.

The Event is still runing when you have been portet to Icecrown Citadel (After Deathbringers Rise).
Some creatures look looked as if they were dead, although they are not.
You can still attack them and kill them too.

2.

Maybe related to Point 1.
The blue Door is missing. 
-> The door-meaning you can see the Council (color: red)

When you join the Instance with a GM Account you can see the Door
with .gm on. 

Our Server Infos:

MaNGOS/0.17.0 (Revision 11943)
mangosR2 branch (\* \* R2 Revision 1868 commit *) for Linux_x64 (little-endian)
Verwende Script-Bibliothek: ScriptDev2 (for MaNGOS 11942+) Revision [2506] Revision R2 [0386](*) \* \* (Unix)
Verwende World-DB: YTDB_0.14.4_R618_MaNGOS_R11930_SD2_R2486_ACID_R309c_RuDB_R47
Verwende creature EventAI: ACID 3.0.9c 'Streamlined Perfection' - Full Release for MaNGOS (3.3.5a Client)

Thanks in advance 

greetz Angarius

**Comment by michalpolko** [comment]
Door - wrong phase prolly
Dead mobs - flags in database (appears only on some difficulties of those mobs)

**Comment by Sar777** [comment]
@michalpolko 
aura 65985 in creature_template_addon entry =38132
