### ISSUE TITLE
[ICC] Bloodqueen #2

### ISSUE THREAD

**Issue by Angarius** [mangosR2/scriptdev2#118]
Hello together -

I have found another Bug @Bloodqueen

Bug:

You are able to open the "Door" with mode .gm off (normal user).
-> Doodad_IceCrown_Gate_01

-> After an Update the Door opens automatically, but you can still open it manually XD

Update from @Sar777 
https://github.com/mangosR2/scriptdev2/commit/956facc35aa4e1786929ec1bb42374f001a79fec

-> See Point 1 @ https://github.com/mangosR2/scriptdev2/issues/104

---

Once the blood queen was defeated, would normally open the door by the chandelier. This does not. Must step up the run down again.

---

Our Server Infos:

MaNGOS/0.17.0 (Revision 11943)
mangosR2 branch (\* \* R2 Revision 1868 commit *) for Linux_x64 (little-endian)
Verwende Script-Bibliothek: ScriptDev2 (for MaNGOS 11942+) Revision [2506] Revision R2 [0386](*) \* \* (Unix)
Verwende World-DB: YTDB_0.14.4_R618_MaNGOS_R11930_SD2_R2486_ACID_R309c_RuDB_R47
Verwende creature EventAI: ACID 3.0.9c 'Streamlined Perfection' - Full Release for MaNGOS (3.3.5a Client)

Thanks in advance 

greetz Angarius

**Comment by Sar777** [comment]
-> After an Update the Door opens automatically, but you can still open it manually XD

Tested for R2 server?
Rev 0386

**Comment by Angarius** [comment]
I'm sorry that I can not test, because this instance is starting to level 80 and I need a raid. The time to level up, unfortunately I have not, so I can not test it on the R2 test server.

There are no commands like .level or .gm on

**Comment by Sar777** [comment]
> Once the blood queen was defeated, would normally open the door by the chandelier. This does not. Must step up the run down again.

http://www.youtube.com/watch?v=leynpGTkq2M&feature=relmfu 2:00

**Comment by Angarius** [comment]
The function with the chandelier works fine. But you're able to click Doodad_IceCrown_Gate_01 and open that "gate".
The works before the fight has started.
(sry for my bad english)
