### ISSUE TITLE
[ICC]DREAMWALKER

### ISSUE THREAD

**Issue by ROKB** [mangosR2/scriptdev2#119]
Mana Void is moving and moving player

**Comment by Sar777** [comment]
Puddle (Mana void) stands on the site ... If you're talking about is

**Comment by Angarius** [comment]
Do you mean the black circles on the floor?
Or the circles which push you up in the air?

**Comment by ROKB** [comment]
http://i.bsvr.net/i/20100208161451461.jpg

this object is moving

**Comment by Angarius** [comment]
Ok. That's the mana - burning thing XD

**Comment by ROKB** [comment]
@Angarius 
8P

**Comment by Angarius** [comment]
XD

**Comment by Sar777** [comment]
Can anyone else confirm this?

**Comment by carlos93** [comment]
for me works ok :S

**Comment by ROKB** [comment]
hm...... whats the problem 8(

**Comment by Angarius** [comment]
I will test this and give you feedback.
ICC 10/25 HC or NHC?

**Comment by ROKB** [comment]
i check 25N

**Comment by michalpolko** [comment]
Missing script either in sd2 or in EAI.
