### ISSUE TITLE
Crash onGossipSelect related to Trial of the Crusaders

### ISSUE THREAD

**Issue by Undergarun** [mangosR2/scriptdev2#12]
http://pastebin.com/ZT0Jp4V4

This happened to me some months ago, i closed TOC for several weeks and after all saves were cleaned everything wents well again. For some reason, an unknown behavior on players make this happens.

**Comment by ghost** [comment]
ive been trying to reproduce this crash  and have unable to   .... i play locally so i might never see this  we'll have t wait and see if we can get a new info 8P
