### ISSUE TITLE
Crash in Dire maul

### ISSUE THREAD

**Issue by Undergarun** [mangosR2/scriptdev2#121]
http://pastebin.com/9F2prNa3
http://pastebin.com/YJjM1TGQ
http://pastebin.com/CxheW06X

**Comment by rsa** [comment]
any news after sd2_mr0387?

**Comment by Undergarun** [comment]
Still happening

**Comment by Undergarun** [comment]
New crashes:
http://pastebin.com/T5FKvpVD
http://pastebin.com/bEGp6meL

**Comment by rsa** [comment]
> Unit::DealDamage (this=0x0,
> spellProto = 0x0

co0l :) i'm crazy :)

**Comment by Undergarun** [comment]
http://pastebin.com/N9jdav83

**Comment by Undergarun** [comment]
Still here http://pastebin.com/r11s48Vk

**Comment by Undergarun** [comment]
Still crashing http://pastebin.com/PKtBaDKn :(

**Comment by Undergarun** [comment]
Finally fixed, thank you.
