### ISSUE TITLE
[ICC] Dreamwalker #2

### ISSUE THREAD

**Issue by Angarius** [mangosR2/scriptdev2#122]
Hello together -

I have found another Bug @Dreamwalker:

Bug:
The Boss should have Auto-Aggro when the Creatures spawn from the Doors on the left and right side.

-> Currently running the creatures directly to the players. Therefore the boss Dreamwalker gets no damage.

Our Server Infos:

MaNGOS/0.17.0 (Revision 11943)
mangosR2 branch (\* \* R2 Revision 1868 commit *) for Linux_x64 (little-endian)
Verwende Script-Bibliothek: ScriptDev2 (for MaNGOS 11942+) Revision [2506] Revision R2 [0386](*) \* \* (Unix)
Verwende World-DB: YTDB_0.14.4_R618_MaNGOS_R11930_SD2_R2486_ACID_R309c_RuDB_R47
Verwende creature EventAI: ACID 3.0.9c 'Streamlined Perfection' - Full Release for MaNGOS (3.3.5a Client)

Thanks in advance 

greetz Angarius

**Comment by michalpolko** [comment]
How much threat should be added for the boss to each of the summoned creatures?

**Comment by michalpolko** [comment]
attacking of Valithria after adds spawn - fixed

amount of threat may need adjusting
