### ISSUE TITLE
[ICC] Bloodqueen #3

### ISSUE THREAD

**Issue by Angarius** [mangosR2/scriptdev2#123]
Hello together -

I have found another Bug @Bloodqueen:

Bug:

First you become the "Vampire Bite" then you will get the Buff "Essence of the Blood Queen".
After a few seconds you should be covered by the Blood Queen, if you do not have another bite.
You will get the Buff from Frenzied Bloodthirst.

-> If you have not bitten, you will not be a vampire.

Spells:

-> Vampiric Bite
100 yd range
Deals 8325 to 9675 damage to the target, granting them the Essence of the Vampyr Queen.

http://www.wowhead.com/spell=71727

-> Essence of the Blood Queen

100 yd range
You are infused with the blood of the Vampyr Queen. Damage done increased by 100%.
Attacks heal caster.

http://www.wowhead.com/spell=70867

-> Frenzied Bloodthirst

Unlimited range
The caster must satiate their need for blood, otherwise they will lose their will to Queen Lana'thel.

http://www.wowhead.com/spell=70877

Our Server Infos:

MaNGOS/0.17.0 (Revision 11943)
mangosR2 branch (\* \* R2 Revision 1868 commit *) for Linux_x64 (little-endian)
Verwende Script-Bibliothek: ScriptDev2 (for MaNGOS 11942+) Revision [2506] Revision R2 [0386](*) \* \* (Unix)
Verwende World-DB: YTDB_0.14.4_R618_MaNGOS_R11930_SD2_R2486_ACID_R309c_RuDB_R47
Verwende creature EventAI: ACID 3.0.9c 'Streamlined Perfection' - Full Release for MaNGOS (3.3.5a Client)

Thanks in advance 

greetz Angarius

**Comment by michalpolko** [comment]
I don't understand this report... Explain more clearly pls.

**Comment by michalpolko** [comment]
If you meant that Mind Control doesn't work, then yes, it wasnt at all implemented back then, right now faction is changed to Queen's.

I'm closing the issue since bug is in core - lack of proper aoe mind control aura implementation.
