### ISSUE TITLE
Professor Putricide

### ISSUE THREAD

**Issue by KiriX** [mangosR2/scriptdev2#127]
Работа босса Профессор Мерзцоид несколько кривовата. В связи с этим его практически нереально убить. При касте 70351 (самый первый каст) он вызывает 37697. Пока не убит этот моб, следующего каста 70351 не должно быть! Соответственно, не должно призываться больше аддов. Кстати, при втором касте, адд другой и работает верно, вот только он не должен кастовать пока жив первый адд.

When boss cast 70351 he summon 37697. While 37697 is alive boss should not cast 70351 again, but he did...
Next cast and next summon work correct.

**Comment by michalpolko** [comment]
Are you sure that new ones shouldnt be summoned until the previously summoned ooze is still alive? Any source?
I havent seen a youtube video, where players would keep the ooze alive for longer than 10 secs after spawning the other - opposite one, so I assume that there is no such restriction for summoning of the oozes.

**Comment by michalpolko** [comment]
No proofs nor any respond - closing.
