### ISSUE TITLE
[win]crash in 1962

### ISSUE THREAD

**Issue by ROKB** [mangosR2/scriptdev2#128]
Exception code: C0000005 ACCESS_VIOLATION
Fault address:  000000002D63CADC 01:000000000010BADC C:\server\mangosscriptR2.dll

Registers:
RAX:000000027567D009
RBX:000000002CF5D6E8
RCX:0000000000000000
RDX:0000000000000000
RSI:0000000000000000
RDI:00000000314E48B0
R8: 0000000001BF7170
R9: 000000002F91F2F0
R10:0000000001D4E840
R11:0000000000000064
R12:0000000000000024
R13:0000000000000000
R14:0000000000000005
R15:0000005E00000001
CS:RIP:0033:000000002D63CADC
SS:RSP:002B:000000002DABEB60  RBP:2CF5D5E0
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010206

Call stack:
Address   Frame     Function      SourceFile
000000002D63CADC  000000002DABEBA0  instance_draktharon_keep::GetSummonDummy+8C  c:\mangos\src\bindings\scriptdev2\scripts\northrend\draktharon_keep\instance_draktharon_keep.cpp line 211
000000002D63B003  000000002DABEC10  boss_novosAI::UpdateAI+363  c:\mangos\src\bindings\scriptdev2\scripts\northrend\draktharon_keep\boss_novos.cpp line 238
000000014015A675  000000002DABEC60  ?Update@Creature@@UEAAXII@Z+4E5
00000001400C1505  000000002DABECA0  ??0?$GridReference@V?$NGrid@$07VPlayer@@U?$TypeList@VPlayer@@U?$TypeList@VCreature@@U?$TypeList@VCorpse@@U?$TypeList@VCamera@@VTypeNull@@@@@@@@@@U?$TypeList@VGameObject@@U?$TypeList@VCreature@@U?$TypeList@VDynamicObject@@U?$TypeList@VCorpse@@VTypeNull@@@@@@@@@@@@@@QEAA@XZ+28A5
00000001400C5E45  000000002DABECD0  ?SetZoneWeather@Map@@QEAA_NIW4WeatherType@@M@Z+10C5
00000001400D8F89  000000002DABFDE0  ?Update@Map@@UEAAXAEBI@Z+3C9
00000001402D7BA0  000000002DABFE10  ?HandleReloadAllCommand@ChatHandler@@IEAA_NPEAD@Z+9FA0
00000001405626D9  000000002DABFE40  ?HandleWardenDataOpcode@WorldSession@@QEAAXAEAVWorldPacket@@@Z+BE09
000007FEF3769941  000000002DABFE70  ?svc_run@ACE_Task_Base@@SAKPEAX@Z+41
000007FEF3769EE5  000000002DABFEB0  ?invoke_i@ACE_Thread_Adapter@@EEAAKXZ+45
000007FEF376A011  000000002DABFEF0  ?invoke@ACE_Thread_Adapter@@UEAAKXZ+71
00000000728D1D9F  000000002DABFF20  _endthreadex+43
00000000728D1E3B  000000002DABFF50  _endthreadex+DF
000000007709652D  000000002DABFF80  BaseThreadInitThunk+D
000000007753C521  000000002DABFFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
000000007756135A  000000000012FAE0  NtWaitForSingleObject+A
000007FEFDA610AC  000000000012FB80  WaitForSingleObjectEx+9C
000007FEF36EB86A  000000000012FBB0  ?__ace_assert@@YAXPEBDH0@Z+39A
000007FEF376E127  000000000012FC30  ?wait_task@ACE_Thread_Manager@@QEAAHPEAVACE_Task_Base@@@Z+237
00000001402D9BDE  000000000012FC60  ?HandleReloadAllCommand@ChatHandler@@IEAA_NPEAD@Z+BFDE
0000000140059AB2  000000000012FE30  ??4BarGoLink@@QEAAAEAV0@AEBV0@@Z+4272
0000000140055D61  000000000012FF20  ??4BarGoLink@@QEAAAEAV0@AEBV0@@Z+521
000000014005D5CE  000000000012FF50  ?at_exit@MaNGOS@@YAXP6AXXZ@Z+7FE
000000007709652D  000000000012FF80  BaseThreadInitThunk+D
000000007753C521  000000000012FFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00000000775618CA  00000000024DFCB0  ZwWaitForMultipleObjects+A
000000007752B007  00000000024DFF50  TpIsTimerSet+907
000000007709652D  00000000024DFF80  BaseThreadInitThunk+D
000000007753C521  00000000024DFFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
000000007756165A  00000000025DFD60  ZwDelayExecution+A
000007FEFDA61203  00000000025DFE00  SleepEx+B3
000000014006EE26  00000000025DFE50  ??0BarGoLink@@QEAA@_K@Z+9E6
000000014007052A  00000000025DFE80  ??0BarGoLink@@QEAA@_K@Z+20EA
000000014006ECDF  00000000025DFEB0  ??0BarGoLink@@QEAA@_K@Z+89F
000007FEF3740A95  00000000025DFEF0  ?invoke@ACE_OS_Thread_Adapter@@UEAAKXZ+55
00000000728D1D9F  00000000025DFF20  _endthreadex+43
00000000728D1E3B  00000000025DFF50  _endthreadex+DF
000000007709652D  00000000025DFF80  BaseThreadInitThunk+D
000000007753C521  00000000025DFFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
000000007756165A  000000000276FD60  ZwDelayExecution+A
000007FEFDA61203  000000000276FE00  SleepEx+B3
000000014006EE26  000000000276FE50  ??0BarGoLink@@QEAA@_K@Z+9E6
000000014007052A  000000000276FE80  ??0BarGoLink@@QEAA@_K@Z+20EA
000000014006ECDF  000000000276FEB0  ??0BarGoLink@@QEAA@_K@Z+89F
000007FEF3740A95  000000000276FEF0  ?invoke@ACE_OS_Thread_Adapter@@UEAAKXZ+55
00000000728D1D9F  000000000276FF20  _endthreadex+43
00000000728D1E3B  000000000276FF50  _endthreadex+DF
000000007709652D  000000000276FF80  BaseThreadInitThunk+D
000000007753C521  000000000276FFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
000000007756165A  000000000286FD60  ZwDelayExecution+A
000007FEFDA61203  000000000286FE00  SleepEx+B3
000000014006EE26  000000000286FE50  ??0BarGoLink@@QEAA@_K@Z+9E6
000000014007052A  000000000286FE80  ??0BarGoLink@@QEAA@_K@Z+20EA
000000014006ECDF  000000000286FEB0  ??0BarGoLink@@QEAA@_K@Z+89F
000007FEF3740A95  000000000286FEF0  ?invoke@ACE_OS_Thread_Adapter@@UEAAKXZ+55
00000000728D1D9F  000000000286FF20  _endthreadex+43
00000000728D1E3B  000000000286FF50  _endthreadex+DF
000000007709652D  000000000286FF80  BaseThreadInitThunk+D
000000007753C521  000000000286FFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
0000000077562C1A  0000000004E8FC50  ZwWaitForWorkViaWorkerFactory+A
000000007752FE0B  0000000004E8FF50  RtlValidateHeap+3BB
000000007709652D  0000000004E8FF80  BaseThreadInitThunk+D
000000007753C521  0000000004E8FFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
0000000077562C1A  000000000922FC50  ZwWaitForWorkViaWorkerFactory+A
000000007752FE0B  000000000922FF50  RtlValidateHeap+3BB
000000007709652D  000000000922FF80  BaseThreadInitThunk+D
000000007753C521  000000000922FFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
000000007756165A  000000002D9BFD60  ZwDelayExecution+A
000007FEFDA61203  000000002D9BFE00  SleepEx+B3
000000014006EE26  000000002D9BFE50  ??0BarGoLink@@QEAA@_K@Z+9E6
000000014007052A  000000002D9BFE80  ??0BarGoLink@@QEAA@_K@Z+20EA
000000014006ECDF  000000002D9BFEB0  ??0BarGoLink@@QEAA@_K@Z+89F
000007FEF3740A95  000000002D9BFEF0  ?invoke@ACE_OS_Thread_Adapter@@UEAAKXZ+55
00000000728D1D9F  000000002D9BFF20  _endthreadex+43
00000000728D1E3B  000000002D9BFF50  _endthreadex+DF
000000007709652D  000000002D9BFF80  BaseThreadInitThunk+D
000000007753C521  000000002D9BFFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
0000000077561FEA  000000002DABCE70  NtGetContextThread+A
0000000077082F4A  000000002DABCEA0  GetThreadContext+A
000000014005C71E  000000002DABD3D0  ??4BarGoLink@@QEAAAEAV0@AEBV0@@Z+6EDE
000000014005CA27  000000002DABDA60  ??4BarGoLink@@QEAAAEAV0@AEBV0@@Z+71E7
000000014005CC3A  000000002DABDD00  ??4BarGoLink@@QEAAAEAV0@AEBV0@@Z+73FA
0000000077119490  000000002DABDDE0  UnhandledExceptionFilter+160
00000000775A43B8  000000002DABDE10  MD5Final+1DE8
00000000775285A8  000000002DABDE80  __C_specific_handler+9C
0000000077539D0D  000000002DABDEB0  RtlDecodePointer+BD
00000000775291AF  000000002DABE590  RtlUnwindEx+BBF
0000000077561278  000000002DABEB50  KiUserExceptionDispatcher+2E
000000002D63CADC  000000002DABEBA0  instance_draktharon_keep::GetSummonDummy+8C  c:\mangos\src\bindings\scriptdev2\scripts\northrend\draktharon_keep\instance_draktharon_keep.cpp line 211
000000002D63B003  000000002DABEC10  boss_novosAI::UpdateAI+363  c:\mangos\src\bindings\scriptdev2\scripts\northrend\draktharon_keep\boss_novos.cpp line 238
000000014015A675  000000002DABEC60  ?Update@Creature@@UEAAXII@Z+4E5
00000001400C1505  000000002DABECA0  ??0?$GridReference@V?$NGrid@$07VPlayer@@U?$TypeList@VPlayer@@U?$TypeList@VCreature@@U?$TypeList@VCorpse@@U?$TypeList@VCamera@@VTypeNull@@@@@@@@@@U?$TypeList@VGameObject@@U?$TypeList@VCreature@@U?$TypeList@VDynamicObject@@U?$TypeList@VCorpse@@VTypeNull@@@@@@@@@@@@@@QEAA@XZ+28A5
00000001400C5E45  000000002DABECD0  ?SetZoneWeather@Map@@QEAA_NIW4WeatherType@@M@Z+10C5
00000001400D8F89  000000002DABFDE0  ?Update@Map@@UEAAXAEBI@Z+3C9
00000001402D7BA0  000000002DABFE10  ?HandleReloadAllCommand@ChatHandler@@IEAA_NPEAD@Z+9FA0
00000001405626D9  000000002DABFE40  ?HandleWardenDataOpcode@WorldSession@@QEAAXAEAVWorldPacket@@@Z+BE09
000007FEF3769941  000000002DABFE70  ?svc_run@ACE_Task_Base@@SAKPEAX@Z+41
000007FEF3769EE5  000000002DABFEB0  ?invoke_i@ACE_Thread_Adapter@@EEAAKXZ+45
000007FEF376A011  000000002DABFEF0  ?invoke@ACE_Thread_Adapter@@UEAAKXZ+71
00000000728D1D9F  000000002DABFF20  _endthreadex+43
00000000728D1E3B  000000002DABFF50  _endthreadex+DF
000000007709652D  000000002DABFF80  BaseThreadInitThunk+D
000000007753C521  000000002DABFFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
000000007756135A  000000002DBBFCA0  NtWaitForSingleObject+A
000007FEFDA610AC  000000002DBBFD40  WaitForSingleObjectEx+9C
000007FEF373D04C  000000002DBBFD80  ?cond_wait@ACE_OS@@YAHPEAVACE_cond_t@@PEAU_RTL_CRITICAL_SECTION@@@Z+4C
00000001402D420D  000000002DBBFDD0  ?HandleReloadAllCommand@ChatHandler@@IEAA_NPEAD@Z+660D
00000001402D17FF  000000002DBBFE10  ?HandleReloadAllCommand@ChatHandler@@IEAA_NPEAD@Z+3BFF
0000000140095454  000000002DBBFE50  ??0CreatureEventAI@@QEAA@AEBV0@@Z+C1F4
000000014005B1A1  000000002DBBFE80  ??4BarGoLink@@QEAAAEAV0@AEBV0@@Z+5961
000000014006ECDF  000000002DBBFEB0  ??0BarGoLink@@QEAA@_K@Z+89F
000007FEF3740A95  000000002DBBFEF0  ?invoke@ACE_OS_Thread_Adapter@@UEAAKXZ+55
00000000728D1D9F  000000002DBBFF20  _endthreadex+43
00000000728D1E3B  000000002DBBFF50  _endthreadex+DF
000000007709652D  000000002DBBFF80  BaseThreadInitThunk+D
000000007753C521  000000002DBBFFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
000000007756153A  000000002DCBF8A0  NtRequestWaitReplyPort+A
00000000770A2F58  000000002DCBF8D0  GetConsoleMode+F8
00000000770D5321  000000002DCBFA20  VerifyConsoleIoHandle+281
00000000770EA762  000000002DCBFB00  ReadConsoleA+B2
00000000770B8E04  000000002DCBFB40  GetEnvironmentStringsA+55C4
000000007291C3F1  000000002DCBFBE0  _wsopen_s+261
000000007291C9B9  000000002DCBFC30  _read+C5
00000000728DD330  000000002DCBFC60  _filbuf+80
00000000728DC8F7  000000002DCBFCC0  fgets+11F
000000014004D1B8  000000002DCBFE80  ?HandleServerLogLevelCommand@ChatHandler@@IEAA_NPEAD@Z+138
000000014006ECDF  000000002DCBFEB0  ??0BarGoLink@@QEAA@_K@Z+89F
000007FEF3740A95  000000002DCBFEF0  ?invoke@ACE_OS_Thread_Adapter@@UEAAKXZ+55
00000000728D1D9F  000000002DCBFF20  _endthreadex+43
00000000728D1E3B  000000002DCBFF50  _endthreadex+DF
000000007709652D  000000002DCBFF80  BaseThreadInitThunk+D
000000007753C521  000000002DCBFFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
000000007756135A  000000002DDBF920  NtWaitForSingleObject+A
000007FEFD1E3D38  000000002DDBF9A0  0001:0000000000002D38 C:\Windows\system32\MSWSOCK.dll
000007FEFD1F1F96  000000002DDBFB40  WSPStartup+8E36
000007FEFEF94EFC  000000002DDBFB80  select+15C
000007FEFEF94E7D  000000002DDBFC80  select+DD
000007FEF36F7672  000000002DDBFD10  ?wait_for_multiple_events@?$ACE_Select_Reactor_T@V?$ACE_Reactor_Token_T@VACE_Token@@@@@@MEAAHAEAVACE_Select_Reactor_Handle_Set@@PEAVACE_Time_Value@@@Z+142
000007FEF3770B66  000000002DDBFDA0  ?handle_events@ACE_TP_Reactor@@UEAAHPEAVACE_Time_Value@@@Z+B6
000007FEF374EA6D  000000002DDBFDD0  ?run_reactor_event_loop@ACE_Reactor@@QEAAHAEAVACE_Time_Value@@P6AHPEAV1@@Z@Z+4D
000000014005818C  000000002DDBFE80  ??4BarGoLink@@QEAAAEAV0@AEBV0@@Z+294C
000000014006ECDF  000000002DDBFEB0  ??0BarGoLink@@QEAA@_K@Z+89F
000007FEF3740A95  000000002DDBFEF0  ?invoke@ACE_OS_Thread_Adapter@@UEAAKXZ+55
00000000728D1D9F  000000002DDBFF20  _endthreadex+43
00000000728D1E3B  000000002DDBFF50  _endthreadex+DF
000000007709652D  000000002DDBFF80  BaseThreadInitThunk+D
000000007753C521  000000002DDBFFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
000000007756165A  000000002DF7FD60  ZwDelayExecution+A
000007FEFDA61203  000000002DF7FE00  SleepEx+B3
000000014006EE26  000000002DF7FE50  ??0BarGoLink@@QEAA@_K@Z+9E6
0000000140057F67  000000002DF7FE80  ??4BarGoLink@@QEAAAEAV0@AEBV0@@Z+2727
000000014006ECDF  000000002DF7FEB0  ??0BarGoLink@@QEAA@_K@Z+89F
000007FEF3740A95  000000002DF7FEF0  ?invoke@ACE_OS_Thread_Adapter@@UEAAKXZ+55
00000000728D1D9F  000000002DF7FF20  _endthreadex+43
00000000728D1E3B  000000002DF7FF50  _endthreadex+DF
000000007709652D  000000002DF7FF80  BaseThreadInitThunk+D
000000007753C521  000000002DF7FFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
000000007756135A  000000002E07E910  NtWaitForSingleObject+A
000007FEFD1E3D38  000000002E07E990  0001:0000000000002D38 C:\Windows\system32\MSWSOCK.dll
000007FEFD1F1F96  000000002E07EB30  WSPStartup+8E36
000007FEFEF94EFC  000000002E07EB70  select+15C
000007FEFEF94E7D  000000002E07EC70  select+DD
000007FEF36F7672  000000002E07ED00  ?wait_for_multiple_events@?$ACE_Select_Reactor_T@V?$ACE_Reactor_Token_T@VACE_Token@@@@@@MEAAHAEAVACE_Select_Reactor_Handle_Set@@PEAVACE_Time_Value@@@Z+142
000007FEF3770B66  000000002E07ED90  ?handle_events@ACE_TP_Reactor@@UEAAHPEAVACE_Time_Value@@@Z+B6
000007FEF374EA6D  000000002E07EDC0  ?run_reactor_event_loop@ACE_Reactor@@QEAAHAEAVACE_Time_Value@@P6AHPEAV1@@Z@Z+4D
00000001402DC2F8  000000002E07FE40  ?HandleReloadAllCommand@ChatHandler@@IEAA_NPEAD@Z+E6F8
000007FEF3769941  000000002E07FE70  ?svc_run@ACE_Task_Base@@SAKPEAX@Z+41
000007FEF3769EE5  000000002E07FEB0  ?invoke_i@ACE_Thread_Adapter@@EEAAKXZ+45
000007FEF376A011  000000002E07FEF0  ?invoke@ACE_Thread_Adapter@@UEAAKXZ+71
00000000728D1D9F  000000002E07FF20  _endthreadex+43
00000000728D1E3B  000000002E07FF50  _endthreadex+DF
000000007709652D  000000002E07FF80  BaseThreadInitThunk+D
000000007753C521  000000002E07FFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
000000007756135A  000000002E17E910  NtWaitForSingleObject+A
000007FEFD1E3D38  000000002E17E990  0001:0000000000002D38 C:\Windows\system32\MSWSOCK.dll
000007FEFD1F1F96  000000002E17EB30  WSPStartup+8E36
000007FEFEF94EFC  000000002E17EB70  select+15C
000007FEFEF94E7D  000000002E17EC70  select+DD
000007FEF36F7672  000000002E17ED00  ?wait_for_multiple_events@?$ACE_Select_Reactor_T@V?$ACE_Reactor_Token_T@VACE_Token@@@@@@MEAAHAEAVACE_Select_Reactor_Handle_Set@@PEAVACE_Time_Value@@@Z+142
000007FEF3770B66  000000002E17ED90  ?handle_events@ACE_TP_Reactor@@UEAAHPEAVACE_Time_Value@@@Z+B6
000007FEF374EA6D  000000002E17EDC0  ?run_reactor_event_loop@ACE_Reactor@@QEAAHAEAVACE_Time_Value@@P6AHPEAV1@@Z@Z+4D
00000001402DC2F8  000000002E17FE40  ?HandleReloadAllCommand@ChatHandler@@IEAA_NPEAD@Z+E6F8
000007FEF3769941  000000002E17FE70  ?svc_run@ACE_Task_Base@@SAKPEAX@Z+41
000007FEF3769EE5  000000002E17FEB0  ?invoke_i@ACE_Thread_Adapter@@EEAAKXZ+45
000007FEF376A011  000000002E17FEF0  ?invoke@ACE_Thread_Adapter@@UEAAKXZ+71
00000000728D1D9F  000000002E17FF20  _endthreadex+43
00000000728D1E3B  000000002E17FF50  _endthreadex+DF
000000007709652D  000000002E17FF80  BaseThreadInitThunk+D
# 000000007753C521  000000002E17FFD0  RtlUserThreadStart+21

Local Variables And Parameters

Call stack:
Address   Frame     Function      SourceFile
000000002D63CADC  000000002DABEBA0  instance_draktharon_keep::GetSummonDummy+8C  c:\mangos\src\bindings\scriptdev2\scripts\northrend\draktharon_keep\instance_draktharon_keep.cpp line 211
    Local  <user defined> 'this' = 0

000000002D63B003  000000002DABEC10  boss_novosAI::UpdateAI+363  c:\mangos\src\bindings\scriptdev2\scripts\northrend\draktharon_keep\boss_novos.cpp line 238
    Local  <user defined> 'this' = 2DABED40
    Parameter  unsigned int 'uiDiff' = 120
    Local  float 'fZ' = 0.000000
    Local  float 'fY' = 0.000000
    Local  float 'fX' = 0.000000

000000014015A675  000000002DABEC60  ?Update@Creature@@UEAAXII@Z+4E5

00000001400C1505  000000002DABECA0  ??0?$GridReference@V?$NGrid@$07VPlayer@@U?$TypeList@VPlayer@@U?$TypeList@VCreature@@U?$TypeList@VCorpse@@U?$TypeList@VCamera@@VTypeNull@@@@@@@@@@U?$TypeList@VGameObject@@U?$TypeList@VCreature@@U?$TypeList@VDynamicObject@@U?$TypeList@VCorpse@@VTypeNull@@@@@@@@@@@@@@QEAA@XZ+28A5

00000001400C5E45  000000002DABECD0  ?SetZoneWeather@Map@@QEAA_NIW4WeatherType@@M@Z+10C5

00000001400D8F89  000000002DABFDE0  ?Update@Map@@UEAAXAEBI@Z+3C9

00000001402D7BA0  000000002DABFE10  ?HandleReloadAllCommand@ChatHandler@@IEAA_NPEAD@Z+9FA0

00000001405626D9  000000002DABFE40  ?HandleWardenDataOpcode@WorldSession@@QEAAXAEAVWorldPacket@@@Z+BE09

000007FEF3769941  000000002DABFE70  ?svc_run@ACE_Task_Base@@SAKPEAX@Z+41

000007FEF3769EE5  000000002DABFEB0  ?invoke_i@ACE_Thread_Adapter@@EEAAKXZ+45

000007FEF376A011  000000002DABFEF0  ?invoke@ACE_Thread_Adapter@@UEAAKXZ+71

00000000728D1D9F  000000002DABFF20  _endthreadex+43

00000000728D1E3B  000000002DABFF50  _endthreadex+DF

000000007709652D  000000002DABFF80  BaseThreadInitThunk+D

000000007753C521  000000002DABFFD0  RtlUserThreadStart+21
# 

Global Variables
     <user defined> 'm_afAmbushSpawn'
     <user defined> 'm_afAmbushSpawn'
     int '_fltused' = 9875
     <user defined> 'TriggerOrphanSpell'
     <user defined> 'RitualChannelerPos'
     <user defined> 'aVolcorSpawnLocs'
     float 'PosVoiceIcecrown'
     <user defined> 'RandomTaunt'
     <user defined> 'HighborneLoc'
     <user defined> 'afSpawnLocations'
     float 'PosVoiceDragon'
     float 'HEIGHT_FENRUS_ROOM' = 140.000000
     unsigned int 'possibleSpawns'
     unsigned int '__security_cookie_complement' = FFFFD288C249868D
     <user defined> 'aOutroLocations'
     char\* 'multiszStringVal' = 2D76B9B0
     char\* 'multiszStringVal' = 2D76B9B0
     unsigned int 'aGandlingEvents'
     int '__proc_attached' = 1
     unsigned int 'm_auiSpellSummonWeapon'
     unsigned int 'aPossibleBreaths'
     <user defined> 'OrbLoc'
     char\* 'out'
     float 'EVENT_AREA_RADIUS' = 65.000000
     <user defined> 'aSpiritSpawns'
     unsigned int 'aCouncilMember'
     unsigned int 'aCouncilMember'
     <user defined> 'm_aShad'
     <user defined> 'aShadowsLocations'
     char\* 'szDwordVal' = 2D76B9AC
     char\* 'szDwordVal' = 2D76B9AC
     <user defined> 'aHakkariDoorLocations'
     float 'Last5Z' = 0.000000
     <user defined> 'FireWallCoords'
     float 'ENKILAH_NECROLORD_SPAWN_COORDINATES'
     <user defined> '__rtc_taa' = 0
     float 'afSporebatPos'
     <user defined> 'aEventBeginLocations'
     <user defined> 'aRAJDialogue'
     <user defined> 'SummonLocations'
     float 'afCenter'
     float 'm_afToWaterLoc'
     unsigned int 'aArenaNPCs'
     <user defined> 'DragonLoc'
     float 'afKaelLandPoint'

**Comment by rsa** [comment]
seems fixed.
