### ISSUE TITLE
compile

### ISSUE THREAD

**Issue by metacreo** [mangosR2/scriptdev2#133]
[  6%] Building CXX object src/bindings/ScriptDev2/CMakeFiles/mangosscriptR2.dir/scripts/northrend/naxxramas/instance_naxxramas.cpp.o
/mangos/src/bindings/ScriptDev2/scripts/northrend/naxxramas/instance_naxxramas.cpp: In member function 'virtual void instance_naxxramas::Initialize()':
/mangos/src/bindings/ScriptDev2/scripts/northrend/naxxramas/instance_naxxramas.cpp:65: error: 'm_uiHorsemenDead' was not declared in this scope
**\* Error code 1

Stop in /mangos/build.
**\* Error code 1

Stop in /mangos/build.
**\* Error code 1

Stop in /mangos/build.

**Comment by Sar777** [comment]
in [sd2_mr0429]
