### ISSUE TITLE
Crash in blackfathom deeps

### ISSUE THREAD

**Issue by Undergarun** [mangosR2/scriptdev2#137]
http://pastebin.com/k84PbrQ9
http://pastebin.com/RcT4bk7p

**Comment by rsa** [comment]
I even theoretically can not imagine why these beautiful ... crushes in destructor - science fiction.

**Comment by Undergarun** [comment]
http://pastebin.com/AZS6gVUn
http://pastebin.com/W8yf0bEN

**Comment by rsa** [comment]
crazy 8-\

**Comment by Undergarun** [comment]
Other type: http://pastebin.com/ZzPEd6T9

**Comment by Undergarun** [comment]
http://pastebin.com/7m5jwe13

**Comment by Undergarun** [comment]
Use to happen at instance resets:

http://pastebin.com/gedmrEXJ

**Comment by Undergarun** [comment]
Now has freezes related to LockedVector http://pastebin.com/8XKYEGRZ

**Comment by Undergarun** [comment]
http://pastebin.com/saEHraR9

**Comment by Undergarun** [comment]
http://pastebin.com/gvLJdrdz

**Comment by Undergarun** [comment]
http://pastebin.com/tS2fFCk0

@rsa Can you take a look into it?

**Comment by Undergarun** [comment]
No more crashes for now...
