### ISSUE TITLE
Crash in ruins of Ahn'Quiraj

### ISSUE THREAD

**Issue by Undergarun** [mangosR2/scriptdev2#138]
http://pastebin.com/07UjxzAN

**Comment by rsa** [comment]
nothing strange - itr = {_M_node = 0x7fca00000000}
one guid removed from storage in another thread. need rework like all similate...

**Comment by Undergarun** [comment]
Looks like fixed, thank you.

**Comment by Undergarun** [comment]
:( http://pastebin.com/Tuhy41Ba

**Comment by Undergarun** [comment]
Still exists:
http://pastebin.com/2Ji2hDTj

**Comment by Undergarun** [comment]
http://pastebin.com/whVE6jDK
http://pastebin.com/cdmmCkjn

**Comment by Undergarun** [comment]
http://pastebin.com/BvSpTRfb
http://pastebin.com/xudpHTSj
http://pastebin.com/B0br4bxj

**Comment by Undergarun** [comment]
http://pastebin.com/JDR2xUhE

**Comment by Undergarun** [comment]
http://pastebin.com/CQQixsVG

**Comment by Undergarun** [comment]
Seems fixed, Thank you.
