### ISSUE TITLE
Trial of the Crusader

### ISSUE THREAD

**Issue by ghost** [mangosR2/scriptdev2#141]
Some Time Instance start and some time not starting

**Comment by Sar777** [comment]
I do not understand.

**Comment by raynar** [comment]
That's a core problem. I have a hack to fix that but rsa is working to fix properly.

**Comment by carlos93** [comment]
I think it's problem related with mmaps.Probably sometimes tirion appears bugged and doesn't start the event.

**Comment by rsa** [comment]
works good.
