### ISSUE TITLE
need possible revert

### ISSUE THREAD

**Issue by softbest** [mangosR2/scriptdev2#143]
Hi

I think that https://github.com/mangosR2/scriptdev2/commit/b6a0ee5059dd9213cd4d101f01962dfa3b340711 need a revert. I think that isn't neccesary and it do problem in windows and R2 not use branch 400

**Comment by michalpolko** [comment]
Yes, this causes linking problems in vc90 project, I've been trying to find the way to fix this but I guess I'm not good at it ;D Including DBCStructure.h doesn't solve this. Disabling pch extends build time for too long, I didnt even check this.
Any ideas anybody?

**Comment by Zakamurite** [comment]
https://github.com/mangos-three/server/commit/c800505246530f0b0f220fc1dbc85754fd3ceff3
?

**Comment by michalpolko** [comment]
This doesn't help :<

**Comment by softbest** [comment]
I think the best solution is revert commit because only it's  for Mangos 400

**Comment by Reamer** [comment]
@softbest 
That's no real solution, better fix linking problems.
I think this wrapper functions are good, we can work with more enum

**Comment by rsa** [comment]
10 min ago compiled (over cmake+VC2012RC). no problem with linking... commit needed for future use. may remove in own branches.

**Comment by michalpolko** [comment]
What Zakamurite linked didnt help, but this way https://github.com/mangosR2/mangos/commit/04c528993d58ab458e920115a511dbb78b24485d helped ;] maybe in mangos-three code is written in other order.

**Comment by rsa** [comment]
as i think, your try make with PCH :)
