### ISSUE TITLE
Trial Of the Champion Argent Confessor Paletress

### ISSUE THREAD

**Issue by KiriX** [mangosR2/scriptdev2#144]
Argent Confessor Paletress don't remove Shield aura after summons die... But should...

https://gist.github.com/3509064

Not tested yet...

**Comment by KiriX** [comment]
Tested. Work fine! =)

**Comment by Undergarun** [comment]
Push it!

**Comment by KiriX** [comment]
я так не люблю пушить... =(

**Comment by Undergarun** [comment]
Don't understand russian T.T

**Comment by Lillecarl** [comment]
He said i do not like to push (http://translate.google.com)

**Comment by KiriX** [comment]
Ну как хотели, сам запушил тогда =)
https://github.com/mangosR2/scriptdev2/commit/f4fc4fdf8714185ae2dca20a5e70ed149ca47060

**Comment by rsa** [comment]
- я так не люблю кошек...
- вы просто не умеете их готовить!

**Comment by KiriX** [comment]
Да, именно поэтому не хочу пушить - вдруг где косякну =)
