### ISSUE TITLE
[ICC] Crash in blood prince council

### ISSUE THREAD

**Issue by Undergarun** [mangosR2/scriptdev2#154]
http://pastebin.com/KqWvSb2C

**Comment by rsa** [comment]
not see any unsafe in dump/script. all good. frequency?

**Comment by Undergarun** [comment]
Only happens once for now.

**Comment by Venom** [comment]
i have question:

why players get combat when they enter the icecrown citadel.  looks like some kind a script summoning all trash mobs. .

players ask me about this a lot. and didnt find the answer or source of it.

**Comment by Undergarun** [comment]
Not happens anymore. So closed!
