### ISSUE TITLE
Битва за Гору Хиджал.

### ISSUE THREAD

**Issue by ghost** [mangosR2/scriptdev2#157]
http://ru.wowhead.com/zone=3606.
Суть в том,что все боссы(кроме Архимонда) и треш заскриптованы на EventAI.Это конечно неплохо реализовано,но через 3-4 минуты они просто исчезают(despawn) и эвент запустить повторно уже нельзя.Ситуация одинаковая,что в чистом СкриптДеве,что в СкриптДеве МангосR2.Список боссов и нпс.
    //bosses
   NPC_WINTERCHILL             = 17767,
    NPC_ANETHERON               = 17808,
    NPC_KAZROGAL                = 17888,
    NPC_AZGALOR                 = 17842,
   // Trash Mobs summoned in waves
    NPC_NECRO                   = 17899,
    NPC_ABOMI                   = 17898,
    NPC_GHOUL                   = 17895,
    NPC_BANSH                   = 17905,
    NPC_CRYPT                   = 17897,
    NPC_GARGO                   = 17906,
    NPC_FROST                   = 17907,
    NPC_GIANT                   = 17908,
    NPC_STALK                   = 17916,
Также на базе Тралла треш спавнится в одной стороне,а должны в 2-х(некритично в принципе).Такая ситуация существует года 2 точно уже. 
The bottom line is that all the bosses (except Archimonde) and scripted by trash EventAI. It certainly is nice to implement, but after 3-4 minutes they just fade away (despawn) Event and restart the anymore. Situation is the same, that in pure ScriptDev2, that ScriptDev2 MangosR2. List of bosses and NPCs.

**Comment by rsa** [comment]
Не лечится. После того как пара (умных людей) переписали скрипт на EAI он стал почти мертвым, я об этом еще 2 года назад жалился. Надо писать заново. Займетесь?

**Comment by ghost** [comment]
Умел бы я это делать,давно бы с Орегона перегнал бы под Мангос(там вполне проходимо).
Чтобы не захламлять лишний раз трекер,хочу спросить:Вы планируете добавлять изменение скрипта Кил'джедена в Плато Солнечного Колодца?
Вот этот скрипт https://github.com/xfurry/ScriptDev2_2010/blob/master/scripts/eastern_kingdoms/sunwell_plateau/boss_kiljaeden.cpp
Или вот этот https://github.com/scriptdev2/scriptdev2-tbc/blob/master/scripts/eastern_kingdoms/sunwell_plateau/boss_kiljaeden.cpp
Вы просто сами говорили,чтобы по всем баг-репортам составляли иссуи на Гитхабе.Спасибо вам,за вашу работу.Реально спасибо.

**Comment by rsa** [comment]
А в чем проблема с килжаденом? у нас вполне современный скрипт, выглядит гораздо более прилично чем старинная (аж 2010) версия xfurry. насколько я понимаю, он и сам ту старую давно забросил.

**Comment by ghost** [comment]
Орбы работают,вот с драконами неполадка(неработают спелы(45856,45860),ну и отражений нет(вы говорили,что нужна сценарная логика).

**Comment by ghost** [comment]
if (pSpawn)
        m_creature->SummonCreature(uiMobEntry, pSpawn->m_fX, pSpawn->m_fY, pSpawn->m_fZ, 0.0f, TEMPSUMMON_TIMED_OOC_OR_DEAD_DESPAWN, 120000);
}
Темпорари суммоны работали не так как надо, вот и деспавнились боссы и мобы поэтому. Я про то, что они в бою уходили в деспавн.
