### ISSUE TITLE
assert fail

### ISSUE THREAD

**Issue by Exxenoz** [mangosR2/scriptdev2#16]
When I fighted against Flame Leviatan in a Ulduar Vehicle I killed him with .die and the application crashed.
The problem part is in Unit.cpp line 6084, at this point the m_currmap pointer was NULL because ResetMap() was called before and the assert in GetMap() forced the app to crash. Is the GetMap() check there really needed? Maybe the problem is caused by other code parts, I have no idea.
Have a look:

//=====================================================
Exception code: 80000003 BREAKPOINT
Fault address:  5C82C355 01:0003B355 C:\Windows\WinSxS\x86_microsoft.vc90.debugcrt_1fc8b3b9a1e18e3b_9.0.30729.1_none_bb1f6aa1308c35eb\MSVCR90D.dll

Registers:
EAX:00000001
EBX:0D246A98
ECX:19AD554E
EDX:0000007B
ESI:0E9BDBE8
EDI:0E9BEC04
CS:EIP:001B:5C82C355
SS:ESP:0023:0E9BCDC8  EBP:0E9BCDE0
DS:0023  ES:0023  FS:003B  GS:0000
Flags:00000246

Call stack:
Address   Frame     Function      SourceFile
5C82C355  00000000  _get_pgmptr+1C5
5C8CE9AD  00000000  abort+2D
5C8BE8D6  00000000  _wassert+D6
00A314EB  00000000  WorldObject::GetMap+BB  d:\server source\insanitycore rsa\src\game\object.h line 584
00BA2EE2  00000000  Unit::RemoveAllAttackers+42  d:\server source\insanitycore rsa\src\game\unit.cpp line 6084
00BA2D69  00000000  Unit::CombatStop+49  d:\server source\insanitycore rsa\src\game\unit.cpp line 6044
00BB1369  00000000  Unit::CleanupsBeforeDelete+69  d:\server source\insanitycore rsa\src\game\unit.cpp line 10013
00BE9242  00000000  Creature::~Creature+52  d:\server source\insanitycore rsa\src\game\creature.cpp line 180
0103412F  00000000  TemporarySummon::~TemporarySummon+1F  d:\server source\insanitycore rsa\src\game\temporarysummon.h line 29
010340E6  00000000  TemporarySummon::`scalar deleting destructor'+16
00B6E84F  00000000  Map::Remove<Creature>+2EF  d:\server source\insanitycore rsa\src\game\map.cpp line 658
00B57404  00000000  Map::RemoveAllObjectsInRemoveList+1B4  d:\server source\insanitycore rsa\src\game\map.cpp line 1019
00FD2CB7  00000000  MapManager::RemoveAllObjectsInRemoveList+B7  d:\server source\insanitycore rsa\src\game\mapmanager.cpp line 278
00EBE8D1  00000000  World::Update+571  d:\server source\insanitycore rsa\src\game\world.cpp line 1648
00B1D789  00000000  WorldRunnable::run+89  d:\server source\insanitycore rsa\src\mangosd\worldrunnable.cpp line 61
014CDD01  00000000  ACE_Based::Thread::ThreadTask+21  d:\server source\insanitycore rsa\src\shared\threading.cpp line 187
66D4FA75  00000000  ACE_OS_Thread_Adapter::invoke+E5  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\os_thread_adapter.cpp line 86
66CCAEBA  00000000  ace_thread_adapter+2A  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\base_thread_adapter.cpp line 120
5C82DFD3  00000000  _beginthreadex+243
5C82DF69  00000000  _beginthreadex+1D9
76861174  00000000  BaseThreadInitThunk+12
7729B3F5  00000000  RtlInitializeExceptionChain+63
7729B3C8  00000000  RtlInitializeExceptionChain+36

Call stack:
Address   Frame     Function      SourceFile
772864F4  00000000  KiFastSystemCallRet+0
7685F003  00000000  WaitForSingleObjectEx+43
7685EFB2  00000000  WaitForSingleObject+12
66D452C9  00000000  ACE_OS::thr_join+39  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\os_ns_thread.inl line 2798
66D9C7C0  00000000  ACE_Thread::join+10  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\thread.inl line 137
66DA2E3E  00000000  ACE_Thread_Manager::wait_task+2DE  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\thread_manager.cpp line 1793
66D9BFBD  00000000  ACE_Task_Base::wait+2D  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\task.cpp line 86
00F24F1A  00000000  ReactorRunnable::Wait+1A  d:\server source\insanitycore rsa\src\game\worldsocketmgr.cpp line 101
00F25A31  00000000  WorldSocketMgr::Wait+51  d:\server source\insanitycore rsa\src\game\worldsocketmgr.cpp line 310
00AE44D1  00000000  Master::Run+811  d:\server source\insanitycore rsa\src\mangosd\master.cpp line 325
00AE28C9  00000000  main+599  d:\server source\insanitycore rsa\src\mangosd\main.cpp line 212
00B1E798  00000000  __tmainCRTStartup+1A8  f:\dd\vctools\crt_bld\self_x86\crt\src\crtexe.c line 586
00B1E5DF  00000000  mainCRTStartup+F  f:\dd\vctools\crt_bld\self_x86\crt\src\crtexe.c line 403
76861174  00000000  BaseThreadInitThunk+12
7729B3F5  00000000  RtlInitializeExceptionChain+63
7729B3C8  00000000  RtlInitializeExceptionChain+36

Call stack:
Address   Frame     Function      SourceFile
772864F4  00000000  KiFastSystemCallRet+0
76861174  00000000  BaseThreadInitThunk+12
7729B3F5  00000000  RtlInitializeExceptionChain+63
7729B3C8  00000000  RtlInitializeExceptionChain+36

Call stack:
Address   Frame     Function      SourceFile
772864F4  00000000  KiFastSystemCallRet+0
75441818  00000000  Sleep+F
66D4D0E5  00000000  ACE_OS::sleep+15  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\os_ns_unistd.inl line 946
014CE137  00000000  ACE_Based::Thread::Sleep+47  d:\server source\insanitycore rsa\src\shared\threading.cpp line 237
014D9CC9  00000000  SqlDelayThread::run+59  d:\server source\insanitycore rsa\src\shared\database\sqldelaythread.cpp line 48
014CDD01  00000000  ACE_Based::Thread::ThreadTask+21  d:\server source\insanitycore rsa\src\shared\threading.cpp line 187
66D4FA75  00000000  ACE_OS_Thread_Adapter::invoke+E5  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\os_thread_adapter.cpp line 86
66CCAEBA  00000000  ace_thread_adapter+2A  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\base_thread_adapter.cpp line 120
5C82DFD3  00000000  _beginthreadex+243
5C82DF69  00000000  _beginthreadex+1D9
76861174  00000000  BaseThreadInitThunk+12
7729B3F5  00000000  RtlInitializeExceptionChain+63
7729B3C8  00000000  RtlInitializeExceptionChain+36

Call stack:
Address   Frame     Function      SourceFile
772864F4  00000000  KiFastSystemCallRet+0
75441818  00000000  Sleep+F
66D4D0E5  00000000  ACE_OS::sleep+15  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\os_ns_unistd.inl line 946
014CE137  00000000  ACE_Based::Thread::Sleep+47  d:\server source\insanitycore rsa\src\shared\threading.cpp line 237
014D9CC9  00000000  SqlDelayThread::run+59  d:\server source\insanitycore rsa\src\shared\database\sqldelaythread.cpp line 48
014CDD01  00000000  ACE_Based::Thread::ThreadTask+21  d:\server source\insanitycore rsa\src\shared\threading.cpp line 187
66D4FA75  00000000  ACE_OS_Thread_Adapter::invoke+E5  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\os_thread_adapter.cpp line 86
66CCAEBA  00000000  ace_thread_adapter+2A  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\base_thread_adapter.cpp line 120
5C82DFD3  00000000  _beginthreadex+243
5C82DF69  00000000  _beginthreadex+1D9
76861174  00000000  BaseThreadInitThunk+12
7729B3F5  00000000  RtlInitializeExceptionChain+63
7729B3C8  00000000  RtlInitializeExceptionChain+36

Call stack:
Address   Frame     Function      SourceFile
772864F4  00000000  KiFastSystemCallRet+0
75441818  00000000  Sleep+F
66D4D0E5  00000000  ACE_OS::sleep+15  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\os_ns_unistd.inl line 946
014CE137  00000000  ACE_Based::Thread::Sleep+47  d:\server source\insanitycore rsa\src\shared\threading.cpp line 237
014D9CC9  00000000  SqlDelayThread::run+59  d:\server source\insanitycore rsa\src\shared\database\sqldelaythread.cpp line 48
014CDD01  00000000  ACE_Based::Thread::ThreadTask+21  d:\server source\insanitycore rsa\src\shared\threading.cpp line 187
66D4FA75  00000000  ACE_OS_Thread_Adapter::invoke+E5  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\os_thread_adapter.cpp line 86
66CCAEBA  00000000  ace_thread_adapter+2A  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\base_thread_adapter.cpp line 120
5C82DFD3  00000000  _beginthreadex+243
5C82DF69  00000000  _beginthreadex+1D9
76861174  00000000  BaseThreadInitThunk+12
7729B3F5  00000000  RtlInitializeExceptionChain+63
7729B3C8  00000000  RtlInitializeExceptionChain+36

Call stack:
Address   Frame     Function      SourceFile
772864F4  00000000  KiFastSystemCallRet+0
75441818  00000000  Sleep+F
66D4D0E5  00000000  ACE_OS::sleep+15  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\os_ns_unistd.inl line 946
014CE137  00000000  ACE_Based::Thread::Sleep+47  d:\server source\insanitycore rsa\src\shared\threading.cpp line 237
014D9CC9  00000000  SqlDelayThread::run+59  d:\server source\insanitycore rsa\src\shared\database\sqldelaythread.cpp line 48
014CDD01  00000000  ACE_Based::Thread::ThreadTask+21  d:\server source\insanitycore rsa\src\shared\threading.cpp line 187
66D4FA75  00000000  ACE_OS_Thread_Adapter::invoke+E5  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\os_thread_adapter.cpp line 86
66CCAEBA  00000000  ace_thread_adapter+2A  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\base_thread_adapter.cpp line 120
5C82DFD3  00000000  _beginthreadex+243
5C82DF69  00000000  _beginthreadex+1D9
76861174  00000000  BaseThreadInitThunk+12
7729B3F5  00000000  RtlInitializeExceptionChain+63
7729B3C8  00000000  RtlInitializeExceptionChain+36

Call stack:
Address   Frame     Function      SourceFile
772864F4  00000000  KiFastSystemCallRet+0
7685F003  00000000  WaitForSingleObjectEx+43
7685EFB2  00000000  WaitForSingleObject+12
66D48632  00000000  ACE_OS::cond_wait+92  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\os_ns_thread.cpp line 1764
66D4836A  00000000  ACE_OS::cond_timedwait+2A  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\os_ns_thread.cpp line 1620
66CDB03F  00000000  ACE_Condition_Thread_Mutex::wait+1F  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\condition_thread_mutex.cpp line 100
66CDB081  00000000  ACE_Condition_Thread_Mutex::wait+21  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\condition_thread_mutex.cpp line 108
66CAF36E  00000000  ACE_Message_Queue<ACE_MT_SYNCH>::wait_not_empty_cond+4E  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\message_queue_t.cpp line 1744
66CAD33D  00000000  ACE_Message_Queue<ACE_MT_SYNCH>::dequeue_head+DD  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\message_queue_t.cpp line 1936
66CAC1D2  00000000  ACE_Activation_Queue::dequeue+42  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\activation_queue.cpp line 89
014D9113  00000000  DelayExecutor::svc+53  d:\server source\insanitycore rsa\src\shared\delayexecutor.cpp line 65
66D9C5A7  00000000  ACE_Task_Base::svc_run+47  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\task.cpp line 271
66D9D16D  00000000  ACE_Thread_Adapter::invoke_i+DD  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\thread_adapter.cpp line 145
66D9D021  00000000  ACE_Thread_Adapter::invoke+D1  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\thread_adapter.cpp line 94
66CCAEBA  00000000  ace_thread_adapter+2A  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\base_thread_adapter.cpp line 120
5C82DFD3  00000000  _beginthreadex+243
5C82DF69  00000000  _beginthreadex+1D9
76861174  00000000  BaseThreadInitThunk+12
7729B3F5  00000000  RtlInitializeExceptionChain+63
7729B3C8  00000000  RtlInitializeExceptionChain+36

Call stack:
Address   Frame     Function      SourceFile
772864F4  00000000  KiFastSystemCallRet+0
7685F003  00000000  WaitForSingleObjectEx+43
7685EFB2  00000000  WaitForSingleObject+12
66D48632  00000000  ACE_OS::cond_wait+92  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\os_ns_thread.cpp line 1764
66D4836A  00000000  ACE_OS::cond_timedwait+2A  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\os_ns_thread.cpp line 1620
66CDB03F  00000000  ACE_Condition_Thread_Mutex::wait+1F  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\condition_thread_mutex.cpp line 100
66CDB081  00000000  ACE_Condition_Thread_Mutex::wait+21  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\condition_thread_mutex.cpp line 108
66CAF36E  00000000  ACE_Message_Queue<ACE_MT_SYNCH>::wait_not_empty_cond+4E  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\message_queue_t.cpp line 1744
66CAD33D  00000000  ACE_Message_Queue<ACE_MT_SYNCH>::dequeue_head+DD  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\message_queue_t.cpp line 1936
66CAC1D2  00000000  ACE_Activation_Queue::dequeue+42  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\activation_queue.cpp line 89
014D9113  00000000  DelayExecutor::svc+53  d:\server source\insanitycore rsa\src\shared\delayexecutor.cpp line 65
66D9C5A7  00000000  ACE_Task_Base::svc_run+47  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\task.cpp line 271
66D9D16D  00000000  ACE_Thread_Adapter::invoke_i+DD  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\thread_adapter.cpp line 145
66D9D021  00000000  ACE_Thread_Adapter::invoke+D1  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\thread_adapter.cpp line 94
66CCAEBA  00000000  ace_thread_adapter+2A  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\base_thread_adapter.cpp line 120
5C82DFD3  00000000  _beginthreadex+243
5C82DF69  00000000  _beginthreadex+1D9
76861174  00000000  BaseThreadInitThunk+12
7729B3F5  00000000  RtlInitializeExceptionChain+63
7729B3C8  00000000  RtlInitializeExceptionChain+36

Call stack:
Address   Frame     Function      SourceFile
772864F4  00000000  KiFastSystemCallRet+0
0E9BBF94  00000000  0000:00000000 
00B1B6D9  00000000  WheatyExceptionReport::printTracesForAllThreads+109  d:\server source\insanitycore rsa\src\shared\wheatyexceptionreport.cpp line 368
7729B3C8  00000000  RtlInitializeExceptionChain+36

Call stack:
Address   Frame     Function      SourceFile
772864F4  00000000  KiFastSystemCallRet+0
76874AB7  00000000  ReadConsoleW+175
768BBF10  00000000  ReadConsoleA+40
7687B2C7  00000000  SetThreadExecutionState+18E2
5C8B207C  00000000  _read+8CC
5C8B19C9  00000000  _read+219
5C843E43  00000000  _filbuf+113
5C84277D  00000000  fgets+30D
00A5046B  00000000  CliRunnable::run+FB  d:\server source\insanitycore rsa\src\mangosd\clirunnable.cpp line 621
014CDD01  00000000  ACE_Based::Thread::ThreadTask+21  d:\server source\insanitycore rsa\src\shared\threading.cpp line 187
66D4FA75  00000000  ACE_OS_Thread_Adapter::invoke+E5  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\os_thread_adapter.cpp line 86
66CCAEBA  00000000  ace_thread_adapter+2A  d:\server source\insanitycore rsa\dep\ace_wrappers\ace\base_thread_adapter.cpp line 120
5C82DFD3  00000000  _beginthreadex+243
5C82DF69  00000000  _beginthreadex+1D9
76861174  00000000  BaseThreadInitThunk+12
7729B3F5  00000000  RtlInitializeExceptionChain+63
7729B3C8  00000000  RtlInitializeExceptionChain+36

Call stack:
Address   Frame     Function      SourceFile
772864F4  00000000  KiFastSystemCallRet+0
74DC678C  00000000  0001:0000578C C:\Windows\system32\MSWSOCK.dll
77434A20  00000000  select+9F
8B082444  FFFFFFFF  0000:00000000 
0B10244C  00000000  0000:00000000 
244C8BC8  00000000

**Comment by Exxenoz** [comment]
MaNGOS r11767 rsa commit f602ace9fc79050f9ebe4447df2dc2f01856ad1d 
ScriptDev2 r2257 rsa commit 9db973cf1c61a900d838390fc51c4c04044f7ae5 (mr113)
btw, what does the "mr" mean?

**Comment by michalpolko** [comment]
m - mangos
r - r2

mangosR2
?

**Comment by ghost** [comment]
this is a core issue and they are currently trying to fix there is actually nothing wrong with the script as in working terms  im sure isse will be resolved soon
