### ISSUE TITLE
Great Bear spirit quest

### ISSUE THREAD

**Issue by Venom** [mangosR2/scriptdev2#160]
http://www.wowhead.com/quest=5929
http://www.wowhead.com/quest=5930

Unable to complete quest . You just talk to bear and that's all not able to complete it.
same problem with gossip_menu condition  quests.  unable to complete.

I rechecked if I was wrong with something.

Mangos  12270  R2 rev 2444   -   Same Database Ytdb 631  -  Quest Working!!!!!!

Mangos  12287  R2 rev 2481   -    Same Database Ytdb 631  - Quest not working!!!

Rechecked twice - no DB problem!

**Comment by Venom** [comment]
theres somthing wrong. i rechecked like 100 times. have 2 copyed ytdb 631 databases.   one DB updated to mangos 12287 R2 rev 2481. at this point quest stoped working. 

second DB didnt update any core any sqls but quest is still working great,    

gossip_script, +  dbscripts_on_gossip,  
condition, gossip_menu_option, gossip_menu,

all this sql dbs are same old ones and new ones didnt changed a bit. didnt have any problems. 
but old core works and new mangosR2 core dosnt work for this quests.

**Comment by rsa** [comment]
awaiting @Schmoozerd ralations.

**Comment by Venom** [comment]
there s a quest in this chain called
http://www.wowhead.com/quest=6001
http://www.wowhead.com/quest=6002

same problem gossip menu missing for this quests in the game. but in database it exists :| unable to complate next quest for bear form.   looks like all gossip quest complates damaged in this core. :|  unable to see any option that is complating the quest. this is realy F*cked up.

**Comment by rsa** [comment]
6001 && 6002 checked, work fine. please, test on R2 test server before publish.

**Comment by rsa** [comment]
quest 5929 also checked, works fine (current mangosR2 + current YTDB, mangosR2 test server).
ergo - not confirm, closed.
