### ISSUE TITLE
Pit of Saron

### ISSUE THREAD

**Issue by TheTumultuousUnicornOfDarkness** [mangosR2/scriptdev2#161]
Hi.

I sent a mail to RSA but I haven't receive answer.

I've found some errors in instance Pit of Saron, in 'src/bindings/ScriptDev2/scripts/northrend/icecrown_citadel/frozen_halls/pit_of_saron'.

I've written these patches :
- The first for the file boss_forgemaster_garfrost.cpp : http://textup.fr/35259le
- The second for the file boss_scourgelord_tyrannus.cpp : http://textup.fr/35258Gt

Thanks.

Cheers,

Xorg.

**Comment by rsa** [comment]
thx for patches, if anybody be work on this instances - be implemented.
next time send your changes over pull-request. also, please, for code editing not use tabs in VC - formatting broken fully (seen in second patch).

**Comment by TheTumultuousUnicornOfDarkness** [comment]
Ok. I'm sorry, I'm new.
