### ISSUE TITLE
Stratholme.

### ISSUE THREAD

**Issue by ghost** [mangosR2/scriptdev2#163]
Hello There was a problem, in the instance Stratholme.
That is on the square knackery.
After killing all the NPC, namely
NPC_ABOM_BILE = 10416,
NPC_ABOM_VENOM = 10,417,
Does not open the door to the Ziggurat of Baron Rivendare. And out of it comes out
NPC_RAMSTEIN = 10439,
Therefore can not be extended Event.
Tested on the test server MangosR2.
Перевод на русский язык:
Здравствуйте. Появилась проблема, в инстансе Стратхольм.
А именно на площади Живодерни.
После убийства всех нпц,а именно  
NPC_ABOM_BILE               = 10416,
NPC_ABOM_VENOM              = 10417,
Не открывается дверь в Зиккурат барона Ривендера. И из нее не выходит
NPC_RAMSTEIN                = 10439,
Следовательно нельзя продолжить эвент.
Тестировал на тестовом сервере МангосR2
Номер объекта GO_ZIGGURAT_DOOR_4          = 175405,

**Comment by rsa** [comment]
иссуй уже пару раз был и оба раза выяснялось что там какие-то еще условия есть.

**Comment by ghost** [comment]
Зачистить Зиккураты и убить Тузадинских послушников(это я сделал),нужно убить всех поганищ на этой площади,вылезет Рамштайн.Но я для верности вычистил всех мобов и боссов,эффект тот же.

**Comment by rsa** [comment]
по коду все в порядке, абоминации есть 2х типов и зачистить их надо не на площади а вообще во всей инсте. после выполнения эвентов всех 3 боссов и гибели крайней абоминации откроется дверь рамштайна.

**Comment by ghost** [comment]
Ну не знаю,я всех грохнул,но результата ноль,может какая абоминация в текстурах сидит?Я понимаю,что mmaps стоят,но такое тоже возможно,даже на оффе порой такое видел.Раньше все в порядке было.
