### ISSUE TITLE
ICC - Lord Marrowgar

### ISSUE THREAD

**Issue by Undergarun** [mangosR2/scriptdev2#167]
1. Coldflame some times don't damage players.

**Comment by michalpolko** [comment]
Not sure, but I think it is a general problem - nothing "coldflame-only" - related to persistent aoe auras. Problem doesn't seem to appear if there is only 1 coldflame (but this is just a theory, need to test this case).

**Comment by mns** [comment]
https://github.com/mangosR2/mangos/commit/9903c77ac76ae84a6b8400a42b2fe83fda1e7a97

**Comment by Undergarun** [comment]
Thank you!
