### ISSUE TITLE
Festergut

### ISSUE THREAD

**Issue by Voidx** [mangosR2/scriptdev2#17]
If you start Festergut with a pet the boss no apply Vile Gas.

**Comment by ghost** [comment]
like he wont cast it at all during the whole fight or what?

**Comment by Voidx** [comment]
yes, if use pet to pull vile gas no work.

**Comment by ghost** [comment]
https://github.com/mangosR2/scriptdev2/commit/3f5941d2b73a741984eaa4bf9a7effdddba8f55e
