### ISSUE TITLE
Professor Putricide

### ISSUE THREAD

**Issue by Voidx** [mangosR2/scriptdev2#18]
When you call the boss with a pet, does not attack with any of its spells.

**Comment by ghost** [comment]
again more info please  like the whole fight he wont cast ?

**Comment by michalpolko** [comment]
I had a report from players that this boss doesn't cast any spells. I was like wtf? Maybe they pulled with pet as well... Interesting.

**Comment by ghost** [comment]
ill test this when i get home  unless a few other wanna speak up and confirm for sure8)

**Comment by Voidx** [comment]
yes, if the boss is pulled with pet no cast spells xD

**Comment by Asprorpsa** [comment]
https://github.com/Asprorpsa/scriptdev2/commit/3401368b424ebe4386085817fe6b2232050da519
тестируйте

**Comment by ghost** [comment]
that might work
