### ISSUE TITLE
Ulduar-Algalon the Observer.

### ISSUE THREAD

**Issue by ghost** [mangosR2/scriptdev2#186]
Algalon the Observer.http://www.wowhead.com/npc=32871
Good afternoon.Bugs on the boss.
Celestial Planetarium(GO_CELESTIAL_ACCES          = 194628,) does not open key.However hard they tried.Must open door if the key without any additional conditions.There are two doors. There should be one.GO_CELESTIAL_DOOR           = 194767,
I opened through spell dm по области(30758 ).
No Brann Bronzebeard.He must be present at the opening event And at the final.Algalon immediately appears in the center, there is no visual teleportation.Here is the right spell Destroy Platform Boom Visual(59084).Also missing weapon in his hands(45620 suitable).The final event at Algalon below question.
SPELL_COSMIC_SMASH              = 62301-Do not use
SPELL_BLACK_HOLE_SHIFT          = 62168,Not working.
Do not teleport a player in a black hole. Also live constellation (33052) also.
 SPELL_PHASE_PUNCH               = 64412, //At a set of five stacks, not teleport in black hole.
NPC_UNLEASHED_DARK_MATTER       = 34097, Missing
NPC_DARK_MATTER                 = 33089,  Shall Only be in a black hole
Maybe I'll find more, just write. Very interesting boss.
Tested today on a test server Mangos P2.Thanks in advance.

**Comment by ghost** [comment]
Скорее всего иссуй надо более грамотно переоформить.

**Comment by rsa** [comment]
? not need close. may add info in issue...

**Comment by ghost** [comment]
Хорошо,добавлю.Когда грамотно смогу составить.Чтобы не вводить в заблуждение.

**Comment by ghost** [comment]
Убирать замок от планетария - не выход, дверь откроется, но эвент не начнется. Попробую поменять Lock id, а может все дело в Playercreateinfo_spell, хотя не это бред.
Ушел разбираться дальше.
 pCreature->SetVisibility(VISIBILITY_OFF); именно эта строчка делает его невидимым, а при юзе итема 
VISIBILITY_OFF меняется на VISIBILITY_ON. Это видимо защита от тех, кто без ключа пытается запустить босса.

**Comment by ghost** [comment]
Проблема решена! Можно закрыть.

**Comment by rsa** [comment]
ммм... каким образом?!! никто ничего не делал вроде.

**Comment by Sar777** [comment]
проблемы сами появляются и сами исчезают :smile:

**Comment by ghost** [comment]
Хаково решил, поменял LockId и проблеме бай бай) У геймобъекта. В дбц нет нужного lockid для этого итема(по крайней мере для 10-тки)
pCreature->SetVisibility(VISIBILITY_OFF) если это убрать(а это вообще должно тут быть?) То и хак ненужен.
Предлагать хак не стану, а то пошлёте куда подальше)

**Comment by rsa** [comment]
часто по хаку можно просто найти правильное решение... а ваш текст я не понял. какой lockid в дбц?!!

**Comment by ghost** [comment]
Понимаете, суть хака в том, что я ему поставил lockid  от хозяйского ключа(тот который дверь Каражана открывает), вот и все. Применил этот хак к Священному Планетарию и дверь открывается и Алгалон убирает свою невидимость и становится доступным для боя.
По поводу дбц - я искал номер итема в 10 колонке, чтобы найти lockid, но там было пусто(для 25-тки это 1831 для итема 45798(героический доступ к Планетарию), но ключ не хотел открывать дверь), бара открывание нет, поэтому зашел в дбц нашел 24490 в 10 колонке и 1700 - это и есть lockid, залез в базу нашел id объекта Планетария 194628 нашел в data 0 какой-то левый id, которого в дбц нет, поменял на 1700 и все. Дверь начала открываться(каст бар открывание), дверь открылась = вперед на пути к боссу. Все.

Update `gameobject_template` (`entry`, `data0`) values('194628','1700');
Надеюсь правильно запрос составил.
Так-что это неправильное решение, это грубый хак, но какое-никакое решение.

**Comment by ghost** [comment]
Как вам известно уже, в чистом СД2 реализовали Алгалона, правда нехватает деспавна и ресуммона(Раду конечно говорил, что без необходимости делать этого не нужно, но этот босс не из разряда стой бей)
                if(!m_bIsPhase2 && m_creature->GetHealthPercent() < 1)
                         m_creature->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
А при достижение MovePoint убирать флаг, чтобы повторно не агрился.
А то при повторном аггро и эвейде запускается Defeat эвент(тот, который должен запускаться только через час на Вотлк) и тогда всё труба.
Созвездия у него почему-то танков не могут атаковать, хотя должны(если соло идти)
Но в принципе скрипт лучше старого. Жаль звание на оффе давалось только за фёрст килл (Небесный Заступник в режиме на 25 человек), хотя Звёздный Скиталец тоже ок)

**Comment by ghost** [comment]
Меня радует, что многое стараются сделать в базе(где ненужно слишком сложных скриптов), например вайпоинты Бранна, исправить в разы проще. Вы и сами на РуМангосе когда-то говорили, что всё можно и нужно делать через EAI(правда спеллы чинить в ядре, а не хакать скриптом), но функционал ограничен(хотя db_script здорово помогает)
На Р2 создать через spell_dbc спелл с scripteffect и вот оно взаимодействие между EAI и db_script. Например создать спелл для старта вайпоинтов, старта рандомного движения, паузы для вайпоинтов и так далее. Хаково, но выбора нет. Ждать пока кто-то реализует? Да ну нафиг, проще самому!
Вы случайно не знаете какой аттрибут отвечает за то, чтобы при эвейде можно было кастовать спелл(не при возврате домой, а именно при эвейде)? Заранее спасибо. Есть ещё какой-то аттрибут(если не ошибаюсь) который не позволяет ауре удалиться при эвейде существа с помощью метода Removeallaurasonevade.
