### ISSUE TITLE
Compile Error 

### ISSUE THREAD

**Issue by Dokman** [mangosR2/scriptdev2#190]
Error   11  error C3668: 'instance_blackrock_spire::GetData' : el método con el especificador de invalidación 'override' no invalidó ningún método de clase base (C:\mangos\src\bindings\scriptdev2\scripts\eastern_kingdoms\blackrock_mountain\blackrock_spire\boss_gyth.cpp) c:\mangos\src\bindings\scriptdev2\scripts\eastern_kingdoms\blackrock_mountain\blackrock_spire\blackrock_spire.h 105

Error   12  error C3668: 'instance_blackrock_spire::GetData' : el método con el especificador de invalidación 'override' no invalidó ningún método de clase base (C:\mangos\src\bindings\scriptdev2\scripts\eastern_kingdoms\blackrock_mountain\blackrock_spire\boss_pyroguard_emberseer.cpp)  c:\mangos\src\bindings\scriptdev2\scripts\eastern_kingdoms\blackrock_mountain\blackrock_spire\blackrock_spire.h 105

Error   13  error C3668: 'instance_blackrock_spire::GetData' : el método con el especificador de invalidación 'override' no invalidó ningún método de clase base (C:\mangos\src\bindings\scriptdev2\scripts\eastern_kingdoms\blackrock_mountain\blackrock_spire\instance_blackrock_spire.cpp)  c:\mangos\src\bindings\scriptdev2\scripts\eastern_kingdoms\blackrock_mountain\blackrock_spire\blackrock_spire.h 105

**Comment by rsa** [comment]
#191
