### ISSUE TITLE
compiling error Windows

### ISSUE THREAD

**Issue by Dokman** [mangosR2/scriptdev2#191]
Error   1   error C3668: 'instance_blackrock_spire::GetData' : el método con el especificador de invalidación 'override' no invalidó ningún método de clase base (C:\mangos\src\bindings\scriptdev2\scripts\eastern_kingdoms\blackrock_mountain\blackrock_spire\boss_gyth.cpp) c:\mangos\src\bindings\scriptdev2\scripts\eastern_kingdoms\blackrock_mountain\blackrock_spire\blackrock_spire.h 105

Error   2   error C3668: 'instance_blackrock_spire::GetData' : el método con el especificador de invalidación 'override' no invalidó ningún método de clase base (C:\mangos\src\bindings\scriptdev2\scripts\eastern_kingdoms\blackrock_mountain\blackrock_spire\boss_pyroguard_emberseer.cpp)  c:\mangos\src\bindings\scriptdev2\scripts\eastern_kingdoms\blackrock_mountain\blackrock_spire\blackrock_spire.h 105

Error   3   error C3668: 'instance_blackrock_spire::GetData' : el método con el especificador de invalidación 'override' no invalidó ningún método de clase base (C:\mangos\src\bindings\scriptdev2\scripts\eastern_kingdoms\blackrock_mountain\blackrock_spire\instance_blackrock_spire.cpp)  c:\mangos\src\bindings\scriptdev2\scripts\eastern_kingdoms\blackrock_mountain\blackrock_spire\blackrock_spire.h 105

**Comment by conan513** [comment]
confirmed
