### ISSUE TITLE
Compiling Error Windows in Bass Sartura

### ISSUE THREAD

**Issue by Dokman** [mangosR2/scriptdev2#192]
Error   4   error C2039: 'FixateTarget' : no es un miembro de 'Creature'    C:\mangos\src\bindings\scriptdev2\scripts\kalimdor\temple_of_ahnqiraj\boss_sartura.cpp  160

Error   5   error C2039: 'FixateTarget' : no es un miembro de 'Creature'    C:\mangos\src\bindings\scriptdev2\scripts\kalimdor\temple_of_ahnqiraj\boss_sartura.cpp  226

Error   6   error C2039: 'FixateTarget' : no es un miembro de 'Creature'    C:\mangos\src\bindings\scriptdev2\scripts\kalimdor\temple_of_ahnqiraj\boss_sartura.cpp  236

Error   7   error C2039: 'FixateTarget' : no es un miembro de 'Creature'    C:\mangos\src\bindings\scriptdev2\scripts\kalimdor\temple_of_ahnqiraj\boss_sartura.cpp  263

Error   8   error C2039: 'FixateTarget' : no es un miembro de 'Creature'    C:\mangos\src\bindings\scriptdev2\scripts\kalimdor\temple_of_ahnqiraj\boss_sartura.cpp  274

**Comment by Dokman** [comment]
Error   1   error C2039: 'FixateTarget' : no es un miembro de 'Creature'    C:\mangos\src\bindings\scriptdev2\scripts\kalimdor\temple_of_ahnqiraj\boss_sartura.cpp  111

Error   2   error C2039: 'FixateTarget' : no es un miembro de 'Creature'    C:\mangos\src\bindings\scriptdev2\scripts\kalimdor\temple_of_ahnqiraj\boss_sartura.cpp  121

Error   3   error C2039: 'FixateTarget' : no es un miembro de 'Creature'    C:\mangos\src\bindings\scriptdev2\scripts\kalimdor\temple_of_ahnqiraj\boss_sartura.cpp  148

**Comment by rsa** [comment]
need have core with 12328 (R2 2602 and above) cmangos commit and also cleanup PCH.

**Comment by Dokman** [comment]
ok i have the new veraion now i recompile
