### ISSUE TITLE
Ulduar - Faceless Horror

### ISSUE THREAD

**Issue by Undergarun** [mangosR2/scriptdev2#195]
Faceless Horror should cast Void Beast between 10-25% hp in order to remove Void Barrier http://www.wowhead.com/spell=63710 at npc dead.

**Comment by ghost** [comment]
Fix in https://github.com/mangosR2/scriptdev2/commit/c0dd7324c7e130ed33828b18e83d7196739d4e66
Good evening.

**Comment by Undergarun** [comment]
Thank you.

**Comment by rsa** [comment]
confirmed? then close.
