### ISSUE TITLE
[SD2] Suggestion

### ISSUE THREAD

**Issue by Dokman** [mangosR2/scriptdev2#198]
why do not merge with the newest things of ulduar of the official scriptdev2 ?

**Comment by rsa** [comment]
send this question to SD2. R2 ulduar code long time much more developed then in SD2. all "newest things" from last SD2 included in R2 SD2 in 2011 year :)

**Comment by ghost** [comment]
Я незнаю,почему они нехотят импортировать код.В Р2 все очень классно сделано.Объединение двух проектов в МангосР2 было бы здорово.Люди грамотные,толковые.

**Comment by rsa** [comment]
у каждого проекта свои стандарты и своя политика, так что ничего странного. к тому же там меня давно не любят :)

**Comment by ghost** [comment]
Меня это огорчает честно говоря.Сообща делать намного веселее.Но я буду верить,что вы все же объединитесь.Я со своей стороны,могу разве что EventAI скриптами помогать,ну а в ядре базовое АИ написать(каст-речь).Благодаря Мангосу и вашему проекту отдельно(спасибо вам),код становится понятнее.Благодарю вас.
