### ISSUE TITLE
how can i edit the fgm commands?

### ISSUE THREAD

**Issue by Dokman** [mangosR2/scriptdev2#199]
for example how edit .namego to .appear ?

**Comment by rsa** [comment]
1. change in core code. 2. chande in DB.

**Comment by Dokman** [comment]
i know it rsa but the question what code is XD

**Comment by Undergarun** [comment]
Look into Level0.cpp, Level1.cpp, Level2.cpp and Level3.cpp and Chat.cpp

**Comment by Dokman** [comment]
ok thx ^^
