### ISSUE TITLE
Problem with all bosses

### ISSUE THREAD

**Issue by Voidx** [mangosR2/scriptdev2#20]
http://www.youtube.com/watch?v=aC49ttIn6gY

See this video. Lanathel atack to princes.

In toc the worms atacks themselves.

**Comment by ghost** [comment]
This doesn't look like all bosses.  My first guess is faction template got changed somewhere. At work so really can't check

**Comment by Voidx** [comment]
faction template same in 4 bosses

**Comment by ghost** [comment]
Well that's not right iic and toc. Aren't the same faction

**Comment by Voidx** [comment]
the problem : 2 boss + same faction + areaspell = fight of the two

see this video i take it now.

**Comment by ghost** [comment]
after getting home and running the event myself ( hows it suppose to )  and watching your video   your DB has errors old script, something not right on your end first the princes are suppose to FD til queen free s them  after a fews texts and then she fades away  after seeing this im gonna guess ToC is the same thing faultly DB

**Comment by Voidx** [comment]
omg you close this but the bosses continues atack to the same factions.

**Comment by ghost** [comment]
Ya the problem is YOUR DATABASE A CLEAN R2 and if u run the event how your suppose to event is fine read my comment above

**Comment by Voidx** [comment]
i use ytdb clean and clean r2

**Comment by ghost** [comment]
Something not right then on your end I've test run this event myself and had no troubles. In your video there not even FD with the red beam on them maybe your missing some sql. I recommend rebuilding your MANGOSDB as well as sd2 db

**Comment by ghost** [comment]
had an hour before school this morning rerun event on a fresh newly built DB ,core and SD2   and no problems 8P

**Comment by Voidx** [comment]
before school xDDD im engineer.... but no problem ^^ i come to see it by myself

**Comment by ghost** [comment]
Im in school for to be a master programmer and software developer but my first year sucks ass im taking all my core classes first (english math ect ect)

**Comment by Voidx** [comment]
fallenangelX the Queen wich attacking my partner is the one on the top floor, not the princes event queen.
I use UDB CLEAN DB AND ALL MR2 changes and de fault continue.

**Comment by ghost** [comment]
UDB = american rushed not that good shit    possible missing ALOT of data 
( fyi im american )

R2 is built around YTDB  works good and is in english too
but DB might not be problem 

```
again after watching your video   flying (gm mode and tto close to ceiling)  might be aggroing her down     on a clean R2  ytdb w/ core and sd2 sqls   and r2 sd2   after testing running this a few times now she has never came down like how your saying   (  and she never will if your following regular gameplay rules)  
```

think about this  your the only one who has brought this up  and people raid R2 ICC almost everyday  i bet  8)

**Comment by Voidx** [comment]
i use ytdb always but test with udb and same happens. Faction_A and Faction_H=16 in ytdb, and 14 in udb, i change it to test in other factions but when a boss do some spells in area makes this happen. (not all spells).

Clean r2 clone.
Last rev. And vmaps on.

**Comment by Voidx** [comment]
you need to wipee 1 time to see the problem.

**Comment by ghost** [comment]
Ill wipe. On purpose next test if I can get my homework done tonight ill give it a test run and see what happens. 8) but will get it checked

**Comment by Voidx** [comment]
thanks fallenangelX ^^ this is a strange problem

**Comment by ghost** [comment]
just reopening til i check this again 8)

**Comment by Voidx** [comment]
this problem can chek wen fly and wipee 1 time, or can change range in creature_model_info

**Comment by ghost** [comment]
I haven't had a chance to get to this yet.  Don't worry its on my mind I've almost unburied myself from the mountain of homework and should have to checked by this weekend. Ty for your patience

**Comment by ghost** [comment]
after testing today for about 2 hrs trying everything and be creative  as well as wiping in different ways  i can official say that if you do this event like your suppose to  then it works fine and queen is kool 8)

**Comment by michalpolko** [comment]
Same problem in Obsidian Sanctum, trash mobs attack dragons, maybe they are targeted by AoE spells and that aggroes them, dunno.

**Comment by Voidx** [comment]
yes same problem in obsidian and toc.
