### ISSUE TITLE
Hyjal_summit(Битва за Гору Хиджал)

### ISSUE THREAD

**Issue by ghost** [mangosR2/scriptdev2#204]
Hello I spoke with about Schmoozerd Hyjal.Here's a link https://github.com/scriptdev2/scriptdev2/issues/42. He proposed to test this patch. http://paste2.org/p/3045957
Please see. Maybe this will help solve the problem of bosses despawned on the fight.Thanks in advance.
Перевод на русский язык:
Здравствуйте. Я переговорил с Schmoozerd по поводу Хиджала.
Вот ссылка https://github.com/scriptdev2/scriptdev2/issues/42.
Он предложил протестировать вот этот патч. http://paste2.org/p/3045957
Посмотрите пожалуйста. Может это поможет решить проблему с деспавном боссов по время боя.Заранее спасибо.Я протестирую на тестовом сервере.Я иссуи стараюсь писать тогда,когда досконально протестирую все.Чтобы не вводить в заблуждение.

**Comment by Reamer** [comment]
Real solution change the tempsummon type

**Comment by ghost** [comment]
Reamer There's a problem with the restart event period. Jaina and Thrall did not restart it in case of failure.
https://github.com/scriptdev2/scriptdev2/commit/ba434f90c5ed4f052dfc27b44c759895faad8dad
Please see.Schmoozerd did fix.

**Comment by Reamer** [comment]
Then someone should merge with sd2 if that is a solution

**Comment by ghost** [comment]
К сожалению непомогло.Плюс после убийства Анетерона(точнее разговора с Джайной,когда она должна начать отступление появляется непонятный тотем и добавляется в счетчик,следовательно эвент у Тралла запустить уже нельзя.
Unfortunately did not help. Plus after killing Anetheron (more conversation with Jaina, when it should start to retreat appears strange totem and added to the counter, hence Event at Thrall run anymore.

**Comment by rsa** [comment]
и не поможет. эта страннная смесь EAI и SD2 в одной инсте вряд ли поддается ремонту, люди которые ее изобрели давно бросили мангос. попытка Шму подчистить - ну оно конечно хорошо, но проблему не решит, надо писать заново.

**Comment by ghost** [comment]
Странно в Аркатраце смесь ЭвентАИ и СД2(эвент предвестника Скайрисса)работает как часы!Даже резет как на оффе сделан.
Ну чтож придется хакать.Я имею ввиду custom моба прилепить и заставлять его вызывать.Чтобы до Архимонда хотя-бы добратся.Заново писать-это геморрой.Тем более,на оффициальном сервере БК инсты немного проапгрейдили.

**Comment by ghost** [comment]
Простите.Гляньте пожалуйста еще вот это https://github.com/scriptdev2/scriptdev2/issues/37
Иссуй по Ночной Погибели в Каражане.Ответы были даны.Просто он не заспавнен в игре.А как выяснилось надо спавнить в игре где-то на горе,активировать урну,он проснется и начнет лететь на Террасу Мастера.Там еще если гриды будут выгружены,он не прилетит.Заранее спасибо.Я на тестовом сервере посмотрю,что да как.Заранее спасибо.

**Comment by rsa** [comment]
надо проверить чтобы был заспавнен как active и всего делов...

**Comment by ghost** [comment]
К сожалению его самого нет.Тоесть он не заспавнен,нужно спавнить вручную.
Даже пройдя 2 цепочки квестов(1 заканчивается гибелью Малчезара,а вторая при уважении дается на Ночную Погибель).Также пройдя эвент Полночи,Благочестивой Девы,Мороуза И Оперы(после Оперы он и должен триггерится)он отказывается появиться(как и выяснилось в том иссуе,требуется ручной спавн в мире)
С помощью команды .gps нашел более близкие к Террасе координаты на горе.
Карта 532,зона 3457,фаза 1
x:-11027.660156
y:-1794.266846
z:152.792282
Ориентация:4.016408

**Comment by tst12** [comment]
насколько помнится, когда боролся с этим лет несколько назад, проблема была в том, что в базе отсутствует ивент от урны

**Comment by ghost** [comment]
Скрипт заимплементили год назад.В scripted_event запись есть.Как объяснил Xfurry,надо заспавнить его на горе,активировать урну,он проснется и полетит.Все,но на тестовом сервере он не заспавнен.
