### ISSUE TITLE
Ulduar-Hodir.

### ISSUE THREAD

**Issue by ghost** [mangosR2/scriptdev2#205]
Hello Managed to thoroughly test the boss Hodir (32 845) in Ulduar, in the mode of 10 and 25.
1) SPELL_ICICLE = 62234, does not use
2) SPELL_COLLAPSING_ICICLE = 69424, creates 2 laps, but not falling icicles and the snow is not created, so from SPELL_FLASH_FREEZE = 61968, is indefensible
3) npc_hodir_helper (32941,32950,32946,32948) do not use their abilities, as they always are frozen (10 released only 2 NPC, only 4 in 25, but they do not use their abilities anyway, should be released immediately and Do not freeze again. Apparently NPC_FLASH_FREEZE_NPC = 32938, spawn without stopping and imposes on them the camp. these assistants also have despawned after defeating the boss and do not respawn when evade boss.
4) SPELL_FLASH_FREEZE_KILL = 62226 does not kill frozen targets. At least NPC exactly players sometimes kills.
MangosR2 tested today.Outro event works okay, though not Hodir casts a spell of teleportation, but it's not critical.Thanks in advance.
Перевод на русский язык:
Здравствуйте. Удалось досконально протестировать босса Ходир(32845) в Ульдуаре,в режиме на 10 и 25 человек.
1) SPELL_ICICLE                = 62234, не использует
2)SPELL_COLLAPSING_ICICLE     = 69424, создает 2 круга,но сосульки не падают и сугроб не создается, следовательно от SPELL_FLASH_FREEZE          = 61968, защититься нельзя
3)npc_hodir_helper (32941,32950,32946,32948) не используют свои способности,также они все время оказываются замороженные(в 10 освобождаются только 2 нпц,в 25 только 4, но они не используют свои способности все равно, должны освобождаться сразу же и не замораживаться вновь. Видимо     NPC_FLASH_FREEZE_NPC    = 32938, спавнится без остановки и накладывает на них стан. Также эти помощники не деспавнятся после победы над боссом и не респавнятся в случае evade босса.
4)SPELL_FLASH_FREEZE_KILL     = 62226, не убивает замороженные цели. По крайней мере нпц точно,игроков иногда убивает.
Тестировал сегодня на МангосР2.
Outro event  Работает в порядке,правда Ходир не кастует спелл телепортации,но это некритично.
Заранее спасибо.Тестировал 1 месяц подряд.Наблюдал за изменениями.
Ссылка на скрипт босса и на нпц;
1)Скрипт(script)-https://github.com/mangosR2/scriptdev2/blob/master/scripts/northrend/ulduar/ulduar/boss_hodir.cpp
2)https://github.com/mangosR2/scriptdev2/blob/master/scripts/northrend/ulduar/ulduar/ulduar.h
Заранее спасибо.
 GO_CACHE_OF_RARE_WINTER     = 194200,
 GO_CACHE_OF_RARE_WINTER_H   = 194201,
Нельзя открыть.Сундук спавнится скриптом в случае победы над боссом в течении 3 минут.
You can not open. Chest spawns script in case of a victory over the boss in the next 3 minutes.

**Comment by Reamer** [comment]
Take a look to my Hodir script. i have no time for merge. This script should work, maybe you have time to test.
https://github.com/Reamer/scriptdev2/tree/master/scripts/northrend/ulduar/ulduar

**Comment by ghost** [comment]
Reamer,Thank you,it is necessary to ask Rsa to add.

**Comment by Reamer** [comment]
No, it isn't necessary to ask rsa for add. We are a developer community and not a one person show. But we must test the scripts + mabye add SQL queries. As i wrote i have no time for clean merge

**Comment by ghost** [comment]
All right. Thank you, just Rsa told me that before writing bug reports tested it on a test server, not on the fact that compile themselves
Перевод на русский:
Хорошо. Спасибо вам,просто Рса мне говорил,чтобы перед написанием баг-репортов тестировали именно на тестовом сервере,а не на том, что компилируем сами.

**Comment by rsa** [comment]
i'm long ago not have sufficient time for see on Reamer repo :(

**Comment by ghost** [comment]
Эх.Еще по Йогг-Сарону надо составить баг-репорт,некоторые ошибки у меня есть идеи как исправить,а вот с другими незнаю.
Translate to English:
More on Yogg-Saron should make a bug-report, some errors I have ideas how to fix, but the other do not know. Just don `t know how to properly explain them.

**Comment by ghost** [comment]
Case не обрабатывается у npc_hodir_helper, наверное из-за этого они и не используют свои способности.
SPELL_COLLAPSING_ICICLE, странно и скрипт нпц есть и в ядре фикс, но тоже не обрабатывается.
https://github.com/Schmoozerd/scriptdev2/tree/ulduar
Вот в репо Шму АИ аддов разделено. Может оно и лучше?
Скрипт Reamer по его словам работает нормально, нужен мерж значит!

**Comment by rsa** [comment]
Займетесь? У меня что-то времени даже сообщения почитать нету... Вот на майских может до ядра доберусь, а до скриптов - даж и не знаю когда...

**Comment by ghost** [comment]
К сожалению моих познаний хватает лишь на базовое АИ в ядре и EventAI скрипты. Я по мере возможности изучаю код ядра и SD2, Xfurry недавно говорил, что закончит БК и Классик контенты, займется Ульдуаром!

**Comment by ghost** [comment]
Хм, как оказалось нпц Орды используют спеллы и вообще все отлично! А вот у Альянса деревянные какие-то.

**Comment by ghost** [comment]
Иссуй можно закрывать) xfurry решил проблему с Ходиром :dancer  :+1: D
А hodir_helper вообще из SD2 выпилил и добавил скрипт в EAI.
Ждемс мержа)
