### ISSUE TITLE
Sunwell Plateau-Brutall and Madrigosa.

### ISSUE THREAD

**Issue by ghost** [mangosR2/scriptdev2#206]
Hello Not start and Event Brutall and Madrigosa it arrives put ice barrier and everything hangs on the spot.Event with Kalecgos was is passed successfully.
Tested on MangosR2.
Перевод на русский язык.
Здравствуйте. Перестал запускаться эвент Бруталла и Мадригоса, она прилетает ставит ледяной барьер и все висит на месте.
Эвент с Калесгосом был пройден успешно.

**Comment by rsa** [comment]
strange, script not changed long time...

**Comment by ghost** [comment]
Согласен,что сценарий не менялся.Прописал команду .npc aiinfo на Бруталла.
Brutallus intro event is currently not started-в настоящее время вступительный эвент не начался(как я понял примерно с перевода).У Мадригосы scriptname generic_creature.

**Comment by ghost** [comment]
Вот в дополнение, сделал деспавн для аддов босса Му'уру,а то куча трупов вызывает сильные задержки. Адды заскриптованы на ЭвентАИ( часовой,берсерк,маг и дитя бездны)
-- Creature id: 25772
UPDATE creature_template SET AIName='EventAI' WHERE entry=25772;
INSERT INTO creature_ai_scripts VALUES 
('2577207','25772','7','0','100','31','0','0','0','0','41','0','0','0','0','0','0','0','0','0','0','0','Despawn'),
('2577208','25772','6','0','100','31','0','0','0','0','41','0','0','0','0','0','0','0','0','0','0','0','Despawn');
-- Creature id: 25798
UPDATE creature_template SET AIName='EventAI' WHERE entry=25798;
INSERT INTO creature_ai_scripts VALUES 
('2579803','25798','6','0','100','31','0','0','0','0','41','0','0','0','0','0','0','0','0','0','0','0','Despawn'),
('2579804','25798','7','0','100','31','0','0','0','0','41','0','0','0','0','0','0','0','0','0','0','0','Despawn');
-- Creature id: 25799
UPDATE creature_template SET AIName='EventAI' WHERE entry=25799;
INSERT INTO creature_ai_scripts VALUES 
('2579904','25799','6','0','100','31','0','0','0','0','41','0','0','0','0','0','0','0','0','0','0','0','Despawn'),
('2579905','25799','7','0','100','31','0','0','0','0','41','0','0','0','0','0','0','0','0','0','0','0','Despawn');
-- Creature id: 25824
UPDATE creature_template SET AIName='EventAI' WHERE entry=25824;
INSERT INTO creature_ai_scripts VALUES 
('2582403','25824','6','0','100','31','0','0','0','0','41','0','0','0','0','0','0','0','0','0','0','0','Despawn'),
('2582404','25824','7','0','100','31','0','0','0','0','41','0','0','0','0','0','0','0','0','0','0','0','Despawn');

Translate:
Here are, in addition, made to despawn adds boss Mu'uru, and the heap of corpses causes severe delays. Adds scripted by EventAI (sentinel, berserker, a mage and a child Abyss)

**Comment by ghost** [comment]
Случилось чудо!Эвент снова работает!Спасибо!
