### ISSUE TITLE
Compile error on windows

### ISSUE THREAD

**Issue by ike3** [mangosR2/scriptdev2#210]
```
'instance_blackrock_spire::GetData' : method with override specifier 'override' did not override any base class methods
'instance_ahnkahet::GetData' : method with override specifier 'override' did not override any base class methods
```

Same for Save, GetData and CheckAchievementCriteriaMeet methods.

Modifier 'override' should be removed as there are no such virtual methods in base class

**Comment by rsa** [comment]
virtual methods declared in sources, see class MANGOS_DLL_SPEC InstanceData
problem in win compile only, need find real source of...

**Comment by ike3** [comment]
Compiles successfully now. Thanks!
