### ISSUE TITLE
ICC - Rotface big oozes

### ISSUE THREAD

**Issue by Kaasss-woe** [mangosR2/scriptdev2#212]
Hi,
it appears that Rotface's big oozes can no longer get taunted by the offtank. They stand stuck to their first target.

I think the problem comes from this patch https://github.com/mangosR2/scriptdev2/commit/2100a4325d7572fe1f8c726584539c2497e8477c and the use of FixateTarget().

The big ooze should not be fixated to its first target, but I don't know the best way to do (I don't want to be stoned because of a "dirty" code), so if anybody has a good idea...

**Comment by Undergarun** [comment]
Confirmed.

**Comment by rsa** [comment]
by wowhead ooze target fixated. this wrong?

**Comment by Kaasss-woe** [comment]
Looking to this post http://www.wowhead.com/npc=36627#comments:id=938694 (and its comment),  little oozes should be fixated but not big oozes. The offtank is supposed to keep them away from the raid.
Confirmed by several strategy guides.

**Comment by michalpolko** [comment]
Yup, big ooze should just have some huge aggro initially.

**Comment by Kaasss-woe** [comment]
Fixed here : https://github.com/mangosR2/scriptdev2/commit/048e8f4d0ca37966ff6432c4a8589f44ad4582bb
