### ISSUE TITLE
Eye of Eternity

### ISSUE THREAD

**Issue by ghost** [mangosR2/scriptdev2#214]
Hello
When activated, the focus of the rainbow (GO_FOCUSING_IRIS=193,958,GO_FOCUSING_IRIS_H = 193960,)  Malygos(28859) does not come to fight, instead, one more Malygos and Event begins outside of combat. Script Failed to test it that way.Tested it on a test server
Перевод на русский язык:
Здравствуйте 
При активации радужного средоточия(GO_FOCUSING_IRIS=193958,_GO_FOCUSING_IRIS_H =193960,)
 Малигос не вступает в бой,вместо этого появляется еще один Малигос(28859) и начинает эвент вне боя. Протестировать его скрипт неудалось таким образом.
Тестировал на тестовом сервере.
При помощи ключа с Сапфирона в Наксрамасе я пытался активировать Малигоса(ключи были выбиты как в режиме на 10,так и на 25 человек,все условия соблюдены)

**Comment by DDarkteam** [comment]
How to fix?
Как профиксить?

**Comment by ghost** [comment]
Никак, все поломалось, если сможете, то займитесь.
А может в базе какой-то косяк(так бывает).
