### ISSUE TITLE
"Testing" branch created

### ISSUE THREAD

**Issue by rsa** [mangosR2/scriptdev2#216]
For test new big changes.
currently:

https://github.com/mangosR2/scriptdev2/commit/6c5dcae4a20d022d66bfb8a877037f467d3eecc1

https://github.com/mangosR2/scriptdev2/commit/53606343b74045e28cf3566d33672924194f877f

**Comment by ghost** [comment]
Здравствуйте, удалось посмотреть Обсидиановое Святилище.
https://github.com/mangosR2/scriptdev2/commit/53606343b74045e28cf3566d33672924194f877f
Сартарион:
1)Огнепых(58907) использует при входе в бой. Должен использовать через 15 минут или при выводе его из платформы.
2)Весперон(30449)-баг заключается в том, что в случае вайпа его больше нельзя атаковать при повторном пуле Сартариона. Также он первый вступает в бой(при втором пуле) и использует свои способности, но его атаковать нельзя.
3)Аколит Весперона(31219)- появляется в мире сумерек в лаве, должен появляться на платформе.
Пока все, что удалось найти. Спасибо за работу.

**Comment by Undergarun** [comment]
All moved to master. Unable to understand Ulduar report about obsidiarian sanctum, but better to fix over main SD2 script.

**Comment by rsa** [comment]
Ulduar says from some tactical errors in bosses. 2 fixed, 1 && 3 requires correct script logic.
