### ISSUE TITLE
Генерал Заритриан.

### ISSUE THREAD

**Issue by ghost** [mangosR2/scriptdev2#217]
Здравствуйте, давно еще обнаружился неприятный баг босса Генерал Заритриан(39746). Суть в том, что он не использует свои способности. Использует только речь.
Должен использовать свои способности и вызывать слуг, а то просто манекен.
Скрипт у него есть, скриптнейм также присутствует.
Hello, long time yet found an annoying bug boss General Zarithrian (39746). The point is that it is not using its ability. Only uses it.Should use their abilities and call servants, and that is simply dummy.The script he has sсriptname also present.

**Comment by ghost** [comment]
Посмотрел в UpdateAI, стало понятно, в чем причина бага. BSW таблица не подтягивается и босс просто напросто не может использовать свои способности.
  void UpdateAI(const uint32 diff)
    {
        if (!m_creature->SelectHostileTarget() || !m_creature->getVictim())
            return;

```
    if (timedQuery(SPELL_CALL_FLAMECALLER, diff))
    {
        doSummon(NPC_FLAMECALLER, SpawnLoc[1].x, SpawnLoc[1].y, SpawnLoc[1].z);
        doSummon(NPC_FLAMECALLER, SpawnLoc[2].x, SpawnLoc[2].y, SpawnLoc[2].z);
```

//            if (currentDifficulty == RAID_DIFFICULTY_25MAN_NORMAL
//                || currentDifficulty == RAID_DIFFICULTY_25MAN_HEROIC)
//                doCast(SPELL_CALL_FLAMECALLER);

```
        DoScriptText(SAY_SUMMON,m_creature);
    }

    timedCast(SPELL_CLEAVE_ARMOR, diff);
    timedCast(SPELL_IMTIMIDATING_ROAR, diff);

    DoMeleeAttackIfReady();
}
```

};
Не происходит срабатывание. У прислужников скорее всего также, хотя странно.

**Comment by Sar777** [comment]
Если не ошибаюсь она пустая, когда то давно там что то "чистили" :). Проверьте эти спеллы в табличке.

**Comment by ghost** [comment]
Я тестирую на тестовом сервере, потому что Rsa говорил, что все баг-репорты желательно проверять именно на нем. А следовательно, доступа к базе нет. Нужно просить того, у кого есть доступ, посмотреть.

**Comment by rsa** [comment]
Все правильно делаете. Проверил BSW таблицы на тестовом, для кричи 39746 ничего не нашел. вроде бы все касты давно из bsw убрали для РС? я уже не в теме :) надо поправить...

**Comment by ghost** [comment]
Всем убрали. у Савианы, Балтара и Халиона в ядре скрипты(точнее таймера в SD2), у Заритриана таймера из BSW, которую почистили.

**Comment by ghost** [comment]
Решение одно может быть только: Снова занести эти спеллы в табличку. Правда я не уверен как это правильно делать, но попробую. На сим можно закрыть я думаю.
