### ISSUE TITLE
Compile error on windows

### ISSUE THREAD

**Issue by ike3** [mangosR2/scriptdev2#219]
on Windows:

```
scripts\outland\hellfire_citadel\shattered_halls\shattered_halls.h(84): 
error C3668: 'instance_shattered_halls::CheckConditionCriteriaMeet' : method 
with override specifier 'override' did not override any base class methods
```

**Comment by rsa** [comment]
not confirm, renew sources.

**Comment by ike3** [comment]
Introduced in [2882]. Could be the same as https://github.com/mangosR2/scriptdev2/issues/210
Still reproduces on [sd2_mr0587]

**Comment by rsa** [comment]
need any method for reproduce. not may repeat on fully clean 2800 && VC11
