### ISSUE TITLE
How we are going to handle versioning for SQL and per instance version?

### ISSUE THREAD

**Issue by Undergarun** [mangosR2/scriptdev2#227]
Now we have same folder sql_mr for whole sql data, but should have one per expansion or something like that. Same for different versions per instance like:
Scholomance, Zul'Gurub, Zul'Aman, Scarlet Monastery/Halls, etc...

**Comment by rsa** [comment]
make cata_scarlet_monastery_\* or mop_zulaman_\* scripts and use his in cata/mop version over db.

**Comment by Undergarun** [comment]
Perfect.
