### ISSUE TITLE
Tuten'kash

### ISSUE THREAD

**Issue by Faq** [mangosR2/scriptdev2#23]
Tuten'kash http://www.wowhead.com/npc=7355

she is spawned in ytdb whats completely wrong.

http://www.wowwiki.com/Tuten%27kash

gong:
http://old.wowhead.com/object=148917

in db gong is binded to eventid = 3130, what is now empty in db.

But such things(waves without timings) isnt possible with EAI now, so prolly gong just needs scripting.

**Comment by ghost** [comment]
wow old issue  you ever solve this if not ill get on it soon

**Comment by Faq** [comment]
no time to give it a try.

**Comment by ghost** [comment]
https://github.com/mangosR2/scriptdev2/blob/ee635c2b3525ec4ad9e9ae4de321cfc86ccc8f62/scripts/kalimdor/razorfen_downs/boss_tuten_kash.cpp    started on it  fun little event 8P

**Comment by ghost** [comment]
before anyone ask  it has to be done in sd2 there no way to control some varibles via ACID

**Comment by ghost** [comment]
https://github.com/mangosR2/scriptdev2/commit/0fb0408ea171db39690f92722fbf387d72dcaf89

also wouldn t mind getting a copy of your sd2 repo in a email all zipped up  "whistling"  8P

**Comment by Faq** [comment]
oh great ur the man :) will check it later.

**Comment by ghost** [comment]
just sorry it took so long  .. worked great for me wiith my little play grp on test server  (( just need some info like is there any text and true spawn locs )
