### ISSUE TITLE
Иллидан

### ISSUE THREAD

**Issue by Asprorpsa** [mangosR2/scriptdev2#26]
http://imagepost.ru/?v=bkmyypvjkgspfwrncirjrgsrpzblnr.jpg

после фазы с элементалями весит в воздухе и нифига не делает, бьет бот, мы не можем... в цель берется, а бить не бьется, ждем пока бот завершит свое дело... еще часа 3 осталось :D

**Comment by ghost** [comment]
any issues you post in sd2 can you please post native language and your best english

**Comment by Asprorpsa** [comment]
I write in German and English do not know much sorry

**Comment by ghost** [comment]
no biggie  i honestly am having trouble reading this  gonna have to try google translate 8)

**Comment by Asprorpsa** [comment]
лучше Русский переводи))
better Russian translation))

**Comment by ghost** [comment]
is what i get after trans this  ------ after the phase with the elementals in the air and weighs nifiga does not, hit the bot, we can not ... the target is taken, and the beat does not break, wait until the bot has completed its work ... another hour and three remained

**Comment by Asprorpsa** [comment]
after the phase with the elementals up in the air and does nothing (this phase has not even finished)

**Comment by ghost** [comment]
k  ty  now i get it

**Comment by ghost** [comment]
what  instance and boss is this i know i know it but im getting old  and did you guys fight here like normal
