### ISSUE TITLE
outdoor pvp and sd2 world maps scripts

### ISSUE THREAD

**Issue by ghost** [mangosR2/scriptdev2#27]
how did you guys wanna handle this conflict>>??

sd2 world maps if assigned will over write what we have of outdoor pvp

**Comment by michalpolko** [comment]
then outdoor pvp handling must be moved to world map scripts, right?

**Comment by ghost** [comment]
https://github.com/fallenangelX/outdoor-pvp  or back to core like Xfurry has done  in here

**Comment by ghost** [comment]
as soon as i get back in action  i was thinking moving to oPVP back to core but need alot of testing i honestly havent even played with ours yet so dont know yet 8)  ... i have dozens on different type of repos w opvp handled diff in my archives so might have something good come out of all it

**Comment by rsa** [comment]
i planning fully remove OPvP from current SD2 and try to port OPvP system from TC.

**Comment by ghost** [comment]
patienly waiting for outdoor pvp fun 8P
