### ISSUE TITLE
Crash with sindragosa spell 

### ISSUE THREAD

**Issue by Undergarun** [mangosR2/scriptdev2#3]
http://pastebin.com/mJpEPyn1

**Comment by tst12** [comment]
line 429 
-           || (victimGUID && !m_creature->GetMap()->GetPlayer(victimGUID)->HasAura(SPELL_ICY_TOMB)))
-           || (victimGUID && m_creature->GetMap()->GetPlayer(victimGUID) && !m_creature->GetMap()->GetPlayer(victimGUID)->HasAura(SPELL_ICY_TOMB)))

**Comment by Undergarun** [comment]
Thanks ;-)
