### ISSUE TITLE
Scriptdev2 compile bug - [EventManager]

### ISSUE THREAD

**Issue by sergeev** [mangosR2/scriptdev2#32]
Проблема: При компиляции scriptdev2 в конце построения выводится следующие

Компоновка...
   Создается библиотека ........\bin\win32_release/mangosscriptR2.lib и объект ........\bin\win32_release/mangosscriptR2.exp
sc_creature.obj : error LNK2019: ссылка на неразрешенный внешний символ "public: __thiscall EventManager::EventManager(void)" (??0EventManager@@QAE@XZ) в функции "public: class EventManager & __thiscall ScriptedAI::Events(void)" (?Events@ScriptedAI@@QAEAAVEventManager@@XZ)
........\bin\win32_release/mangosscriptR2.dll : fatal error LNK1120: 1 неразрешенных внешних элементов
Журнал построения был сохранен в "file://f:\ManGOS\releaseR2\src\bindings\scriptdev2\VC90\ScriptDev2__Win32_Release\BuildLog.htm"
ScriptDev2 - ошибок 2, предупреждений 0
========== Построение: успешно: 0, с ошибками: 1, без изменений: 0, пропущено: 0 ==========

Как видно из ошибки EventManager не включен в ScriptLoader ?

**Comment by sergeev** [comment]
Пока что просто так.
/*EventManager& ScriptedAI::Events()
{
    // use lazy initialization to save memory
    if (!m_events)
        m_events = new EventManager();

```
return *m_events;
```

}*/
в sc_creature.cpp

**Comment by Thermaltake** [comment]
https://github.com/mangosR2/scriptdev2/issues/33
http://paste2.org/p/1676831

**Comment by sergeev** [comment]
Спасибо!.
