### ISSUE TITLE
fos crash.

### ISSUE THREAD

**Issue by burninsky** [mangosR2/scriptdev2#35]
player fos enter and server crash.

Exception code: C0000005 ACCESS_VIOLATION
Fault address:  00000001400663DF 01:00000000000653DF C:\server\mangosd.exe

Registers:
RAX:0000000000000000
RBX:000007FFCCCF3DD0
RCX:0000000000000000
RDX:0000000000000000
RSI:00000000095343E0
RDI:000007FFCCCF3DD0
R8: 0000000009534390
R9: 0000000000000000
R10:0000000000000246
R11:0000000000083A68
R12:000007FFD2B04000
R13:0000000000000000
R14:0000000000000000
R15:0000000000000001
CS:RIP:0033:00000001400663DF
SS:RSP:002B:0000000009534248  RBP:09534390
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010257

Call stack:
Address   Frame     Function      SourceFile
00000001400663DF  0000000009534240  Database::getQueryConnection+3F  f:\1\mangos\src\shared\database\database.cpp line 234
00000000090FA678  0000000009534280  strSD2Pquery+28  f:\1\mangos\src\bindings\scriptdev2\scriptmgr.cpp line 71
0000000008F03561  000000000953C420  BSWScriptedAI::_loadFromDB+D1  f:\1\mangos\src\bindings\scriptdev2\base\bsw_ai.cpp line 60
0000000008F0492A  000000000953C460  BSWScriptedAI::BSWScriptedAI+6A  f:\1\mangos\src\bindings\scriptdev2\base\bsw_ai.cpp line 11
0000000008FFAED3  000000000953C4A0  boss_bronjahmAI::boss_bronjahmAI+23  f:\1\mangos\src\bindings\scriptdev2\scripts\northrend\icecrown_citadel\frozen_halls\forge_of_souls\boss_bronjahm.cpp line 54
0000000008FFB401  000000000953C4E0  GetAI_boss_bronjahm+31  f:\1\mangos\src\bindings\scriptdev2\scripts\northrend\icecrown_citadel\frozen_halls\forge_of_souls\boss_bronjahm.cpp line 233
000000014043CA83  000000000953D690  FactorySelector::selectAI+93  f:\1\mangos\src\game\creatureaiselector.cpp line 37
00000001401447B6  000000000953D6C0  Creature::AIM_Initialize+76  f:\1\mangos\src\game\creature.cpp line 783
000000014014C2BE  000000000953D770  Creature::LoadFromDB+3FE  f:\1\mangos\src\game\creature.cpp line 1379
0000000140436DA8  000000000953D7F0  LoadHelper<Creature>+A8  f:\1\mangos\src\game\objectgridloader.cpp line 120
000000014043756B  000000000953D850  ObjectGridLoader::Visit+FB  f:\1\mangos\src\game\objectgridloader.cpp line 198
00000001404377E5  000000000953D8A0  ObjectGridLoader::Load+15  f:\1\mangos\src\game\objectgridloader.cpp line 224
00000001404378A3  000000000953D8F0  ObjectGridLoader::LoadN+63  f:\1\mangos\src\game\objectgridloader.cpp line 242
00000001400C6218  000000000953E980  Map::EnsureGridLoaded+128  f:\1\mangos\src\game\map.cpp line 277
00000001400C8C1A  000000000953E9F0  Map::EnsureGridLoadedAtEnter+1A  f:\1\mangos\src\game\map.cpp line 238
00000001400D2FE8  000000000953EA40  Map::Add+E8  f:\1\mangos\src\game\map.cpp line 302
00000001400D4509  000000000953FBC0  DungeonMap::Add+789  f:\1\mangos\src\game\map.cpp line 1417
00000001404B6FEE  000000000953FCE0  WorldSession::HandleMoveWorldportAckOpcode+31E  f:\1\mangos\src\game\movementhandler.cpp line 126
000000014028FF3A  000000000953FD30  WorldSession::ExecuteOpcode+2A  f:\1\mangos\src\game\worldsession.cpp line 1039
0000000140295E39  000000000953FDB0  WorldSession::Update+189  f:\1\mangos\src\game\worldsession.cpp line 271
000000014008FF0E  000000000953FE10  World::UpdateSessions+9E  f:\1\mangos\src\game\world.cpp line 2058
0000000140092503  000000000953FE50  World::Update+133  f:\1\mangos\src\game\world.cpp line 1584
00000001400597A1  000000000953FE80  WorldRunnable::run+61  f:\1\mangos\src\mangosd\worldrunnable.cpp line 67
000000014006D36F  000000000953FEB0  ACE_Based::Thread::ThreadTask+F  f:\1\mangos\src\shared\threading.cpp line 190
000007FEE65D0A95  000000000953FEF0  ACE_OS_Thread_Adapter::invoke+55  f:\1\core\dep\ace_wrappers\ace\os_thread_adapter.cpp line 86
000000006D051DB7  000000000953FF20  _endthreadex+43
000000006D051E53  000000000953FF50  _endthreadex+DF
000000007710F56D  000000000953FF80  BaseThreadInitThunk+D
0000000077242CC1  000000000953FFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
000000007725F6FA  000000000012FAE0  NtWaitForSingleObject+A
000007FEFD2810AC  000000000012FB80  WaitForSingleObjectEx+9C
000007FEE657B86A  000000000012FBB0  ACE_OS::thr_join+2A  f:\1\core\dep\ace_wrappers\ace\os_ns_thread.inl line 2798
000007FEE65FE127  000000000012FC30  ACE_Thread_Manager::wait_task+237  f:\1\core\dep\ace_wrappers\ace\thread_manager.cpp line 1793
00000001402AFD2E  000000000012FC60  WorldSocketMgr::Wait+3E  f:\1\mangos\src\game\worldsocketmgr.cpp line 310
0000000140058262  000000000012FE30  Master::Run+5A2  f:\1\mangos\src\mangosd\master.cpp line 325
0000000140054891  000000000012FF20  main+4A1  f:\1\mangos\src\mangosd\main.cpp line 215
000000014005BCE6  000000000012FF50  __tmainCRTStartup+11A  f:\dd\vctools\crt_bld\self_64_amd64\crt\src\crtexe.c line 555
000000007710F56D  000000000012FF80  BaseThreadInitThunk+D
0000000077242CC1  000000000012FFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
000000007725FC6A  00000000028AFCB0  NtWaitForMultipleObjects+A
0000000077229A07  00000000028AFF50  EtwTraceMessageVa+E07
000000007710F56D  00000000028AFF80  BaseThreadInitThunk+D
0000000077242CC1  00000000028AFFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
000000007725F9FA  0000000002B7FD60  ZwDelayExecution+A
000007FEFD281203  0000000002B7FE00  SleepEx+B3
000000014006D4B6  0000000002B7FE50  ACE_Based::Thread::Sleep+46  f:\1\mangos\src\shared\threading.cpp line 238
000000014006EBBA  0000000002B7FE80  SqlDelayThread::run+4A  f:\1\mangos\src\shared\database\sqldelaythread.cpp line 50
000000014006D36F  0000000002B7FEB0  ACE_Based::Thread::ThreadTask+F  f:\1\mangos\src\shared\threading.cpp line 190
000007FEE65D0A95  0000000002B7FEF0  ACE_OS_Thread_Adapter::invoke+55  f:\1\core\dep\ace_wrappers\ace\os_thread_adapter.cpp line 86
000000006D051DB7  0000000002B7FF20  _endthreadex+43
000000006D051E53  0000000002B7FF50  _endthreadex+DF
000000007710F56D  0000000002B7FF80  BaseThreadInitThunk+D
0000000077242CC1  0000000002B7FFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
000000007725F9FA  0000000002DAFD60  ZwDelayExecution+A
000007FEFD281203  0000000002DAFE00  SleepEx+B3
000000014006D4B6  0000000002DAFE50  ACE_Based::Thread::Sleep+46  f:\1\mangos\src\shared\threading.cpp line 238
000000014006EBBA  0000000002DAFE80  SqlDelayThread::run+4A  f:\1\mangos\src\shared\database\sqldelaythread.cpp line 50
000000014006D36F  0000000002DAFEB0  ACE_Based::Thread::ThreadTask+F  f:\1\mangos\src\shared\threading.cpp line 190
000007FEE65D0A95  0000000002DAFEF0  ACE_OS_Thread_Adapter::invoke+55  f:\1\core\dep\ace_wrappers\ace\os_thread_adapter.cpp line 86
000000006D051DB7  0000000002DAFF20  _endthreadex+43
000000006D051E53  0000000002DAFF50  _endthreadex+DF
000000007710F56D  0000000002DAFF80  BaseThreadInitThunk+D
0000000077242CC1  0000000002DAFFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
000000007725F9FA  0000000002FFFD60  ZwDelayExecution+A
000007FEFD281203  0000000002FFFE00  SleepEx+B3
000000014006D4B6  0000000002FFFE50  ACE_Based::Thread::Sleep+46  f:\1\mangos\src\shared\threading.cpp line 238
000000014006EBBA  0000000002FFFE80  SqlDelayThread::run+4A  f:\1\mangos\src\shared\database\sqldelaythread.cpp line 50
000000014006D36F  0000000002FFFEB0  ACE_Based::Thread::ThreadTask+F  f:\1\mangos\src\shared\threading.cpp line 190
000007FEE65D0A95  0000000002FFFEF0  ACE_OS_Thread_Adapter::invoke+55  f:\1\core\dep\ace_wrappers\ace\os_thread_adapter.cpp line 86
000000006D051DB7  0000000002FFFF20  _endthreadex+43
000000006D051E53  0000000002FFFF50  _endthreadex+DF
000000007710F56D  0000000002FFFF80  BaseThreadInitThunk+D
0000000077242CC1  0000000002FFFFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
000000007725F6FA  000000000933FBE0  NtWaitForSingleObject+A
000007FEFD2810AC  000000000933FC80  WaitForSingleObjectEx+9C
000007FEE65CD04C  000000000933FCC0  ACE_OS::cond_wait+4C  f:\1\core\dep\ace_wrappers\ace\os_ns_thread.cpp line 1775
000007FEE65CE2CE  000000000933FD60  ACE_OS::cond_timedwait+2E  f:\1\core\dep\ace_wrappers\ace\os_ns_thread.cpp line 1620
000007FEE6579F9F  000000000933FD90  ACE_Message_Queue<ACE_MT_SYNCH>::wait_not_empty_cond+3F  f:\1\core\dep\ace_wrappers\ace\message_queue_t.cpp line 1744
000007FEE657A5F0  000000000933FDE0  ACE_Message_Queue<ACE_MT_SYNCH>::dequeue_head+70  f:\1\core\dep\ace_wrappers\ace\message_queue_t.cpp line 1936
000007FEE6579A7F  000000000933FE10  ACE_Activation_Queue::dequeue+1F  f:\1\core\dep\ace_wrappers\ace\activation_queue.cpp line 89
000000014057C976  000000000933FE40  DelayExecutor::svc+66  f:\1\mangos\src\shared\delayexecutor.cpp line 71
000007FEE65F9941  000000000933FE70  ACE_Task_Base::svc_run+41  f:\1\core\dep\ace_wrappers\ace\task.cpp line 286
000007FEE65F9EE5  000000000933FEB0  ACE_Thread_Adapter::invoke_i+45  f:\1\core\dep\ace_wrappers\ace\thread_adapter.cpp line 145
000007FEE65FA011  000000000933FEF0  ACE_Thread_Adapter::invoke+71  f:\1\core\dep\ace_wrappers\ace\thread_adapter.cpp line 94
000000006D051DB7  000000000933FF20  _endthreadex+43
000000006D051E53  000000000933FF50  _endthreadex+DF
000000007710F56D  000000000933FF80  BaseThreadInitThunk+D
0000000077242CC1  000000000933FFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
000000007725F6FA  000000000943FBE0  NtWaitForSingleObject+A
000007FEFD2810AC  000000000943FC80  WaitForSingleObjectEx+9C
000007FEE65CD04C  000000000943FCC0  ACE_OS::cond_wait+4C  f:\1\core\dep\ace_wrappers\ace\os_ns_thread.cpp line 1775
000007FEE65CE2CE  000000000943FD60  ACE_OS::cond_timedwait+2E  f:\1\core\dep\ace_wrappers\ace\os_ns_thread.cpp line 1620
000007FEE6579F9F  000000000943FD90  ACE_Message_Queue<ACE_MT_SYNCH>::wait_not_empty_cond+3F  f:\1\core\dep\ace_wrappers\ace\message_queue_t.cpp line 1744
000007FEE657A5F0  000000000943FDE0  ACE_Message_Queue<ACE_MT_SYNCH>::dequeue_head+70  f:\1\core\dep\ace_wrappers\ace\message_queue_t.cpp line 1936
000007FEE6579A7F  000000000943FE10  ACE_Activation_Queue::dequeue+1F  f:\1\core\dep\ace_wrappers\ace\activation_queue.cpp line 89
000000014057C976  000000000943FE40  DelayExecutor::svc+66  f:\1\mangos\src\shared\delayexecutor.cpp line 71
000007FEE65F9941  000000000943FE70  ACE_Task_Base::svc_run+41  f:\1\core\dep\ace_wrappers\ace\task.cpp line 286
000007FEE65F9EE5  000000000943FEB0  ACE_Thread_Adapter::invoke_i+45  f:\1\core\dep\ace_wrappers\ace\thread_adapter.cpp line 145
000007FEE65FA011  000000000943FEF0  ACE_Thread_Adapter::invoke+71  f:\1\core\dep\ace_wrappers\ace\thread_adapter.cpp line 94
000000006D051DB7  000000000943FF20  _endthreadex+43
000000006D051E53  000000000943FF50  _endthreadex+DF
000000007710F56D  000000000943FF80  BaseThreadInitThunk+D
0000000077242CC1  000000000943FFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
000000007726038A  0000000009532560  NtGetContextThread+A
00000000770F44FA  0000000009532590  GetThreadContext+A
000000014005AD1E  0000000009532AC0  WheatyExceptionReport::printTracesForAllThreads+BE  f:\1\mangos\src\shared\wheatyexceptionreport.cpp line 370
000000014005B027  0000000009533150  WheatyExceptionReport::GenerateExceptionReport+2B7  f:\1\mangos\src\shared\wheatyexceptionreport.cpp line 468
000000014005B23A  00000000095333F0  WheatyExceptionReport::WheatyUnhandledExceptionFilter+14A  f:\1\mangos\src\shared\wheatyexceptionreport.cpp line 109
0000000077189380  00000000095334D0  UnhandledExceptionFilter+160
00000000772A6228  0000000009533500  RtlWow64EnableFsRedirection+27F8
0000000077224F48  0000000009533570  __C_specific_handler+9C
0000000077244F6D  00000000095335A0  RtlCompareUnicodeString+8D
0000000077225B2C  0000000009533C80  RtlTimeToSecondsSince1970+63C
000000007725F638  0000000009534238  KiUserExceptionDispatcher+2E
00000001400663DF  0000000009534240  Database::getQueryConnection+3F  f:\1\mangos\src\shared\database\database.cpp line 234
00000000090FA678  0000000009534280  strSD2Pquery+28  f:\1\mangos\src\bindings\scriptdev2\scriptmgr.cpp line 71
0000000008F03561  000000000953C420  BSWScriptedAI::_loadFromDB+D1  f:\1\mangos\src\bindings\scriptdev2\base\bsw_ai.cpp line 60
0000000008F0492A  000000000953C460  BSWScriptedAI::BSWScriptedAI+6A  f:\1\mangos\src\bindings\scriptdev2\base\bsw_ai.cpp line 11
0000000008FFAED3  000000000953C4A0  boss_bronjahmAI::boss_bronjahmAI+23  f:\1\mangos\src\bindings\scriptdev2\scripts\northrend\icecrown_citadel\frozen_halls\forge_of_souls\boss_bronjahm.cpp line 54
0000000008FFB401  000000000953C4E0  GetAI_boss_bronjahm+31  f:\1\mangos\src\bindings\scriptdev2\scripts\northrend\icecrown_citadel\frozen_halls\forge_of_souls\boss_bronjahm.cpp line 233
000000014043CA83  000000000953D690  FactorySelector::selectAI+93  f:\1\mangos\src\game\creatureaiselector.cpp line 37
00000001401447B6  000000000953D6C0  Creature::AIM_Initialize+76  f:\1\mangos\src\game\creature.cpp line 783
000000014014C2BE  000000000953D770  Creature::LoadFromDB+3FE  f:\1\mangos\src\game\creature.cpp line 1379
0000000140436DA8  000000000953D7F0  LoadHelper<Creature>+A8  f:\1\mangos\src\game\objectgridloader.cpp line 120
000000014043756B  000000000953D850  ObjectGridLoader::Visit+FB  f:\1\mangos\src\game\objectgridloader.cpp line 198
00000001404377E5  000000000953D8A0  ObjectGridLoader::Load+15  f:\1\mangos\src\game\objectgridloader.cpp line 224
00000001404378A3  000000000953D8F0  ObjectGridLoader::LoadN+63  f:\1\mangos\src\game\objectgridloader.cpp line 242
00000001400C6218  000000000953E980  Map::EnsureGridLoaded+128  f:\1\mangos\src\game\map.cpp line 277
00000001400C8C1A  000000000953E9F0  Map::EnsureGridLoadedAtEnter+1A  f:\1\mangos\src\game\map.cpp line 238
00000001400D2FE8  000000000953EA40  Map::Add+E8  f:\1\mangos\src\game\map.cpp line 302
00000001400D4509  000000000953FBC0  DungeonMap::Add+789  f:\1\mangos\src\game\map.cpp line 1417
00000001404B6FEE  000000000953FCE0  WorldSession::HandleMoveWorldportAckOpcode+31E  f:\1\mangos\src\game\movementhandler.cpp line 126
000000014028FF3A  000000000953FD30  WorldSession::ExecuteOpcode+2A  f:\1\mangos\src\game\worldsession.cpp line 1039
0000000140295E39  000000000953FDB0  WorldSession::Update+189  f:\1\mangos\src\game\worldsession.cpp line 271
000000014008FF0E  000000000953FE10  World::UpdateSessions+9E  f:\1\mangos\src\game\world.cpp line 2058
0000000140092503  000000000953FE50  World::Update+133  f:\1\mangos\src\game\world.cpp line 1584
00000001400597A1  000000000953FE80  WorldRunnable::run+61  f:\1\mangos\src\mangosd\worldrunnable.cpp line 67
000000014006D36F  000000000953FEB0  ACE_Based::Thread::ThreadTask+F  f:\1\mangos\src\shared\threading.cpp line 190
000007FEE65D0A95  000000000953FEF0  ACE_OS_Thread_Adapter::invoke+55  f:\1\core\dep\ace_wrappers\ace\os_thread_adapter.cpp line 86
000000006D051DB7  000000000953FF20  _endthreadex+43
000000006D051E53  000000000953FF50  _endthreadex+DF
000000007710F56D  000000000953FF80  BaseThreadInitThunk+D
0000000077242CC1  000000000953FFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
000000007725F8DA  000000000963F8A0  ZwRequestWaitReplyPort+A
0000000077112B08  000000000963F8D0  GetConsoleMode+F8
0000000077145601  000000000963FA20  VerifyConsoleIoHandle+281
000000007715A922  000000000963FB00  ReadConsoleA+B2
0000000077129934  000000000963FB40  GetEnvironmentStringsA+5AB8
000000006D09C315  000000000963FBE0  _wsopen_s+261
000000006D09C8DD  000000000963FC30  _read+C5
000000006D05D350  000000000963FC60  _filbuf+80
000000006D05C917  000000000963FCC0  fgets+11F
0000000140048EB8  000000000963FE80  CliRunnable::run+D8  f:\1\mangos\src\mangosd\clirunnable.cpp line 621
000000014006D36F  000000000963FEB0  ACE_Based::Thread::ThreadTask+F  f:\1\mangos\src\shared\threading.cpp line 190
000007FEE65D0A95  000000000963FEF0  ACE_OS_Thread_Adapter::invoke+55  f:\1\core\dep\ace_wrappers\ace\os_thread_adapter.cpp line 86
000000006D051DB7  000000000963FF20  _endthreadex+43
000000006D051E53  000000000963FF50  _endthreadex+DF
000000007710F56D  000000000963FF80  BaseThreadInitThunk+D
0000000077242CC1  000000000963FFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
000000007725F9FA  000000000973FD60  ZwDelayExecution+A
000007FEFD281203  000000000973FE00  SleepEx+B3
000000014006D4B6  000000000973FE50  ACE_Based::Thread::Sleep+46  f:\1\mangos\src\shared\threading.cpp line 238
0000000140056D5A  000000000973FE80  FreezeDetectorRunnable::run+6A  f:\1\mangos\src\mangosd\master.cpp line 81
000000014006D36F  000000000973FEB0  ACE_Based::Thread::ThreadTask+F  f:\1\mangos\src\shared\threading.cpp line 190
000007FEE65D0A95  000000000973FEF0  ACE_OS_Thread_Adapter::invoke+55  f:\1\core\dep\ace_wrappers\ace\os_thread_adapter.cpp line 86
000000006D051DB7  000000000973FF20  _endthreadex+43
000000006D051E53  000000000973FF50  _endthreadex+DF
000000007710F56D  000000000973FF80  BaseThreadInitThunk+D
0000000077242CC1  000000000973FFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
000000007725F6FA  000000000983E910  NtWaitForSingleObject+A
000007FEFC9E3978  000000000983E990  0001:0000000000002978 C:\Windows\system32\MSWSOCK.dll
000007FEFC9F06B6  000000000983EB30  WSPStartup+7CD6
000007FEFF4C72BC  000000000983EB70  select+15C
000007FEFF4C723D  000000000983EC70  select+DD
000007FEE6587672  000000000983ED00  ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >::wait_for_multiple_events+142  f:\1\core\dep\ace_wrappers\ace\select_reactor_t.cpp line 1100
000007FEE6600B66  000000000983ED90  ACE_TP_Reactor::handle_events+B6  f:\1\core\dep\ace_wrappers\ace\tp_reactor.cpp line 169
000007FEE65DEA6D  000000000983EDC0  ACE_Reactor::run_reactor_event_loop+4D  f:\1\core\dep\ace_wrappers\ace\reactor.cpp line 267
00000001402B2448  000000000983FE40  ReactorRunnable::svc+108  f:\1\mangos\src\game\worldsocketmgr.cpp line 165
000007FEE65F9941  000000000983FE70  ACE_Task_Base::svc_run+41  f:\1\core\dep\ace_wrappers\ace\task.cpp line 286
000007FEE65F9EE5  000000000983FEB0  ACE_Thread_Adapter::invoke_i+45  f:\1\core\dep\ace_wrappers\ace\thread_adapter.cpp line 145
000007FEE65FA011  000000000983FEF0  ACE_Thread_Adapter::invoke+71  f:\1\core\dep\ace_wrappers\ace\thread_adapter.cpp line 94
000000006D051DB7  000000000983FF20  _endthreadex+43
000000006D051E53  000000000983FF50  _endthreadex+DF
000000007710F56D  000000000983FF80  BaseThreadInitThunk+D
0000000077242CC1  000000000983FFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
000000007725F6FA  0000000009A9E910  NtWaitForSingleObject+A
000007FEFC9E3978  0000000009A9E990  0001:0000000000002978 C:\Windows\system32\MSWSOCK.dll
000007FEFC9F06B6  0000000009A9EB30  WSPStartup+7CD6
000007FEFF4C72BC  0000000009A9EB70  select+15C
000007FEFF4C723D  0000000009A9EC70  select+DD
000007FEE6587672  0000000009A9ED00  ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >::wait_for_multiple_events+142  f:\1\core\dep\ace_wrappers\ace\select_reactor_t.cpp line 1100
000007FEE6600B66  0000000009A9ED90  ACE_TP_Reactor::handle_events+B6  f:\1\core\dep\ace_wrappers\ace\tp_reactor.cpp line 169
000007FEE65DEA6D  0000000009A9EDC0  ACE_Reactor::run_reactor_event_loop+4D  f:\1\core\dep\ace_wrappers\ace\reactor.cpp line 267
00000001402B2448  0000000009A9FE40  ReactorRunnable::svc+108  f:\1\mangos\src\game\worldsocketmgr.cpp line 165
000007FEE65F9941  0000000009A9FE70  ACE_Task_Base::svc_run+41  f:\1\core\dep\ace_wrappers\ace\task.cpp line 286
000007FEE65F9EE5  0000000009A9FEB0  ACE_Thread_Adapter::invoke_i+45  f:\1\core\dep\ace_wrappers\ace\thread_adapter.cpp line 145
000007FEE65FA011  0000000009A9FEF0  ACE_Thread_Adapter::invoke+71  f:\1\core\dep\ace_wrappers\ace\thread_adapter.cpp line 94
000000006D051DB7  0000000009A9FF20  _endthreadex+43
000000006D051E53  0000000009A9FF50  _endthreadex+DF
000000007710F56D  0000000009A9FF80  BaseThreadInitThunk+D
0000000077242CC1  0000000009A9FFD0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
0000000077260FBA  0000000008DFFC50  ZwWaitForWorkViaWorkerFactory+A
0000000077228F7B  0000000008DFFF50  EtwTraceMessageVa+37B
000000007710F56D  0000000008DFFF80  BaseThreadInitThunk+D
# 0000000077242CC1  0000000008DFFFD0  RtlUserThreadStart+21

Local Variables And Parameters

Call stack:
Address   Frame     Function      SourceFile
00000001400663DF  0000000009534240  Database::getQueryConnection+3F  f:\1\mangos\src\shared\database\database.cpp line 234
    Local  <user defined> 'this' = 90FA678

00000000090FA678  0000000009534280  strSD2Pquery+28  f:\1\mangos\src\bindings\scriptdev2\scriptmgr.cpp line 71
    Parameter  char\* 'str' = 140637398

0000000008F03561  000000000953C420  BSWScriptedAI::_loadFromDB+D1  f:\1\mangos\src\bindings\scriptdev2\base\bsw_ai.cpp line 60
punting on symbol this
    Local  ACE_Process_Mutex
         <user defined>  ACE_Process_Mutex
         <user defined>  ACE_Process_Mutex
         <user defined>  ACE_Process_Mutex
         <user defined>  ~ACE_Process_Mutex
         <user defined>  remove
         <user defined>  acquire
         <user defined>  acquire
         <user defined>  tryacquire
         <user defined>  release
         <user defined>  acquire_read
         <user defined>  acquire_write
         <user defined>  tryacquire_read
         <user defined>  tryacquire_write
         <user defined>  tryacquire_write_upgrade
         <user defined>  lock
         <user defined>  dump
         <user defined>  __Ace
         <user defined>  name_
         <user defined>  unique_name
         <user defined>  lock_
         <user defined>  operator=
         <user defined>  __dflt_ctor_closure
         <user defined>  __vecDelDtor

```
Local  char* 'query'
Local  BSWRecord
     unsigned int  id = FFFFFFFE
     <user defined>  m_uiSpellEntry
     <user defined>  m_uiSpellTimerMin
     <user defined>  m_uiSpellTimerMax
     <user defined>  m_uiSpellData
     <user defined>  LocData
     int  varData = 8FFB401
     unsigned int  StageMaskN = 0
     unsigned int  StageMaskH = CCCF3DD0
     int  m_CastTarget = 7FF
     bool  m_IsVisualEffect = 0
     bool  m_IsBugged = 40
     int  textEntry = 7FF
     unsigned int  m_SpellTimer = 0
```

0000000008F0492A  000000000953C460  BSWScriptedAI::BSWScriptedAI+6A  f:\1\mangos\src\bindings\scriptdev2\base\bsw_ai.cpp line 11
    Local  <user defined> 'this' = 0
    Parameter  <user defined> 'pCreature' = 8FFB401

0000000008FFAED3  000000000953C4A0  boss_bronjahmAI::boss_bronjahmAI+23  f:\1\mangos\src\bindings\scriptdev2\scripts\northrend\icecrown_citadel\frozen_halls\forge_of_souls\boss_bronjahm.cpp line 54
    Local  <user defined> 'this' = 7FFD48C4000
    Parameter  <user defined> 'pCreature' = 14043CA83

0000000008FFB401  000000000953C4E0  GetAI_boss_bronjahm+31  f:\1\mangos\src\bindings\scriptdev2\scripts\northrend\icecrown_citadel\frozen_halls\forge_of_souls\boss_bronjahm.cpp line 233
    Parameter  <user defined> 'pCreature' = 7FF00000000

000000014043CA83  000000000953D690  FactorySelector::selectAI+93  f:\1\mangos\src\game\creatureaiselector.cpp line 37
    Parameter  <user defined> 'creature' = 953E999

**Comment by ghost** [comment]
not enough connections setting in mangos config   up the number
