### ISSUE TITLE
Quest [The Second Trial]

### ISSUE THREAD

**Issue by Venom** [mangosR2/scriptdev2#37]
this is really old quest but its NOT WORKING ANYMORE.
i think there s need to be updated or somthing.

https://github.com/scriptdev2/scriptdev2/blob/master/scripts/eastern_kingdoms/eversong_woods.cpp

http://old02.wowhead.com/quest=9686

**Comment by ghost** [comment]
will check it out soon  it was removed yet in 335 so needs to fixed 8)

**Comment by ghost** [comment]
should be able to check this out tonight  just hold tight

**Comment by ghost** [comment]
after testing this it is working fine  u need quest 9690  first to be complete  report back if your still having an issue
