### ISSUE TITLE
Not working quests in Icecrown

### ISSUE THREAD

**Issue by klimbo** [mangosR2/scriptdev2#38]
The Valiant's Challenge (10 quests)
Among the Champions (4 quests)
http://pastebin.com/99PztLgp

script for npc_champion (copy/paste from npc_valiant's script)
http://pastebin.com/XNKseEuu

note:
these quests involving the vehicles and therefore I'm not offered to 'ytdb'

**Comment by klimbo** [comment]
Edit: (important)
Death Knight is not allowed in Champions League, because
quest giver Illyrie Nightfall(33770) has the wrong chain of quests.

need to fix it:
UPDATE quest_template SET PrevQuestId = 13794 WHERE entry IN (13793,13814,13791,13813);

it is also necessary (otherwise spell=63010 do not work)
UPDATE creature_template SET unit_flags = 8 WHERE entry IN
(33217,33316,33317,33318,33319,33320,33321,33322,33323,33324);

**Comment by ghost** [comment]
gonna get to this tonight  instead of two scripts we ll combine them ..... and just to answer any  the ahead thinkers these quest will need script because i believe this need vehicle support sincce your suppose to be on a mount correct?

**Comment by klimbo** [comment]
I guess, but  leave them if you doubt. (this is not so important)
The future will show whether it is true.

**Comment by ghost** [comment]
Huh lol.  Future will show if what is true and have read my inbox message

**Comment by ghost** [comment]
https://github.com/mangosR2/scriptdev2/commit/d05a4c4fab40b20596d2df92c6dd08490f035f3d
