### ISSUE TITLE
Ahn'kahet: The Old Kingdom

### ISSUE THREAD

**Issue by Venom** [mangosR2/scriptdev2#42]
bug.

on last boss npc

http://www.wowhead.com/npc=29311#article

when he using his spell http://www.wowhead.com/spell=57496 [Insanity]
phase is changing for your character its like invisiblity. and you are attacked by a npc with no model. when you kill that npc u stack in that phase of invisibility.  u cant remove that spell so you stack. 

didnt tested this on 5 players!   so there might be glitch or somthing for one player

**Comment by ghost** [comment]
this whole instance could use some love  sooner or later but when i get time ill pop in there

**Comment by rsa** [comment]
problem not only in this spell, need implement visual models stack and operate with this (see http://getmangos.com/community/topic/16965/spell-dispersion/ for example)

**Comment by rsa** [comment]
long time ago fixed :)
