### ISSUE TITLE
Halls of reflection SQL text

### ISSUE THREAD

**Issue by Venom** [mangosR2/scriptdev2#44]
BUG: wrong IDs   in game  showing < ERRORs > in gossips. 

-- Gossips
DELETE FROM `gossip_texts` WHERE `entry` BETWEEN -3594540 AND -3594530;
REPLACE INTO `gossip_texts` (`entry`, `content_default`, `content_loc8`, `comment`) VALUES
(-3668536, 'Lady Jaina, we are ready for next mission!', 'Джайна, мы готовы!',''),
(-3668537, 'Lady Jaina, Let\'s go!', 'Давай быстрее!', ''),
(-3668538, 'Lady Sylvanas, we are ready for next mission!', 'Сильвана, мы готовы!', ''),
(-3668539, 'Lady Sylvanas, Let\'s go!', 'Поехали!', ''),
(-3668540, 'Let\'s go!', 'Побежали!', '');

PROBLEM FIX:

-- Gossips
DELETE FROM `gossip_texts` WHERE `entry` BETWEEN -3594540 AND -3594530;
REPLACE INTO `gossip_texts` (`entry`, `content_default`, `content_loc8`, `comment`) VALUES
(-3594536, 'Lady Jaina, we are ready for next mission!', 'Джайна, мы готовы!',''),
(-3594537, 'Lady Jaina, Let\'s go!', 'Давай быстрее!', ''),
(-3594538, 'Lady Sylvanas, we are ready for next mission!', 'Сильвана, мы готовы!', ''),
(-3594539, 'Lady Sylvanas, Let\'s go!', 'Поехали!', ''),
(-3594540, 'Let\'s go!', 'Побежали!', '');

**Comment by ghost** [comment]
https://github.com/mangosR2/scriptdev2/commit/a4aa44fa1f5f25885000f1b1b673c7849c2eef22   good catch
