### ISSUE TITLE
Violet Hold, bad SQL DELETE FROM command 

### ISSUE THREAD

**Issue by Walkum** [mangosR2/scriptdev2#45]
https://github.com/Radicalmangos/devscriptdev2/commit/43dd62a0b78bacf7fe5269dbcd888ddf1db24192

**Comment by tibbi** [comment]
heh nice report, fixed with https://github.com/mangosR2/scriptdev2/commit/b3df7a972781818ef21e5e0b8e5497779cf6e18f
