### ISSUE TITLE
Culling of Stratholme

### ISSUE THREAD

**Issue by Walkum** [mangosR2/scriptdev2#46]
Hi, I tested recently the instance Culling of Stratholme, and is bugged :S, I made the quest of the 5 box, and when Chromi appears at Stratholme's entrance, I talk with her, and appear the three gossips. The third gossip is the gossip that activate de event, and when active then, doesn't work anything more, the event don't start.

MaNGOS version 11831.

(Sorry for the english, I am spanish)

Thanks in advance.

**Comment by Nevadas** [comment]
Im note sure thats the same problem , but walkum can you say the q is ended when you use the five boxes?
Also my question , works the events when you clear the boxes? I tryed this before the update and it dosnt work on the testserver.
But is also possibly it is another thing.

**Comment by Walkum** [comment]
Yea, it is that you say. When I finish the quest of the clear boxes, Chromi appears, I talk with her, and the event don't start. These is the bug :(

**Comment by Nevadas** [comment]
Sorry when i ask again, the quest is really finish ? You can give it to chromie ? Or only the counter in the upper middle shows 5/5 ?

**Comment by Walkum** [comment]
Yes, I can, and I talk with her for start the event, but is bug :(

**Comment by raynar** [comment]
When the counter shows 5/5 the quest isn't complete --> first bug
If you complete the quest by .quest complete, the npc that appears the event doesn't work--> second bug

**Comment by Nevadas** [comment]
Yes! exactly this is also my bug! *sign
Thats why i ask Walkum.

**Comment by ghost** [comment]
sorry all i just really have not had much time lately .. shit still have SWP outdoor pvp to remove  the whole ICC other issues  ect ect we 'll get to them one by one   .....  i glanced over this and it seems like while ago this was official removed from official sd2 and went to eventAI  our cos is a scripts we have had held on to i there might be DB incorrects and ect stuff  or shit the event might just not be there or finished

**Comment by Nevadas** [comment]
Thx for your answer FallenAngelx!

Take your time!

**Comment by Nevadas** [comment]
Hi FallenAngelX

I try the changes on CoS. It works fine for me!
It was not really everyithing (you wrote thsi in your commit) but the important things works!

Thank you very much!

**Comment by ghost** [comment]
honestly im still having alot of bugs lol  wtf do you mean it works for you???

**Comment by ghost** [comment]
ya alot of stuff is repaired but its far from being done ...  alot of dead code and ect stuff  i will be glad when ever i finally get done w this place  i have a feeling its gonna take awhile 8(

**Comment by Walkum** [comment]
Yea, now works great!!! Very thanks FallenAngel for your work ^^

**Comment by ghost** [comment]
you guys have to be kidding  ... maybe im missing something  u guys getting quest credit and able to get to second event  or npcs dont have crazy running  ..." scratches head, from what i see alot of bugs left "

**Comment by ghost** [comment]
https://github.com/mangosR2/scriptdev2/commit/bc5a025039a9b334798926cfe5b22eb3f6f06077

still little buggy  only first event has been tested   but the issue thats been reported has been fixed .. i will be continueing work on CoS  so if notice any more pls open new issues   8P

**Comment by Walkum** [comment]
Thx for the fixes, i will try it, but that the event worked by the other commits, is not kidding, seriously 8P, at player eyes the event works good.

thanks, if I can help you tell me ^^, good work fallen.

**Comment by ghost** [comment]
i guess your players arent as picky as mine 8P
