### ISSUE TITLE
Pit of Saron Bosses

### ISSUE THREAD

**Issue by Venom** [mangosR2/scriptdev2#48]
UPDATE `creature_template` SET `ScriptName`='boss_forgemaster_garfrost', `AIName` ='' WHERE `entry`=36494;

this boss dosnt have any sound IDs. and some of them are incorrect. for example when he enchants axe weapon. there goes boss_krick' sounds and on this boss death i can hear krick tolking.

here it is my correct eventAI audio+Text for that boss. 

modify it for ScriptDev2 fix.  sound IDs are correct and text is correct.

INSERT INTO `creature_ai_texts` VALUES ('-364941', 'Tiny creatures under feet, you bring Garfrost somthing good to eat ', '', '', '', '', '', '', '', '', '16912', '1', '0', '0', 'Garfrost aggro start');
INSERT  INTO `creature_ai_texts` VALUES ('-364942', 'Axe too weak. Garfrost make better and CRUSH YOU.', '', '', '', '', '', '', '', '', '16916', '1', '0', '0', 'Garfrost axe enchant');
INSERT INTO `creature_ai_texts` VALUES ('-364943', 'Garfrost tired of puny mortals. now your bones all freeze', '', '', '', '', '', '', '', '', '16917', '1', '0', '0', 'Garfrost mace enchant');
INSERT INTO `creature_ai_texts` VALUES ('-364944', 'Garfrost nope giant underpants clean. save boss great shame. for later.', '', '', '', '', '', '', '', '', '16915', '1', '0', '0', 'Garfrost death');

Tyrannus boss
UPDATE `creature_template` SET `ScriptName`='boss_scourgelord_tyrannus', `AIName` ='' WHERE `entry`=36658;

this boss is siting on his dragon and not coming down .  we just DPS dragon, kill it, and NO LOOT.

**Comment by ghost** [comment]
Confirm. After death of dragon, boss dissapeared.

**Comment by michalpolko** [comment]
I am only using Garfrost from PoS because the 2 remaining bosses aren't working well.
I hope I will be able to write new script for them in this month ;)

**Comment by rsa** [comment]
mostly rewrited.
