### ISSUE TITLE
[BUG] Oculus dracos

### ISSUE THREAD

**Issue by Walkum** [mangosR2/scriptdev2#49]
The issue is about the oculus dracos. The spells that use the vehicles of the dragons, works correctly without vehicle (for example when you use .cast ID), but when the caster is the vehicle, doesn't work correctly (the DPS spells don't give damage to the enemies, the heal spells don't heal, etc).

The spells:

Bronze dragon:
http://www.wowhead.com/spell=49840
http://es.wowhead.com/spell=49592

Emerald:
http://es.wowhead.com/spell=50341

Ruby:
http://es.wowhead.com/spell=50232

**Comment by ghost** [comment]
spell support is for core  8P

**Comment by Walkum** [comment]
These spells works correctly, but no in the dracos. Maybe is caused by vehicles (mangos), not script, i will open issue in the mangos repo, thx ^^

**Comment by Nevadas** [comment]
Hi Walkum, are you sure thats all dragon have problems?
On our system the Bronze dragon and his spells work fine.

**Comment by ghost** [comment]
moved to core
