### ISSUE TITLE
Icecrown citadel, Синдрагоса

### ISSUE THREAD

**Issue by ghost** [mangosR2/scriptdev2#50]
В битве с боссом Синдрагоса (http://ru.wowhead.com/npc=36853) часто происходит "не допризыв склепа". Появляется метка, потом вешается аура от склепа, но сам склеп не появляется. В результате выбраться нет возможности.

**Comment by Inquisitor** [comment]
ICC is rewrited. Is problem solved?

ЦЛК переписали. Проблема решена?

**Comment by Undergarun** [comment]
If problem persist, open new issue.
