### ISSUE TITLE
Рубиновое святилище, Балтар рожденный в битве, героический режим

### ISSUE THREAD

**Issue by ghost** [mangosR2/scriptdev2#51]
При битве с Балтаром (http://ru.wowhead.com/npc=39751) на героическом режиме, когда у босса чуть больше 3 миллионов хп, он вызывает копию. На самого Балтара вешается неуязвимость. Когда убивается копия неуязвимость снимается. Босс дальше спокойно бьется до 1 миллиона, а потом на него снова вешается неуязвимость. Никаких клонов у него при этом нет

**Comment by rsa** [comment]
в нормале копия вылазит на 50%, в героиках - на 66% и 33%. что, второй раз нету что ли?

**Comment by ghost** [comment]
Нету.

**Comment by rsa** [comment]
checked, not confirm. багов там много, но этого нет. проверяйте базу.
