### ISSUE TITLE
redeeming The Dead

### ISSUE THREAD

**Issue by Venom** [mangosR2/scriptdev2#52]
using mangosR2/TEST 

http://www.wowhead.com/quest=9685/redeeming-the-dead

blood elf paladin resurection spell quest is borken.

Problem:
using this item http://www.wowhead.com/item=24184    on npc http://www.wowhead.com/npc=17768  should resurect him and quest is Done. but  its only says.  OBJECTIVE COMPLATED.   but not the quest.

quest still not complated. i checked the older DB of this quest and there's nothing changed. its same.  problem is from core i think. quest can be complated only if i use .Die command on that npc.

**Comment by Venom** [comment]
http://www.scriptdev2.com/showthread.php?t=352&highlight=Redeeming+Dead&page=2

**Comment by ghost** [comment]
i dont have a sd2 account on their forums so cant check link 8P

**Comment by ghost** [comment]
https://github.com/mangosR2/scriptdev2/commit/74ade4fc764ca1f20196a7da1891a4b450e3c6e1
