### ISSUE TITLE
Some Missing Textes or Typos in boss_devourer_of_souls or error in sql

### ISSUE THREAD

**Issue by Nevadas** [mangosR2/scriptdev2#58]
In /northrend/icecrown_citadel/frozen_halls
I found 

```
SAY_MALE_1_AGGRO = -1632007,
SAY_FEMALE_AGGRO = -1632008,
SAY_MALE_1_SLAY_1 = -1632009,
```

But in the sql  mr00249_scriptdev2_icecrown_down.sql
missing this textes

Thx

**Comment by Nevadas** [comment]
Im not sure but i hope thats a simmilar problem with krick_and_ick and the texts are included but every its wrong with the numbers.

**Comment by rsa** [comment]
mostly rewrited
