### ISSUE TITLE
Another missing Textes in boss_krick_and_ick or error in sql

### ISSUE THREAD

**Issue by Nevadas** [mangosR2/scriptdev2#59]
Hi !

I found some other missing texts in 

boss_krick_and_ick.cpp

```
SAY_AGGRO = -1658024,
SAY_SLAY_1 = -1658025,
SAY_SLAY_2 = -1658026,
SAY_ORDER_STOP = -1658027,
SAY_ORDER_BLOW = -1658028,
SAY_TARGET_1 = -1658029,
```

This things are missing in the sql file "mr00249_scriptdev2_icecrown_down.sql"

Thx for your help!

**Comment by Nevadas** [comment]
I found out thats the texts are inside but with another Numbers.
Thats from the sql file:
-- Krick
(-1658010,'Our work must not be interrupted! Ick! Take care of them!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,16926,1,0,0,'Krick SAY_AGGRO'),
(-1658011,'Ooh...We could probably use these parts!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,16927,1,0,0,'Krick SAY_SLAY_1'),
(-1658012,'Arms and legs are in short supply...Thanks for your contribution!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,16928,1,0,0,'Krick SAY_SLAY_2'),
(-1658013,'Enough moving around! Hold still while I blow them all up!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,16929,1,0,0,'Krick SAY_BARRAGE_1'),
(-1658014,'Krick begins rapidly conjuring explosive mines!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,3,0,0,'Krick SAY_BARRAGE_2'),
(-1658015,'Quickly! Poison them all while they''re still close!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,16930,1,0,0,'Krick SAY_POISON_NOVA'),
(-1658016,'No! That one! That one! Get that one!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,16931,1,0,0,'Krick SAY_CHASE_1'),
(-1658017,'I''ve changed my mind...go get that one instead!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,16932,1,0,0,'Krick SAY_CHASE_2'),
(-1658018,'What are you attacking him for? The dangerous one is over there,fool!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,16933,1,0,0,'Krick SAY_CHASE_3'),

I dont no where is right! In sql or in script?

**Comment by rsa** [comment]
mostly rewrited.
