### ISSUE TITLE
Pit of saron

### ISSUE THREAD

**Issue by KiriX** [mangosR2/scriptdev2#6]
1) Не открывается ледяная стена при убийстве первых двух боссов.
Ну да это не проблема - правится так: https://gist.github.com/1039636
Но далее у меня возникло несколько вопросов:
1) В YTDB не стоит в мире боссов Крик и собственно главного босса. На месте Крика стоит только Ик - он же является вехиклом для Крика. Аналогично для мэйн-босса - висит в воздухе Иней, который является вехиклом мэйн-босса.
Беда в том, что сидящий на вехикле НПС хоть и прорисовывается в базе, но по сути не имеет скрипта - он не грузится... И НПС этот сидящий не кастует спеллы (Крик сидящий на Ике должен поливать спеллами пати, в то время как Ик наносит только физ-дамаг). Как бы сделать так, чтобы НПС на вехикле (созданный из таблицы vehicle_acessory) мог кастовать да и вообще слезать со своего вехикла?
Да и хер с ним с этим Криком! Интереснее ситуация с главным боссом.
Как бы реализовать сход мейна с дракона и начало схватки?

**Comment by rsa** [comment]
крик стоять не должен.он спавнится по эвенту ику на шею. ему надо развесить флаги и написать скрипт, поливать будет только в путь.
то же самое и с тираннусом. при спавне сажаешь его спеллом на дракона, в нужный момент removeAura(CONTROL_VEHICLE) и оба пошли драться по отдельности.

**Comment by KiriX** [comment]
rsa - как всё просто по твоим словам выходит =)))

**Comment by rsa** [comment]
просто только кошки родятся. мне уже давно наскучило писать скрипты...

**Comment by Sharki** [comment]
проблема осталась, нет тираннуса, только иней, можно ли как то исправить эту проблему, так же не нашел Сильвану стоящую на выходе из пещеры к Тираннусу(даже в ГМ режиме)

**Comment by rsa** [comment]
а что, кто-то скрипт уже написал?

**Comment by Sharki** [comment]
нельзя ли в коде поменять Инея и сделать что бы на его месте стоял Тираннус? хотел бы узнать ид Сильваны, которая должна появляться после смерти Тираннуса
