### ISSUE TITLE
Utgarde Pinnacle, Missing Sql

### ISSUE THREAD

**Issue by Nevadas** [mangosR2/scriptdev2#61]
Hi Reamer ! Thx for your work!
It is possibly thats some sql things are missed in your sql file?

I search for the insert of scriptnames: event_call_flames , npc_spirit_fount !

Can you help?

I dont now anybody need this:

INSERT INTO scripted_event_id VALUES (17841,'event_call_flames');
UPDATE creature_template SET ScriptName="npc_spirit_fount" WHERE entry= 27339;

Thsi was for the missing scripts in DB. I hope thats right! ;-)

PS.: I wrote this comment on the last commit for compile fix but i dont sure thats everybody read this!

**Comment by Venom** [comment]
thanks...

**Comment by Reamer** [comment]
to 27339: better use eventai for this npc

INSERT INTO scripted_event_id VALUES (17841,'event_call_flames');
-> this should be right
