### ISSUE TITLE
Script unloading crash(?)

### ISSUE THREAD

**Issue by michalpolko** [mangosR2/scriptdev2#64]
http://pastebin.com/v3RB98yR

Happens with every .server restart command.
Anybody knows why this occurs? I think it started a few months ago...

Platform is some Linux (Ubuntu? Debian?), I don't remember which one exactly, I'm not the admin  ;P

**Comment by raynar** [comment]
me happens too :S

**Comment by ghost** [comment]
its a TBB crash

**Comment by raynar** [comment]
I don't use tbb :S

**Comment by ghost** [comment]
#2  0x00007f96c03021c0 in tbb::assertion_failure (filename=0x7f96c0307b68 "../../src/tbbmalloc/MemoryAllocator.cpp", line=2108,
    expression=0x7f96c0308468 "isProperlyPlaced(objectToFree, block)", comment=0x0) at ../../src/tbb/tbb_assert_impl.h:80
#3  0x00007f96c0305273 in scalable_free (object=0x7f96a5362a28) at ../../src/tbbmalloc/MemoryAllocator.cpp:2108

**Comment by raynar** [comment]
yes you're right, but I have ransom similar crashes when I use server restart command

**Comment by rsa** [comment]
tbb now has broken (or may be incompartible with current OS) memory manager. his normally work on winXP. disable tbb on other OS, even be have similate problems.
PS may be need renew TBB, but i not check.
