### ISSUE TITLE
Errors in the file

### ISSUE THREAD

**Issue by Agustin1010** [mangosR2/scriptdev2#65]
IN mr00261_mangos_game_event_stuff.sql: http://pastebin.com/TvvpxrDu

**Comment by tibbi** [comment]
r2 doesnt even have such file. Where you have it from ?

**Comment by Agustin1010** [comment]
https://github.com/mangosR2/scriptdev2/blob/master/sql_mr/mr00261_mangos_game_event_stuff.sql

**Comment by Agustin1010** [comment]
I'm stupid mistake

**Comment by Agustin1010** [comment]
There is no error

**Comment by Agustin1010** [comment]
https://github.com/mangosR2/mangos/issues/560

**Comment by Agustin1010** [comment]
You can arrange

**Comment by tibbi** [comment]
oh its in sd part.. my bad

**Comment by tibbi** [comment]
first error should be fixed with https://github.com/mangosR2/scriptdev2/commit/e9ffd1131c3a169e38f8806df56f44461df2d771 , but those 2 errors werent in that file.

**Comment by Agustin1010** [comment]
Thanks
