### ISSUE TITLE
Errors in the file

### ISSUE THREAD

**Issue by Agustin1010** [mangosR2/scriptdev2#66]
In: https://github.com/mangosR2/scriptdev2/blob/master/sql_mr/mr00262_mangos_culling_of_stratholme.sql
Error: http://pastebin.com/ztbnesb8 + http://pastebin.com/hMaxvUnh
In: https://github.com/mangosR2/scriptdev2/blob/master/sql_mr/mr00249_scriptdev2_Quest_Script_stuff.sql
Attention: The second time you run the file can not be put. Will be many error logs

**Comment by tibbi** [comment]
should be fixed with https://github.com/mangosR2/scriptdev2/commit/5c6f951ce88b506dc4b53ef4e45a5629f445cfc6
