### ISSUE TITLE
Problem in guard

### ISSUE THREAD

**Issue by ghost** [mangosR2/scriptdev2#68]
http://s11.postimage.org/rmxmy11n7/Wo_WScrn_Shot_121211_125811.jpg
http://s8.postimage.org/ob5efpl2d/Wo_WScrn_Shot_121211_130038.jpg
http://s10.postimage.org/dpp43kz9l/Wo_WScrn_Shot_121211_130039.jpg
A lot of this mob it's summon , this just a little of them i can be Screen Shot.

**Comment by xarly** [comment]
The only thing you can do just now is revert this commit
https://github.com/mangosR2/scriptdev2/commit/9431b6e0fdf13e26f5fc0e70f9df10df4088c123

**Comment by ghost** [comment]
https://github.com/fallenangelX/Infinity/commit/37302a82ba4094a9b47a27ad687d5201c9452a27. Small fix for it make it friendly and still holds some off style

**Comment by rsa** [comment]
fixed in 0304
