### ISSUE TITLE
Compile Errors

### ISSUE THREAD

**Issue by teffcz** [mangosR2/scriptdev2#7]
Hi dev. team.

when i compile Scriptdev2 i have this errors

mangos/src/bindings/ScriptDev2/scripts/outland/coilfang_reservoir/serpent_shrine/boss_the_lurker_below.cpp: In func
tion 'bool GOUse_go_strange_pool(Player_, GameObject_)':

mangos/src/bindings/ScriptDev2/scripts/outland/coilfang_reservoir/serpent_shrine/boss_the_lurker_below.cpp:133:26:
error: 'class Player' has no member named 'CompletedAchievement'

make[2]: **\* [src/bindings/ScriptDev2/CMakeFiles/mangosscript.dir/scripts/outland/coilfang_reservoir/serpent_shrine/boss_the_lurker_belo
w.cpp.o] Error 1
make[1]: **\* [src/bindings/ScriptDev2/CMakeFiles/mangosscript.dir/all] Error 2
make: **\* [all] Error 2

Thank you for your help:)

**Comment by Inquisitor** [comment]
First of all, why you are using make instead of CMake as MaNGOS recommends?

**Comment by teffcz** [comment]
I read the instructions for compiling, and the problem occurred during a newer version of SD2 ... I use

https://github.com/mangos/mangos
AND
mangosR2 / scriptdev2

can be a problem in that?

**Comment by cyberaven** [comment]
you use diffrent ver. scriptdev2 and mangos.

**Comment by Inquisitor** [comment]
please use our mangosR2/mangos branch
