### ISSUE TITLE
The DK's quest problem

### ISSUE THREAD

**Issue by fisher19811221** [mangosR2/scriptdev2#72]
The quest (http://www.wowhead.com/quest=12680) can't be finished .The spell of the horse is missing.... So,i can't  return the horse.

i used the latest YTDB.sorry,my poor english.

**Comment by rsa** [comment]
RTFM for DB update sequence.

**Comment by Venom** [comment]
check this bug out :D

http://www.wowhead.com/quest=12755
faction is changed and every npc is GREEN status now.

but when you go near them they still attack you. and u cant do anything at all...

screen:
http://imageshack.us/photo/my-images/806/wowscrnshot013012123707.jpg/

i had to change faction 35 to quest giver.....
