### ISSUE TITLE
[Utgarde Pinnacle] Crash in Boss Skadi

### ISSUE THREAD

**Issue by Undergarun** [mangosR2/scriptdev2#74]
http://pastebin.com/xPBYxGuL

**Comment by Undergarun** [comment]
http://pastebin.com/iwsr2Zb9

**Comment by Undergarun** [comment]
Still happens. Some fix Reamer or better to temporary disabled this boss?

**Comment by Reamer** [comment]
sry i don't know, wy this crash appear, better you disable this boss.
One possibilty the cast to skadi ai

**Comment by Reamer** [comment]
maybe you can explain when the crash appear. I have no idea, because i have no crash. But on my server i have not so much players.

**Comment by Undergarun** [comment]
Not yet fixed http://pastebin.com/B6G6tJVA :(

**Comment by Undergarun** [comment]
Next attemp over: http://pastebin.com/ML17tGxt

**Comment by Undergarun** [comment]
http://pastebin.com/x0X2Z1cp Fucking Skadi

**Comment by rsa** [comment]
this - other crush :) very good.

**Comment by Undergarun** [comment]
Finally fixed ;-) Thank you.

**Comment by rsa** [comment]
wow. i'm in shock.
