### ISSUE TITLE
Отсутствует файл ulduar_teleport.cpp

### ISSUE THREAD

**Issue by stink** [mangosR2/scriptdev2#75]
Собственно не собирается SD2:
Ошибка    2   error C1083: Не удается открыть файл источник: ..\scripts\northrend\ulduar\ulduar\ulduar_teleport.cpp: No such file or directory    D:\compile\mangos\src\bindings\scriptdev2\VC100\c1xx    ScriptDev2

Ну и в догонку:
Предупреждение    1   warning C4018: >: несоответствие типов со знаком и без знака    D:\compile\mangos\src\bindings\scriptdev2\scripts\northrend\ulduar\ulduar\boss_ignis.cpp    119 1   ScriptDev2

Но это не критично :)

**Comment by Reamer** [comment]
maybe you can write in english, then i can help you

**Comment by stink** [comment]
Actually is not going to SD2:
Error 2 error C1083: Can not open source file: .. \ scripts \ northrend \ ulduar \ ulduar \ ulduar_teleport.cpp: No such file or directory D: \ compile \ mangos \ src \ bindings \ scriptdev2 \ VC100 \ c1xx ScriptDev2

And:
Warning 1 warning C4018:>: type mismatch with signed and unsigned D: \ compile \ mangos \ src \ bindings \ scriptdev2 \ scripts \ northrend \ ulduar \ ulduar \ boss_ignis.cpp 119 1 ScriptDev2

But it is not critical:)

I'm use GoogleTranslate. Sorry =)

**Comment by Reamer** [comment]
ulduar_teleport.cpp functions are move into the file ulduar.cpp
You can delete ulduar_teleport.cpp out of you VC100-project

**Comment by Reamer** [comment]
PS: I have no luck for a good translation from russia to german^^

**Comment by rsa** [comment]
but your make good answer :)
