### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by conan513** [mangosR2/scriptdev2#78]
I've got some error with the lastest build: http://pastebin.com/h6tEs67D
Is this normal or I forget something?

**Comment by Inquisitor** [comment]
So what's the error? I see random DB related errors, not core related.

**Comment by ghost** [comment]
The only real error here are the creature s and some of the scriptname settings

**Comment by Inquisitor** [comment]
So just reapply all the SD2 DB updates from _/sql/updates_ and _/sql_mr_. If there still will be some nonexisting scriptnames in DB, just remove them.

**Comment by ghost** [comment]
NO reruning all updates in sd2 folder will screw sd2 up half that crap in sql updates don't fit R2 you just screw it all up and only reason there any sql uppdates at all is cause merger aren't cleaning out old ones or unneeded ones

**Comment by ghost** [comment]
https://github.com/simplexo. U can find 99%the of all db fixes plus more here for and deleting nonexisting scriptname WHAT check for typos check ect ect before u blindly delete ... damn iriskin I know your smarter then this
