### ISSUE TITLE
Scarlet Enclav

### ISSUE THREAD

**Issue by bondiano** [mangosR2/scriptdev2#8]
Неработают некторые квесты ДК:
   1) "Подарок с подвохом" (http://ru.wowhead.com/quest=12698)
Вурдалаки (http://ru.wowhead.com/npc=28845) спавнятся и мгновенно умирают. Если убрать у вурдалаков С++ скрипт, то они не умирают, но и не сдаются.
   2) Нету спеллов у некоторых вехиклов:
(http://ru.wowhead.com/npc=28605) (http://ru.wowhead.com/npc=28607) Не сдать кв (http://ru.wowhead.com/quest=12680)
(http://ru.wowhead.com/npc=28782) Не сдать кв (http://ru.wowhead.com/quest=12687)
(http://ru.wowhead.com/npc=28833) Не сделать кв (http://ru.wowhead.com/quest=12701)
А также лошадки в Серебрянном турнире(http://ru.wowhead.com/npc=33843)(http://ru.wowhead.com/npc=33842) и может быть еще что-то (Мотоциклы в Ульдуаре). Странно то, что, допустим Око Акеруса работает исправно и спеллы у него есть.

Some Quests of Death Knight:
   1) "The Gift That Keeps On Giving" (http://www.wowhead.com/quest=12698) 
Scarlet Ghoul (http://www.wowhead.com/npc=28845) spawn and instantly die. If you delete C++ script from ghouls, they do not die, but quest can not complete
   2) Some vehicles have not its spells 
(Http://www.wowhead.com/npc=28605) (http://www.wowhead.com/npc=28607) Quest can not complete (http://ru.wowhead.com/quest=12680) 
(Http://www.wowhead.com/npc=28782) Quest can not complete (http://www.wowhead.com/quest=12687) 
(Http://www.wowhead.com/npc=28833) Quest can not complete (http://www.wowhead.com/quest=12701) 
As well as horses in Crusaders Coliseum (http://www.wowhead.com/npc=33843) (http://www.wowhead.com/npc=33842) and may be something else (vehicles in Ulduar). But Eye of Acherus working properly and it have its spells

----- Sorry for my English

**Comment by ghost** [comment]
ok do dont  understand everything  but vehicles right now are buggy til one of our veterns/Supercodes can figure out fix 

нормально сделать не понимаю, все, кроме автомобилей прямо сейчас глючат сезам один из наших veterns / Supercodes можете выяснить, исправить  <- might not be right ... i  tried

**Comment by bondiano** [comment]
да верно вехиклы это одна проблема....но "Подарок с подвохом" (http://ru.wowhead.com/quest=12698) не как не могу починить.
Yes, vehicles it's always bug... But quest "The Gift That Keeps On Giving" (http://www.wowhead.com/quest=12698), i can't fix.

**Comment by ghost** [comment]
the quest is working  just tested  there is a new bug since i fixed this ghouls are spawning dead  this wasnt happening when last tested this .. something broke recently

**Comment by ghost** [comment]
gift of the harvestor quest is working now since last sd2 revision  rest of quest are bugged from recent cores changes and will be retested and fixed and polished again after core is fix 8)  very soon
