### ISSUE TITLE
toc double spawn

### ISSUE THREAD

**Issue by ROKB** [mangosR2/scriptdev2#86]
tochm 2nd named double spawn.
tocru anub double spawn.

**Comment by Reamer** [comment]
What? I unterstand nothing

**Comment by ROKB** [comment]
start phase and spawn creature. but double spawn creature(2 creature)

**Comment by Reamer** [comment]
instance? encounter? please more informations

**Comment by ROKB** [comment]
http://pastebin.com/CzJDkKKS

**Comment by rsa** [comment]
i already see this crush, but no addons on this creature in my db. also no double spawn. check your DB.

**Comment by ROKB** [comment]
@rsa me too, no have creature addons. anyway plz check crush 8P

**Comment by rsa** [comment]
sorry, i not see in crush anything related to core. seems, that getting from DB data for summoned creature incorrect. recheck it manually.

**Comment by Venom** [comment]
i have this problem. in Trial of Champion....

players can summon bosses as many times as they talk to summoning npc.

if 3 players talk to npc.  then 6 boss will be summoned
