### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ghost** [mangosR2/scriptdev2#87]
sd2 isnt able to be compiled with the mangos repo of mangosR2.. help/fix?

**Comment by ghost** [comment]
lol u we need the error were not their over your shoulder looking at the screen

**Comment by Faq** [comment]
where is the error msg?

**Comment by ghost** [comment]
there is no error msg.. sd2 just dont compile lol.. everythings fine and then failed 1, 0 sucess

**Comment by rsa** [comment]
not confirm.
