### ISSUE TITLE
Crash possible related to Rubi Sanctum

### ISSUE THREAD

**Issue by Undergarun** [mangosR2/scriptdev2#89]
http://pastebin.com/UKMnB3f5

**Comment by Inquisitor** [comment]
Uhm... Why do you think so?

**Comment by Venom** [comment]
scriptdev2 is really messedup  lot of bugs little bugs.  

for example:  Trial of Champion http://www.wowhead.com/npc=34928#article boss http://www.wowhead.com/spell=66515 spell dosnt come off. and stays on it forever. impossible to kill boss.

Pit of Saron  -   EVENT and BOSS  SOUNDS + TESTS is really wrong. every single sound or text is wrong. 

Hall of Reflection.  - lich king dosnt summon ICE WALLS. and if you run too far from him.  he dosnt summon any undead ghouls.  then if he dosnt summon ghouls, Sylvana never brake that ICE WALL.....

Forge of Souls.  -  http://www.wowhead.com/npc=36497  Bronjahm casting his healing spells too quickly. too much.
 i checked the Official....   there also problems with quests in this instance.   only GMs can see quest complate Sylvana. when killing http://www.wowhead.com/npc=36502

DK quests.  http://www.wowhead.com/quest=12687  when u stealing the horse, it is Disappearing too fast.  u cant take the horse to the quest giver.

**Comment by Undergarun** [comment]
@Venom Open new issue for every instance. Those bug reports have no sense here.

@Inquisitor My players report crash in some halion phase related to same % of live.

**Comment by raynar** [comment]
@Undergarun sorry spanish but ir more quickly: Halion tira el server sobre el 40%, nosotros tocamos el script y lo hicimos un poco mejor, échale un vistazo si quieres. Al menos caerse no se cae xD

**Comment by Undergarun** [comment]
@raynar Puedes linkarme el commit? Lo testeo y si va mejor actualizo el de R2. ¿Arregla también el problema de los portales para que se pueda matar a Halion? Gracias ;-)

**Comment by raynar** [comment]
@Undergarun si todo eso esta arreglado, pero no hay un commit en si, creo que te saldria mejor pillar el codigo entero y probarlo porque son muchos commits

**Comment by carlos93** [comment]
@undergarun el script esta hecho por mi y son muchos commits testeando cosas, pero si quieres optimizarlo todo tuyo.

https://github.com/Radicalmangos/devscriptdev2/blob/master/scripts/northrend/ruby_sanctum/boss_halion.cpp

Tambien decirte que los otros 2 tambien estan modificados (saviana y baltharus) pero esos creo que no tienen bugs ;).

**Comment by Undergarun** [comment]
@carlos93 @raynar  Muchas gracias, lo reviso y porteo a R2 ;-)
