### ISSUE TITLE
Some script use issues in mr00001_mangos_outdoor_pvp.sql

### ISSUE THREAD

**Issue by Undergarun** [mangosR2/scriptdev2#9]
This ScriptNames are missing:

ERROR:SD2: Script registering but ScriptName outdoor_pvp_eastern_plaguelands is not assigned in database. Script will not be used.
ERROR:SD2: Script registering but ScriptName outdoor_pvp_silithus is not assigned in database. Script will not be used.

But world_template only can handler one ScriptName per map, so maybe script merge is needed

outdoor_pvp_eastern_plaguelands with outdoor_pvp_eastern_kingdoms
and outdoor_pvp_kalimdor with outdoor_pvp_silithus

**Comment by rsa** [comment]
see outdoor_pvp_zone_selector. in R2 used another methot to access zone scripts.
