### ISSUE TITLE
Trial of the Crusader

### ISSUE THREAD

**Issue by ghost** [mangosR2/scriptdev2#93]
Since Mmap update this instance isn't working anymore. I event added zone ignore 4722 and still same thing... 
I mean not even first boss gormak isn't showing up... I receive only entering combat and halp a sec later leaving combat...

Respect

**Comment by raynar** [comment]
You must ignore 649 --> that's the mapid for Trial of Crusader

**Comment by ghost** [comment]
ty...how do I find out all the maps what they are?

**Comment by raynar** [comment]
you have 2 methods. 
I go to areatrigger_teleport, search the instance (entrance, no exit) and see target_map.

**Comment by Reamer** [comment]
GM-command: ".gps"

**Comment by ghost** [comment]
ty
