### ISSUE TITLE
Visibility in ICC

### ISSUE THREAD

**Issue by carlos93** [mangosR2/scriptdev2#95]
Hi, is there any way for increase visibility only in ICC?, else it generate a lot of lag :S.

We need DEFAULT_VISIBILITY_INSTANCE = 500 for Lich King encounter ;)

Thanks!

**Comment by rsa** [comment]
not 500, 400 sufficient. is i check, increasing to 500 not generated big additional lags (~5% additional load).
PS for one instance - very hard and not needed.
