### ISSUE TITLE
Possible crash in boss_malygos.cpp

### ISSUE THREAD

**Issue by RangerRU** [mangosR2/scriptdev2#96]
/ scripts / northrend / nexus / eye_of_eternity / boss_malygos.cpp

in code: void SummonedCreatureJustDied(Creature\* pSummoned)

if m_creature->getVictim() is NULL - we are have crash

For example, use command .die on summoned creature in GM mode

P.S. Sorry for my bad English

**Comment by mns** [comment]
Replace m_creature->getVictim()->SummonCreature(...) with m_creature->SummonCreature(....) and feedback result please .

**Comment by RangerRU** [comment]
тогда проще проверку сделать может быть ?

if (!m_creature || !m_creature->getVictim())
    return;

**Comment by mns** [comment]
m_creature always is true
I thing not need Victim pointer for summoning .
more code cause less performance.
I like less codes with best result :)

**Comment by RangerRU** [comment]
ну смотрите сами

предупрежден-вооружен
