### ISSUE TITLE
Spells bugged.

### ISSUE THREAD

**Issue by carlos93** [mangosR2/scriptdev2#98]
Since X commit those spells start to be bugged. I think that the problem appears after https://github.com/mangosR2/mangos/commit/8efc1ac47c27d4b7ea8ba71a858ff3b172d5c7e7
http://www.wowhead.com/spell=70701
http://www.wowhead.com/spell=72454

They don't do damage and in SpellEffects.cpp Spell::EffectSchoolDMG, they have code. Before they work :S

Thanks.

**Comment by Angarius** [comment]
confirmed!
And I think there is a Problem with the green and orange "blobs" from the Boss Professor Putricide.
This issue I'll be watching again but more accurate and better prepare. I'll be in touch as soon as I have all the information together.

**Comment by softbest** [comment]
this commit is correct. i test the mangos whitout this commit

**Comment by rsa** [comment]
need confirmation and open new issue, if need.
