### ISSUE TITLE
Spiders (36725) in ICC get instant aggro by entering the instance

### ISSUE THREAD

**Issue by ZuSe** [mangosR2/scriptdev2#99]
As the headline says.. there is a bug with the spiders in ICC. You get instant aggro by them, when u enter the instance.
You are instantly in combat and after 10 sec the spiders arrive at the entrance and start attacking you.

I had a look on the EventAI and aura-entry.. didnt find any errors. Hope someone around here, who knows the sd2-stuff better, has an idea.

LInk to creature : http://old.wowhead.com/npc=36725/nerubar-broodkeeper

Additional Information:
MaNGOS/0.17.0 (Revision 11928)
mangosR2 branch (\* \* R2 Revision 1823 commit 7b99061fb45cc9c01dbb184e3e48d2e56a73756e) for Linux_x64 (little-endian)
ScriptDev2 (for MaNGOS 11812+)_2319_RuDB_43Revision [2484] Revision R2 [0377](7b99061fb45cc9c01dbb184e3e48d2e56a73756e) \* \* (Unix)
YTDB_0.14.4_R617_MaNGOS_R11928_SD2_R2478_ACID_R309c_RuDB_R47
ACID 3.0.9c 'Streamlined Perfection' - Full Release for MaNGOS (3.3.5a Client)

**Comment by Zakamurite** [comment]
the problem is with eventAI
UPDATE `creature_template` SET `AIName`='' WHERE `entry` = 36725;

**Comment by rsa** [comment]
this - bad implementation of start event in ICC.

**Comment by michalpolko** [comment]
As far as I remember, those creatures have currently set to aggro whenever some friendly unit moves in los. But they aggro randomly ;/
I was said that they should aggro when a player walks into one of traps that are present in that area.
